# generated by 'xml2py'
# flags 'cublas.xml -c -d -v -l cublas'
#gccxmlparser.py: Converter: attrs = {'context': '_90', 'name': 'operator 1', 'demangled': 'dim3::operator uint3()', 'mangled': '_ZN4dim3cv5uint3Ev', 'id': '_606', 'access': 'public', 'returns': '_27', 'location': 'f4:396', 'file': 'f4', 'inline': '1', 'endline': '396', 'line': '396'} (implement me)
from cuda.utils import get_lib
from ctypes import *

_libraries = {}
_libraries['cublas'] = get_lib('cublas')
STRING = c_char_p


_FP_NORMAL = 4
_FP_SUPERNORMAL = 6
_FP_SUBNORMAL = 5
_FP_INFINITE = 2
_FP_NAN = 1
_FP_ZERO = 3
float_t = c_float
double_t = c_double

# values for unnamed enumeration
# /usr/include/architecture/i386/math.h 117
__math_errhandling = _libraries['cublas'].__math_errhandling
__math_errhandling.restype = c_uint
# __math_errhandling()
__math_errhandling.argtypes = []
__math_errhandling.__doc__ = \
"""unsigned int __math_errhandling()
/usr/include/architecture/i386/math.h:117"""
# /usr/include/architecture/i386/math.h 137
__fpclassifyf = _libraries['cublas'].__fpclassifyf
__fpclassifyf.restype = c_int
# __fpclassifyf(p1)
__fpclassifyf.argtypes = [c_float]
__fpclassifyf.__doc__ = \
"""int __fpclassifyf(float p1)
/usr/include/architecture/i386/math.h:137"""
# /usr/include/architecture/i386/math.h 138
__fpclassifyd = _libraries['cublas'].__fpclassifyd
__fpclassifyd.restype = c_int
# __fpclassifyd(p1)
__fpclassifyd.argtypes = [c_double]
__fpclassifyd.__doc__ = \
"""int __fpclassifyd(double p1)
/usr/include/architecture/i386/math.h:138"""
# /usr/include/architecture/i386/math.h 139
__fpclassify = _libraries['cublas'].__fpclassify
__fpclassify.restype = c_int
# __fpclassify(p1)
__fpclassify.argtypes = [c_longdouble]
__fpclassify.__doc__ = \
"""int __fpclassify(long double p1)
/usr/include/architecture/i386/math.h:139"""
# /usr/include/architecture/i386/math.h 262
acos = _libraries['cublas'].acos
acos.restype = c_double
# acos(p1)
acos.argtypes = [c_double]
acos.__doc__ = \
"""double acos(double p1)
/usr/include/architecture/i386/math.h:262"""
# /usr/include/architecture/i386/math.h 263
acosf = _libraries['cublas'].acosf
acosf.restype = c_float
# acosf(p1)
acosf.argtypes = [c_float]
acosf.__doc__ = \
"""float acosf(float p1)
/usr/include/architecture/i386/math.h:263"""
# /usr/include/architecture/i386/math.h 265
asin = _libraries['cublas'].asin
asin.restype = c_double
# asin(p1)
asin.argtypes = [c_double]
asin.__doc__ = \
"""double asin(double p1)
/usr/include/architecture/i386/math.h:265"""
# /usr/include/architecture/i386/math.h 266
asinf = _libraries['cublas'].asinf
asinf.restype = c_float
# asinf(p1)
asinf.argtypes = [c_float]
asinf.__doc__ = \
"""float asinf(float p1)
/usr/include/architecture/i386/math.h:266"""
# /usr/include/architecture/i386/math.h 268
atan = _libraries['cublas'].atan
atan.restype = c_double
# atan(p1)
atan.argtypes = [c_double]
atan.__doc__ = \
"""double atan(double p1)
/usr/include/architecture/i386/math.h:268"""
# /usr/include/architecture/i386/math.h 269
atanf = _libraries['cublas'].atanf
atanf.restype = c_float
# atanf(p1)
atanf.argtypes = [c_float]
atanf.__doc__ = \
"""float atanf(float p1)
/usr/include/architecture/i386/math.h:269"""
# /usr/include/architecture/i386/math.h 271
atan2 = _libraries['cublas'].atan2
atan2.restype = c_double
# atan2(p1, p2)
atan2.argtypes = [c_double, c_double]
atan2.__doc__ = \
"""double atan2(double p1, double p2)
/usr/include/architecture/i386/math.h:271"""
# /usr/include/architecture/i386/math.h 272
atan2f = _libraries['cublas'].atan2f
atan2f.restype = c_float
# atan2f(p1, p2)
atan2f.argtypes = [c_float, c_float]
atan2f.__doc__ = \
"""float atan2f(float p1, float p2)
/usr/include/architecture/i386/math.h:272"""
# /usr/include/architecture/i386/math.h 274
cos = _libraries['cublas'].cos
cos.restype = c_double
# cos(p1)
cos.argtypes = [c_double]
cos.__doc__ = \
"""double cos(double p1)
/usr/include/architecture/i386/math.h:274"""
# /usr/include/architecture/i386/math.h 275
cosf = _libraries['cublas'].cosf
cosf.restype = c_float
# cosf(p1)
cosf.argtypes = [c_float]
cosf.__doc__ = \
"""float cosf(float p1)
/usr/include/architecture/i386/math.h:275"""
# /usr/include/architecture/i386/math.h 277
sin = _libraries['cublas'].sin
sin.restype = c_double
# sin(p1)
sin.argtypes = [c_double]
sin.__doc__ = \
"""double sin(double p1)
/usr/include/architecture/i386/math.h:277"""
# /usr/include/architecture/i386/math.h 278
sinf = _libraries['cublas'].sinf
sinf.restype = c_float
# sinf(p1)
sinf.argtypes = [c_float]
sinf.__doc__ = \
"""float sinf(float p1)
/usr/include/architecture/i386/math.h:278"""
# /usr/include/architecture/i386/math.h 280
tan = _libraries['cublas'].tan
tan.restype = c_double
# tan(p1)
tan.argtypes = [c_double]
tan.__doc__ = \
"""double tan(double p1)
/usr/include/architecture/i386/math.h:280"""
# /usr/include/architecture/i386/math.h 281
tanf = _libraries['cublas'].tanf
tanf.restype = c_float
# tanf(p1)
tanf.argtypes = [c_float]
tanf.__doc__ = \
"""float tanf(float p1)
/usr/include/architecture/i386/math.h:281"""
# /usr/include/architecture/i386/math.h 283
acosh = _libraries['cublas'].acosh
acosh.restype = c_double
# acosh(p1)
acosh.argtypes = [c_double]
acosh.__doc__ = \
"""double acosh(double p1)
/usr/include/architecture/i386/math.h:283"""
# /usr/include/architecture/i386/math.h 284
acoshf = _libraries['cublas'].acoshf
acoshf.restype = c_float
# acoshf(p1)
acoshf.argtypes = [c_float]
acoshf.__doc__ = \
"""float acoshf(float p1)
/usr/include/architecture/i386/math.h:284"""
# /usr/include/architecture/i386/math.h 286
asinh = _libraries['cublas'].asinh
asinh.restype = c_double
# asinh(p1)
asinh.argtypes = [c_double]
asinh.__doc__ = \
"""double asinh(double p1)
/usr/include/architecture/i386/math.h:286"""
# /usr/include/architecture/i386/math.h 287
asinhf = _libraries['cublas'].asinhf
asinhf.restype = c_float
# asinhf(p1)
asinhf.argtypes = [c_float]
asinhf.__doc__ = \
"""float asinhf(float p1)
/usr/include/architecture/i386/math.h:287"""
# /usr/include/architecture/i386/math.h 289
atanh = _libraries['cublas'].atanh
atanh.restype = c_double
# atanh(p1)
atanh.argtypes = [c_double]
atanh.__doc__ = \
"""double atanh(double p1)
/usr/include/architecture/i386/math.h:289"""
# /usr/include/architecture/i386/math.h 290
atanhf = _libraries['cublas'].atanhf
atanhf.restype = c_float
# atanhf(p1)
atanhf.argtypes = [c_float]
atanhf.__doc__ = \
"""float atanhf(float p1)
/usr/include/architecture/i386/math.h:290"""
# /usr/include/architecture/i386/math.h 292
cosh = _libraries['cublas'].cosh
cosh.restype = c_double
# cosh(p1)
cosh.argtypes = [c_double]
cosh.__doc__ = \
"""double cosh(double p1)
/usr/include/architecture/i386/math.h:292"""
# /usr/include/architecture/i386/math.h 293
coshf = _libraries['cublas'].coshf
coshf.restype = c_float
# coshf(p1)
coshf.argtypes = [c_float]
coshf.__doc__ = \
"""float coshf(float p1)
/usr/include/architecture/i386/math.h:293"""
# /usr/include/architecture/i386/math.h 295
sinh = _libraries['cublas'].sinh
sinh.restype = c_double
# sinh(p1)
sinh.argtypes = [c_double]
sinh.__doc__ = \
"""double sinh(double p1)
/usr/include/architecture/i386/math.h:295"""
# /usr/include/architecture/i386/math.h 296
sinhf = _libraries['cublas'].sinhf
sinhf.restype = c_float
# sinhf(p1)
sinhf.argtypes = [c_float]
sinhf.__doc__ = \
"""float sinhf(float p1)
/usr/include/architecture/i386/math.h:296"""
# /usr/include/architecture/i386/math.h 298
tanh = _libraries['cublas'].tanh
tanh.restype = c_double
# tanh(p1)
tanh.argtypes = [c_double]
tanh.__doc__ = \
"""double tanh(double p1)
/usr/include/architecture/i386/math.h:298"""
# /usr/include/architecture/i386/math.h 299
tanhf = _libraries['cublas'].tanhf
tanhf.restype = c_float
# tanhf(p1)
tanhf.argtypes = [c_float]
tanhf.__doc__ = \
"""float tanhf(float p1)
/usr/include/architecture/i386/math.h:299"""
# /usr/include/architecture/i386/math.h 301
exp = _libraries['cublas'].exp
exp.restype = c_double
# exp(p1)
exp.argtypes = [c_double]
exp.__doc__ = \
"""double exp(double p1)
/usr/include/architecture/i386/math.h:301"""
# /usr/include/architecture/i386/math.h 302
expf = _libraries['cublas'].expf
expf.restype = c_float
# expf(p1)
expf.argtypes = [c_float]
expf.__doc__ = \
"""float expf(float p1)
/usr/include/architecture/i386/math.h:302"""
# /usr/include/architecture/i386/math.h 304
exp2 = _libraries['cublas'].exp2
exp2.restype = c_double
# exp2(p1)
exp2.argtypes = [c_double]
exp2.__doc__ = \
"""double exp2(double p1)
/usr/include/architecture/i386/math.h:304"""
# /usr/include/architecture/i386/math.h 305
exp2f = _libraries['cublas'].exp2f
exp2f.restype = c_float
# exp2f(p1)
exp2f.argtypes = [c_float]
exp2f.__doc__ = \
"""float exp2f(float p1)
/usr/include/architecture/i386/math.h:305"""
# /usr/include/architecture/i386/math.h 307
expm1 = _libraries['cublas'].expm1
expm1.restype = c_double
# expm1(p1)
expm1.argtypes = [c_double]
expm1.__doc__ = \
"""double expm1(double p1)
/usr/include/architecture/i386/math.h:307"""
# /usr/include/architecture/i386/math.h 308
expm1f = _libraries['cublas'].expm1f
expm1f.restype = c_float
# expm1f(p1)
expm1f.argtypes = [c_float]
expm1f.__doc__ = \
"""float expm1f(float p1)
/usr/include/architecture/i386/math.h:308"""
# /usr/include/architecture/i386/math.h 310
log = _libraries['cublas'].log
log.restype = c_double
# log(p1)
log.argtypes = [c_double]
log.__doc__ = \
"""double log(double p1)
/usr/include/architecture/i386/math.h:310"""
# /usr/include/architecture/i386/math.h 311
logf = _libraries['cublas'].logf
logf.restype = c_float
# logf(p1)
logf.argtypes = [c_float]
logf.__doc__ = \
"""float logf(float p1)
/usr/include/architecture/i386/math.h:311"""
# /usr/include/architecture/i386/math.h 313
log10 = _libraries['cublas'].log10
log10.restype = c_double
# log10(p1)
log10.argtypes = [c_double]
log10.__doc__ = \
"""double log10(double p1)
/usr/include/architecture/i386/math.h:313"""
# /usr/include/architecture/i386/math.h 314
log10f = _libraries['cublas'].log10f
log10f.restype = c_float
# log10f(p1)
log10f.argtypes = [c_float]
log10f.__doc__ = \
"""float log10f(float p1)
/usr/include/architecture/i386/math.h:314"""
# /usr/include/architecture/i386/math.h 316
log2 = _libraries['cublas'].log2
log2.restype = c_double
# log2(p1)
log2.argtypes = [c_double]
log2.__doc__ = \
"""double log2(double p1)
/usr/include/architecture/i386/math.h:316"""
# /usr/include/architecture/i386/math.h 317
log2f = _libraries['cublas'].log2f
log2f.restype = c_float
# log2f(p1)
log2f.argtypes = [c_float]
log2f.__doc__ = \
"""float log2f(float p1)
/usr/include/architecture/i386/math.h:317"""
# /usr/include/architecture/i386/math.h 319
log1p = _libraries['cublas'].log1p
log1p.restype = c_double
# log1p(p1)
log1p.argtypes = [c_double]
log1p.__doc__ = \
"""double log1p(double p1)
/usr/include/architecture/i386/math.h:319"""
# /usr/include/architecture/i386/math.h 320
log1pf = _libraries['cublas'].log1pf
log1pf.restype = c_float
# log1pf(p1)
log1pf.argtypes = [c_float]
log1pf.__doc__ = \
"""float log1pf(float p1)
/usr/include/architecture/i386/math.h:320"""
# /usr/include/architecture/i386/math.h 322
logb = _libraries['cublas'].logb
logb.restype = c_double
# logb(p1)
logb.argtypes = [c_double]
logb.__doc__ = \
"""double logb(double p1)
/usr/include/architecture/i386/math.h:322"""
# /usr/include/architecture/i386/math.h 323
logbf = _libraries['cublas'].logbf
logbf.restype = c_float
# logbf(p1)
logbf.argtypes = [c_float]
logbf.__doc__ = \
"""float logbf(float p1)
/usr/include/architecture/i386/math.h:323"""
# /usr/include/architecture/i386/math.h 325
modf = _libraries['cublas'].modf
modf.restype = c_double
# modf(p1, p2)
modf.argtypes = [c_double, POINTER(c_double)]
modf.__doc__ = \
"""double modf(double p1, double * p2)
/usr/include/architecture/i386/math.h:325"""
# /usr/include/architecture/i386/math.h 326
modff = _libraries['cublas'].modff
modff.restype = c_float
# modff(p1, p2)
modff.argtypes = [c_float, POINTER(c_float)]
modff.__doc__ = \
"""float modff(float p1, float * p2)
/usr/include/architecture/i386/math.h:326"""
# /usr/include/architecture/i386/math.h 328
ldexp = _libraries['cublas'].ldexp
ldexp.restype = c_double
# ldexp(p1, p2)
ldexp.argtypes = [c_double, c_int]
ldexp.__doc__ = \
"""double ldexp(double p1, int p2)
/usr/include/architecture/i386/math.h:328"""
# /usr/include/architecture/i386/math.h 329
ldexpf = _libraries['cublas'].ldexpf
ldexpf.restype = c_float
# ldexpf(p1, p2)
ldexpf.argtypes = [c_float, c_int]
ldexpf.__doc__ = \
"""float ldexpf(float p1, int p2)
/usr/include/architecture/i386/math.h:329"""
# /usr/include/architecture/i386/math.h 331
frexp = _libraries['cublas'].frexp
frexp.restype = c_double
# frexp(p1, p2)
frexp.argtypes = [c_double, POINTER(c_int)]
frexp.__doc__ = \
"""double frexp(double p1, int * p2)
/usr/include/architecture/i386/math.h:331"""
# /usr/include/architecture/i386/math.h 332
frexpf = _libraries['cublas'].frexpf
frexpf.restype = c_float
# frexpf(p1, p2)
frexpf.argtypes = [c_float, POINTER(c_int)]
frexpf.__doc__ = \
"""float frexpf(float p1, int * p2)
/usr/include/architecture/i386/math.h:332"""
# /usr/include/architecture/i386/math.h 334
ilogb = _libraries['cublas'].ilogb
ilogb.restype = c_int
# ilogb(p1)
ilogb.argtypes = [c_double]
ilogb.__doc__ = \
"""int ilogb(double p1)
/usr/include/architecture/i386/math.h:334"""
# /usr/include/architecture/i386/math.h 335
ilogbf = _libraries['cublas'].ilogbf
ilogbf.restype = c_int
# ilogbf(p1)
ilogbf.argtypes = [c_float]
ilogbf.__doc__ = \
"""int ilogbf(float p1)
/usr/include/architecture/i386/math.h:335"""
# /usr/include/architecture/i386/math.h 337
scalbn = _libraries['cublas'].scalbn
scalbn.restype = c_double
# scalbn(p1, p2)
scalbn.argtypes = [c_double, c_int]
scalbn.__doc__ = \
"""double scalbn(double p1, int p2)
/usr/include/architecture/i386/math.h:337"""
# /usr/include/architecture/i386/math.h 338
scalbnf = _libraries['cublas'].scalbnf
scalbnf.restype = c_float
# scalbnf(p1, p2)
scalbnf.argtypes = [c_float, c_int]
scalbnf.__doc__ = \
"""float scalbnf(float p1, int p2)
/usr/include/architecture/i386/math.h:338"""
# /usr/include/architecture/i386/math.h 340
scalbln = _libraries['cublas'].scalbln
scalbln.restype = c_double
# scalbln(p1, p2)
scalbln.argtypes = [c_double, c_long]
scalbln.__doc__ = \
"""double scalbln(double p1, long int p2)
/usr/include/architecture/i386/math.h:340"""
# /usr/include/architecture/i386/math.h 341
scalblnf = _libraries['cublas'].scalblnf
scalblnf.restype = c_float
# scalblnf(p1, p2)
scalblnf.argtypes = [c_float, c_long]
scalblnf.__doc__ = \
"""float scalblnf(float p1, long int p2)
/usr/include/architecture/i386/math.h:341"""
# /usr/include/architecture/i386/math.h 343
fabs = _libraries['cublas'].fabs
fabs.restype = c_double
# fabs(p1)
fabs.argtypes = [c_double]
fabs.__doc__ = \
"""double fabs(double p1)
/usr/include/architecture/i386/math.h:343"""
# /usr/include/architecture/i386/math.h 344
fabsf = _libraries['cublas'].fabsf
fabsf.restype = c_float
# fabsf(p1)
fabsf.argtypes = [c_float]
fabsf.__doc__ = \
"""float fabsf(float p1)
/usr/include/architecture/i386/math.h:344"""
# /usr/include/architecture/i386/math.h 346
cbrt = _libraries['cublas'].cbrt
cbrt.restype = c_double
# cbrt(p1)
cbrt.argtypes = [c_double]
cbrt.__doc__ = \
"""double cbrt(double p1)
/usr/include/architecture/i386/math.h:346"""
# /usr/include/architecture/i386/math.h 347
cbrtf = _libraries['cublas'].cbrtf
cbrtf.restype = c_float
# cbrtf(p1)
cbrtf.argtypes = [c_float]
cbrtf.__doc__ = \
"""float cbrtf(float p1)
/usr/include/architecture/i386/math.h:347"""
# /usr/include/architecture/i386/math.h 349
hypot = _libraries['cublas'].hypot
hypot.restype = c_double
# hypot(p1, p2)
hypot.argtypes = [c_double, c_double]
hypot.__doc__ = \
"""double hypot(double p1, double p2)
/usr/include/architecture/i386/math.h:349"""
# /usr/include/architecture/i386/math.h 350
hypotf = _libraries['cublas'].hypotf
hypotf.restype = c_float
# hypotf(p1, p2)
hypotf.argtypes = [c_float, c_float]
hypotf.__doc__ = \
"""float hypotf(float p1, float p2)
/usr/include/architecture/i386/math.h:350"""
# /usr/include/architecture/i386/math.h 352
pow = _libraries['cublas'].pow
pow.restype = c_double
# pow(p1, p2)
pow.argtypes = [c_double, c_double]
pow.__doc__ = \
"""double pow(double p1, double p2)
/usr/include/architecture/i386/math.h:352"""
# /usr/include/architecture/i386/math.h 353
powf = _libraries['cublas'].powf
powf.restype = c_float
# powf(p1, p2)
powf.argtypes = [c_float, c_float]
powf.__doc__ = \
"""float powf(float p1, float p2)
/usr/include/architecture/i386/math.h:353"""
# /usr/include/architecture/i386/math.h 355
sqrt = _libraries['cublas'].sqrt
sqrt.restype = c_double
# sqrt(p1)
sqrt.argtypes = [c_double]
sqrt.__doc__ = \
"""double sqrt(double p1)
/usr/include/architecture/i386/math.h:355"""
# /usr/include/architecture/i386/math.h 356
sqrtf = _libraries['cublas'].sqrtf
sqrtf.restype = c_float
# sqrtf(p1)
sqrtf.argtypes = [c_float]
sqrtf.__doc__ = \
"""float sqrtf(float p1)
/usr/include/architecture/i386/math.h:356"""
# /usr/include/architecture/i386/math.h 358
erf = _libraries['cublas'].erf
erf.restype = c_double
# erf(p1)
erf.argtypes = [c_double]
erf.__doc__ = \
"""double erf(double p1)
/usr/include/architecture/i386/math.h:358"""
# /usr/include/architecture/i386/math.h 359
erff = _libraries['cublas'].erff
erff.restype = c_float
# erff(p1)
erff.argtypes = [c_float]
erff.__doc__ = \
"""float erff(float p1)
/usr/include/architecture/i386/math.h:359"""
# /usr/include/architecture/i386/math.h 361
erfc = _libraries['cublas'].erfc
erfc.restype = c_double
# erfc(p1)
erfc.argtypes = [c_double]
erfc.__doc__ = \
"""double erfc(double p1)
/usr/include/architecture/i386/math.h:361"""
# /usr/include/architecture/i386/math.h 362
erfcf = _libraries['cublas'].erfcf
erfcf.restype = c_float
# erfcf(p1)
erfcf.argtypes = [c_float]
erfcf.__doc__ = \
"""float erfcf(float p1)
/usr/include/architecture/i386/math.h:362"""
# /usr/include/architecture/i386/math.h 364
lgamma = _libraries['cublas'].lgamma
lgamma.restype = c_double
# lgamma(p1)
lgamma.argtypes = [c_double]
lgamma.__doc__ = \
"""double lgamma(double p1)
/usr/include/architecture/i386/math.h:364"""
# /usr/include/architecture/i386/math.h 365
lgammaf = _libraries['cublas'].lgammaf
lgammaf.restype = c_float
# lgammaf(p1)
lgammaf.argtypes = [c_float]
lgammaf.__doc__ = \
"""float lgammaf(float p1)
/usr/include/architecture/i386/math.h:365"""
# /usr/include/architecture/i386/math.h 367
tgamma = _libraries['cublas'].tgamma
tgamma.restype = c_double
# tgamma(p1)
tgamma.argtypes = [c_double]
tgamma.__doc__ = \
"""double tgamma(double p1)
/usr/include/architecture/i386/math.h:367"""
# /usr/include/architecture/i386/math.h 368
tgammaf = _libraries['cublas'].tgammaf
tgammaf.restype = c_float
# tgammaf(p1)
tgammaf.argtypes = [c_float]
tgammaf.__doc__ = \
"""float tgammaf(float p1)
/usr/include/architecture/i386/math.h:368"""
# /usr/include/architecture/i386/math.h 370
ceil = _libraries['cublas'].ceil
ceil.restype = c_double
# ceil(p1)
ceil.argtypes = [c_double]
ceil.__doc__ = \
"""double ceil(double p1)
/usr/include/architecture/i386/math.h:370"""
# /usr/include/architecture/i386/math.h 371
ceilf = _libraries['cublas'].ceilf
ceilf.restype = c_float
# ceilf(p1)
ceilf.argtypes = [c_float]
ceilf.__doc__ = \
"""float ceilf(float p1)
/usr/include/architecture/i386/math.h:371"""
# /usr/include/architecture/i386/math.h 373
floor = _libraries['cublas'].floor
floor.restype = c_double
# floor(p1)
floor.argtypes = [c_double]
floor.__doc__ = \
"""double floor(double p1)
/usr/include/architecture/i386/math.h:373"""
# /usr/include/architecture/i386/math.h 374
floorf = _libraries['cublas'].floorf
floorf.restype = c_float
# floorf(p1)
floorf.argtypes = [c_float]
floorf.__doc__ = \
"""float floorf(float p1)
/usr/include/architecture/i386/math.h:374"""
# /usr/include/architecture/i386/math.h 376
nearbyint = _libraries['cublas'].nearbyint
nearbyint.restype = c_double
# nearbyint(p1)
nearbyint.argtypes = [c_double]
nearbyint.__doc__ = \
"""double nearbyint(double p1)
/usr/include/architecture/i386/math.h:376"""
# /usr/include/architecture/i386/math.h 377
nearbyintf = _libraries['cublas'].nearbyintf
nearbyintf.restype = c_float
# nearbyintf(p1)
nearbyintf.argtypes = [c_float]
nearbyintf.__doc__ = \
"""float nearbyintf(float p1)
/usr/include/architecture/i386/math.h:377"""
# /usr/include/architecture/i386/math.h 379
rint = _libraries['cublas'].rint
rint.restype = c_double
# rint(p1)
rint.argtypes = [c_double]
rint.__doc__ = \
"""double rint(double p1)
/usr/include/architecture/i386/math.h:379"""
# /usr/include/architecture/i386/math.h 380
rintf = _libraries['cublas'].rintf
rintf.restype = c_float
# rintf(p1)
rintf.argtypes = [c_float]
rintf.__doc__ = \
"""float rintf(float p1)
/usr/include/architecture/i386/math.h:380"""
# /usr/include/architecture/i386/math.h 382
lrint = _libraries['cublas'].lrint
lrint.restype = c_long
# lrint(p1)
lrint.argtypes = [c_double]
lrint.__doc__ = \
"""long int lrint(double p1)
/usr/include/architecture/i386/math.h:382"""
# /usr/include/architecture/i386/math.h 383
lrintf = _libraries['cublas'].lrintf
lrintf.restype = c_long
# lrintf(p1)
lrintf.argtypes = [c_float]
lrintf.__doc__ = \
"""long int lrintf(float p1)
/usr/include/architecture/i386/math.h:383"""
# /usr/include/architecture/i386/math.h 385
round = _libraries['cublas'].round
round.restype = c_double
# round(p1)
round.argtypes = [c_double]
round.__doc__ = \
"""double round(double p1)
/usr/include/architecture/i386/math.h:385"""
# /usr/include/architecture/i386/math.h 386
roundf = _libraries['cublas'].roundf
roundf.restype = c_float
# roundf(p1)
roundf.argtypes = [c_float]
roundf.__doc__ = \
"""float roundf(float p1)
/usr/include/architecture/i386/math.h:386"""
# /usr/include/architecture/i386/math.h 388
lround = _libraries['cublas'].lround
lround.restype = c_long
# lround(p1)
lround.argtypes = [c_double]
lround.__doc__ = \
"""long int lround(double p1)
/usr/include/architecture/i386/math.h:388"""
# /usr/include/architecture/i386/math.h 389
lroundf = _libraries['cublas'].lroundf
lroundf.restype = c_long
# lroundf(p1)
lroundf.argtypes = [c_float]
lroundf.__doc__ = \
"""long int lroundf(float p1)
/usr/include/architecture/i386/math.h:389"""
# /usr/include/architecture/i386/math.h 394
llrint = _libraries['cublas'].llrint
llrint.restype = c_longlong
# llrint(p1)
llrint.argtypes = [c_double]
llrint.__doc__ = \
"""long long int llrint(double p1)
/usr/include/architecture/i386/math.h:394"""
# /usr/include/architecture/i386/math.h 395
llrintf = _libraries['cublas'].llrintf
llrintf.restype = c_longlong
# llrintf(p1)
llrintf.argtypes = [c_float]
llrintf.__doc__ = \
"""long long int llrintf(float p1)
/usr/include/architecture/i386/math.h:395"""
# /usr/include/architecture/i386/math.h 397
llround = _libraries['cublas'].llround
llround.restype = c_longlong
# llround(p1)
llround.argtypes = [c_double]
llround.__doc__ = \
"""long long int llround(double p1)
/usr/include/architecture/i386/math.h:397"""
# /usr/include/architecture/i386/math.h 398
llroundf = _libraries['cublas'].llroundf
llroundf.restype = c_longlong
# llroundf(p1)
llroundf.argtypes = [c_float]
llroundf.__doc__ = \
"""long long int llroundf(float p1)
/usr/include/architecture/i386/math.h:398"""
# /usr/include/architecture/i386/math.h 402
trunc = _libraries['cublas'].trunc
trunc.restype = c_double
# trunc(p1)
trunc.argtypes = [c_double]
trunc.__doc__ = \
"""double trunc(double p1)
/usr/include/architecture/i386/math.h:402"""
# /usr/include/architecture/i386/math.h 403
truncf = _libraries['cublas'].truncf
truncf.restype = c_float
# truncf(p1)
truncf.argtypes = [c_float]
truncf.__doc__ = \
"""float truncf(float p1)
/usr/include/architecture/i386/math.h:403"""
# /usr/include/architecture/i386/math.h 405
fmod = _libraries['cublas'].fmod
fmod.restype = c_double
# fmod(p1, p2)
fmod.argtypes = [c_double, c_double]
fmod.__doc__ = \
"""double fmod(double p1, double p2)
/usr/include/architecture/i386/math.h:405"""
# /usr/include/architecture/i386/math.h 406
fmodf = _libraries['cublas'].fmodf
fmodf.restype = c_float
# fmodf(p1, p2)
fmodf.argtypes = [c_float, c_float]
fmodf.__doc__ = \
"""float fmodf(float p1, float p2)
/usr/include/architecture/i386/math.h:406"""
# /usr/include/architecture/i386/math.h 408
remainder = _libraries['cublas'].remainder
remainder.restype = c_double
# remainder(p1, p2)
remainder.argtypes = [c_double, c_double]
remainder.__doc__ = \
"""double remainder(double p1, double p2)
/usr/include/architecture/i386/math.h:408"""
# /usr/include/architecture/i386/math.h 409
remainderf = _libraries['cublas'].remainderf
remainderf.restype = c_float
# remainderf(p1, p2)
remainderf.argtypes = [c_float, c_float]
remainderf.__doc__ = \
"""float remainderf(float p1, float p2)
/usr/include/architecture/i386/math.h:409"""
# /usr/include/architecture/i386/math.h 411
remquo = _libraries['cublas'].remquo
remquo.restype = c_double
# remquo(p1, p2, p3)
remquo.argtypes = [c_double, c_double, POINTER(c_int)]
remquo.__doc__ = \
"""double remquo(double p1, double p2, int * p3)
/usr/include/architecture/i386/math.h:411"""
# /usr/include/architecture/i386/math.h 412
remquof = _libraries['cublas'].remquof
remquof.restype = c_float
# remquof(p1, p2, p3)
remquof.argtypes = [c_float, c_float, POINTER(c_int)]
remquof.__doc__ = \
"""float remquof(float p1, float p2, int * p3)
/usr/include/architecture/i386/math.h:412"""
# /usr/include/architecture/i386/math.h 414
copysign = _libraries['cublas'].copysign
copysign.restype = c_double
# copysign(p1, p2)
copysign.argtypes = [c_double, c_double]
copysign.__doc__ = \
"""double copysign(double p1, double p2)
/usr/include/architecture/i386/math.h:414"""
# /usr/include/architecture/i386/math.h 415
copysignf = _libraries['cublas'].copysignf
copysignf.restype = c_float
# copysignf(p1, p2)
copysignf.argtypes = [c_float, c_float]
copysignf.__doc__ = \
"""float copysignf(float p1, float p2)
/usr/include/architecture/i386/math.h:415"""
# /usr/include/architecture/i386/math.h 417
nan = _libraries['cublas'].nan
nan.restype = c_double
# nan(p1)
nan.argtypes = [STRING]
nan.__doc__ = \
"""double nan(unknown * p1)
/usr/include/architecture/i386/math.h:417"""
# /usr/include/architecture/i386/math.h 418
nanf = _libraries['cublas'].nanf
nanf.restype = c_float
# nanf(p1)
nanf.argtypes = [STRING]
nanf.__doc__ = \
"""float nanf(unknown * p1)
/usr/include/architecture/i386/math.h:418"""
# /usr/include/architecture/i386/math.h 420
nextafter = _libraries['cublas'].nextafter
nextafter.restype = c_double
# nextafter(p1, p2)
nextafter.argtypes = [c_double, c_double]
nextafter.__doc__ = \
"""double nextafter(double p1, double p2)
/usr/include/architecture/i386/math.h:420"""
# /usr/include/architecture/i386/math.h 421
nextafterf = _libraries['cublas'].nextafterf
nextafterf.restype = c_float
# nextafterf(p1, p2)
nextafterf.argtypes = [c_float, c_float]
nextafterf.__doc__ = \
"""float nextafterf(float p1, float p2)
/usr/include/architecture/i386/math.h:421"""
# /usr/include/architecture/i386/math.h 423
fdim = _libraries['cublas'].fdim
fdim.restype = c_double
# fdim(p1, p2)
fdim.argtypes = [c_double, c_double]
fdim.__doc__ = \
"""double fdim(double p1, double p2)
/usr/include/architecture/i386/math.h:423"""
# /usr/include/architecture/i386/math.h 424
fdimf = _libraries['cublas'].fdimf
fdimf.restype = c_float
# fdimf(p1, p2)
fdimf.argtypes = [c_float, c_float]
fdimf.__doc__ = \
"""float fdimf(float p1, float p2)
/usr/include/architecture/i386/math.h:424"""
# /usr/include/architecture/i386/math.h 426
fmax = _libraries['cublas'].fmax
fmax.restype = c_double
# fmax(p1, p2)
fmax.argtypes = [c_double, c_double]
fmax.__doc__ = \
"""double fmax(double p1, double p2)
/usr/include/architecture/i386/math.h:426"""
# /usr/include/architecture/i386/math.h 427
fmaxf = _libraries['cublas'].fmaxf
fmaxf.restype = c_float
# fmaxf(p1, p2)
fmaxf.argtypes = [c_float, c_float]
fmaxf.__doc__ = \
"""float fmaxf(float p1, float p2)
/usr/include/architecture/i386/math.h:427"""
# /usr/include/architecture/i386/math.h 429
fmin = _libraries['cublas'].fmin
fmin.restype = c_double
# fmin(p1, p2)
fmin.argtypes = [c_double, c_double]
fmin.__doc__ = \
"""double fmin(double p1, double p2)
/usr/include/architecture/i386/math.h:429"""
# /usr/include/architecture/i386/math.h 430
fminf = _libraries['cublas'].fminf
fminf.restype = c_float
# fminf(p1, p2)
fminf.argtypes = [c_float, c_float]
fminf.__doc__ = \
"""float fminf(float p1, float p2)
/usr/include/architecture/i386/math.h:430"""
# /usr/include/architecture/i386/math.h 432
fma = _libraries['cublas'].fma
fma.restype = c_double
# fma(p1, p2, p3)
fma.argtypes = [c_double, c_double, c_double]
fma.__doc__ = \
"""double fma(double p1, double p2, double p3)
/usr/include/architecture/i386/math.h:432"""
# /usr/include/architecture/i386/math.h 433
fmaf = _libraries['cublas'].fmaf
fmaf.restype = c_float
# fmaf(p1, p2, p3)
fmaf.argtypes = [c_float, c_float, c_float]
fmaf.__doc__ = \
"""float fmaf(float p1, float p2, float p3)
/usr/include/architecture/i386/math.h:433"""
# /usr/include/architecture/i386/math.h 435
acosl = _libraries['cublas'].acosl
acosl.restype = c_longdouble
# acosl(p1)
acosl.argtypes = [c_longdouble]
acosl.__doc__ = \
"""long double acosl(long double p1)
/usr/include/architecture/i386/math.h:435"""
# /usr/include/architecture/i386/math.h 436
asinl = _libraries['cublas'].asinl
asinl.restype = c_longdouble
# asinl(p1)
asinl.argtypes = [c_longdouble]
asinl.__doc__ = \
"""long double asinl(long double p1)
/usr/include/architecture/i386/math.h:436"""
# /usr/include/architecture/i386/math.h 437
atanl = _libraries['cublas'].atanl
atanl.restype = c_longdouble
# atanl(p1)
atanl.argtypes = [c_longdouble]
atanl.__doc__ = \
"""long double atanl(long double p1)
/usr/include/architecture/i386/math.h:437"""
# /usr/include/architecture/i386/math.h 438
atan2l = _libraries['cublas'].atan2l
atan2l.restype = c_longdouble
# atan2l(p1, p2)
atan2l.argtypes = [c_longdouble, c_longdouble]
atan2l.__doc__ = \
"""long double atan2l(long double p1, long double p2)
/usr/include/architecture/i386/math.h:438"""
# /usr/include/architecture/i386/math.h 439
cosl = _libraries['cublas'].cosl
cosl.restype = c_longdouble
# cosl(p1)
cosl.argtypes = [c_longdouble]
cosl.__doc__ = \
"""long double cosl(long double p1)
/usr/include/architecture/i386/math.h:439"""
# /usr/include/architecture/i386/math.h 440
sinl = _libraries['cublas'].sinl
sinl.restype = c_longdouble
# sinl(p1)
sinl.argtypes = [c_longdouble]
sinl.__doc__ = \
"""long double sinl(long double p1)
/usr/include/architecture/i386/math.h:440"""
# /usr/include/architecture/i386/math.h 441
tanl = _libraries['cublas'].tanl
tanl.restype = c_longdouble
# tanl(p1)
tanl.argtypes = [c_longdouble]
tanl.__doc__ = \
"""long double tanl(long double p1)
/usr/include/architecture/i386/math.h:441"""
# /usr/include/architecture/i386/math.h 442
acoshl = _libraries['cublas'].acoshl
acoshl.restype = c_longdouble
# acoshl(p1)
acoshl.argtypes = [c_longdouble]
acoshl.__doc__ = \
"""long double acoshl(long double p1)
/usr/include/architecture/i386/math.h:442"""
# /usr/include/architecture/i386/math.h 443
asinhl = _libraries['cublas'].asinhl
asinhl.restype = c_longdouble
# asinhl(p1)
asinhl.argtypes = [c_longdouble]
asinhl.__doc__ = \
"""long double asinhl(long double p1)
/usr/include/architecture/i386/math.h:443"""
# /usr/include/architecture/i386/math.h 444
atanhl = _libraries['cublas'].atanhl
atanhl.restype = c_longdouble
# atanhl(p1)
atanhl.argtypes = [c_longdouble]
atanhl.__doc__ = \
"""long double atanhl(long double p1)
/usr/include/architecture/i386/math.h:444"""
# /usr/include/architecture/i386/math.h 445
coshl = _libraries['cublas'].coshl
coshl.restype = c_longdouble
# coshl(p1)
coshl.argtypes = [c_longdouble]
coshl.__doc__ = \
"""long double coshl(long double p1)
/usr/include/architecture/i386/math.h:445"""
# /usr/include/architecture/i386/math.h 446
sinhl = _libraries['cublas'].sinhl
sinhl.restype = c_longdouble
# sinhl(p1)
sinhl.argtypes = [c_longdouble]
sinhl.__doc__ = \
"""long double sinhl(long double p1)
/usr/include/architecture/i386/math.h:446"""
# /usr/include/architecture/i386/math.h 447
tanhl = _libraries['cublas'].tanhl
tanhl.restype = c_longdouble
# tanhl(p1)
tanhl.argtypes = [c_longdouble]
tanhl.__doc__ = \
"""long double tanhl(long double p1)
/usr/include/architecture/i386/math.h:447"""
# /usr/include/architecture/i386/math.h 448
expl = _libraries['cublas'].expl
expl.restype = c_longdouble
# expl(p1)
expl.argtypes = [c_longdouble]
expl.__doc__ = \
"""long double expl(long double p1)
/usr/include/architecture/i386/math.h:448"""
# /usr/include/architecture/i386/math.h 449
exp2l = _libraries['cublas'].exp2l
exp2l.restype = c_longdouble
# exp2l(p1)
exp2l.argtypes = [c_longdouble]
exp2l.__doc__ = \
"""long double exp2l(long double p1)
/usr/include/architecture/i386/math.h:449"""
# /usr/include/architecture/i386/math.h 450
expm1l = _libraries['cublas'].expm1l
expm1l.restype = c_longdouble
# expm1l(p1)
expm1l.argtypes = [c_longdouble]
expm1l.__doc__ = \
"""long double expm1l(long double p1)
/usr/include/architecture/i386/math.h:450"""
# /usr/include/architecture/i386/math.h 451
logl = _libraries['cublas'].logl
logl.restype = c_longdouble
# logl(p1)
logl.argtypes = [c_longdouble]
logl.__doc__ = \
"""long double logl(long double p1)
/usr/include/architecture/i386/math.h:451"""
# /usr/include/architecture/i386/math.h 452
log10l = _libraries['cublas'].log10l
log10l.restype = c_longdouble
# log10l(p1)
log10l.argtypes = [c_longdouble]
log10l.__doc__ = \
"""long double log10l(long double p1)
/usr/include/architecture/i386/math.h:452"""
# /usr/include/architecture/i386/math.h 453
log2l = _libraries['cublas'].log2l
log2l.restype = c_longdouble
# log2l(p1)
log2l.argtypes = [c_longdouble]
log2l.__doc__ = \
"""long double log2l(long double p1)
/usr/include/architecture/i386/math.h:453"""
# /usr/include/architecture/i386/math.h 454
log1pl = _libraries['cublas'].log1pl
log1pl.restype = c_longdouble
# log1pl(p1)
log1pl.argtypes = [c_longdouble]
log1pl.__doc__ = \
"""long double log1pl(long double p1)
/usr/include/architecture/i386/math.h:454"""
# /usr/include/architecture/i386/math.h 455
logbl = _libraries['cublas'].logbl
logbl.restype = c_longdouble
# logbl(p1)
logbl.argtypes = [c_longdouble]
logbl.__doc__ = \
"""long double logbl(long double p1)
/usr/include/architecture/i386/math.h:455"""
# /usr/include/architecture/i386/math.h 456
modfl = _libraries['cublas'].modfl
modfl.restype = c_longdouble
# modfl(p1, p2)
modfl.argtypes = [c_longdouble, POINTER(c_longdouble)]
modfl.__doc__ = \
"""long double modfl(long double p1, long double * p2)
/usr/include/architecture/i386/math.h:456"""
# /usr/include/architecture/i386/math.h 457
ldexpl = _libraries['cublas'].ldexpl
ldexpl.restype = c_longdouble
# ldexpl(p1, p2)
ldexpl.argtypes = [c_longdouble, c_int]
ldexpl.__doc__ = \
"""long double ldexpl(long double p1, int p2)
/usr/include/architecture/i386/math.h:457"""
# /usr/include/architecture/i386/math.h 458
frexpl = _libraries['cublas'].frexpl
frexpl.restype = c_longdouble
# frexpl(p1, p2)
frexpl.argtypes = [c_longdouble, POINTER(c_int)]
frexpl.__doc__ = \
"""long double frexpl(long double p1, int * p2)
/usr/include/architecture/i386/math.h:458"""
# /usr/include/architecture/i386/math.h 459
ilogbl = _libraries['cublas'].ilogbl
ilogbl.restype = c_int
# ilogbl(p1)
ilogbl.argtypes = [c_longdouble]
ilogbl.__doc__ = \
"""int ilogbl(long double p1)
/usr/include/architecture/i386/math.h:459"""
# /usr/include/architecture/i386/math.h 460
scalbnl = _libraries['cublas'].scalbnl
scalbnl.restype = c_longdouble
# scalbnl(p1, p2)
scalbnl.argtypes = [c_longdouble, c_int]
scalbnl.__doc__ = \
"""long double scalbnl(long double p1, int p2)
/usr/include/architecture/i386/math.h:460"""
# /usr/include/architecture/i386/math.h 461
scalblnl = _libraries['cublas'].scalblnl
scalblnl.restype = c_longdouble
# scalblnl(p1, p2)
scalblnl.argtypes = [c_longdouble, c_long]
scalblnl.__doc__ = \
"""long double scalblnl(long double p1, long int p2)
/usr/include/architecture/i386/math.h:461"""
# /usr/include/architecture/i386/math.h 462
fabsl = _libraries['cublas'].fabsl
fabsl.restype = c_longdouble
# fabsl(p1)
fabsl.argtypes = [c_longdouble]
fabsl.__doc__ = \
"""long double fabsl(long double p1)
/usr/include/architecture/i386/math.h:462"""
# /usr/include/architecture/i386/math.h 463
cbrtl = _libraries['cublas'].cbrtl
cbrtl.restype = c_longdouble
# cbrtl(p1)
cbrtl.argtypes = [c_longdouble]
cbrtl.__doc__ = \
"""long double cbrtl(long double p1)
/usr/include/architecture/i386/math.h:463"""
# /usr/include/architecture/i386/math.h 464
hypotl = _libraries['cublas'].hypotl
hypotl.restype = c_longdouble
# hypotl(p1, p2)
hypotl.argtypes = [c_longdouble, c_longdouble]
hypotl.__doc__ = \
"""long double hypotl(long double p1, long double p2)
/usr/include/architecture/i386/math.h:464"""
# /usr/include/architecture/i386/math.h 465
powl = _libraries['cublas'].powl
powl.restype = c_longdouble
# powl(p1, p2)
powl.argtypes = [c_longdouble, c_longdouble]
powl.__doc__ = \
"""long double powl(long double p1, long double p2)
/usr/include/architecture/i386/math.h:465"""
# /usr/include/architecture/i386/math.h 466
sqrtl = _libraries['cublas'].sqrtl
sqrtl.restype = c_longdouble
# sqrtl(p1)
sqrtl.argtypes = [c_longdouble]
sqrtl.__doc__ = \
"""long double sqrtl(long double p1)
/usr/include/architecture/i386/math.h:466"""
# /usr/include/architecture/i386/math.h 467
erfl = _libraries['cublas'].erfl
erfl.restype = c_longdouble
# erfl(p1)
erfl.argtypes = [c_longdouble]
erfl.__doc__ = \
"""long double erfl(long double p1)
/usr/include/architecture/i386/math.h:467"""
# /usr/include/architecture/i386/math.h 468
erfcl = _libraries['cublas'].erfcl
erfcl.restype = c_longdouble
# erfcl(p1)
erfcl.argtypes = [c_longdouble]
erfcl.__doc__ = \
"""long double erfcl(long double p1)
/usr/include/architecture/i386/math.h:468"""
# /usr/include/architecture/i386/math.h 469
lgammal = _libraries['cublas'].lgammal
lgammal.restype = c_longdouble
# lgammal(p1)
lgammal.argtypes = [c_longdouble]
lgammal.__doc__ = \
"""long double lgammal(long double p1)
/usr/include/architecture/i386/math.h:469"""
# /usr/include/architecture/i386/math.h 470
tgammal = _libraries['cublas'].tgammal
tgammal.restype = c_longdouble
# tgammal(p1)
tgammal.argtypes = [c_longdouble]
tgammal.__doc__ = \
"""long double tgammal(long double p1)
/usr/include/architecture/i386/math.h:470"""
# /usr/include/architecture/i386/math.h 471
ceill = _libraries['cublas'].ceill
ceill.restype = c_longdouble
# ceill(p1)
ceill.argtypes = [c_longdouble]
ceill.__doc__ = \
"""long double ceill(long double p1)
/usr/include/architecture/i386/math.h:471"""
# /usr/include/architecture/i386/math.h 472
floorl = _libraries['cublas'].floorl
floorl.restype = c_longdouble
# floorl(p1)
floorl.argtypes = [c_longdouble]
floorl.__doc__ = \
"""long double floorl(long double p1)
/usr/include/architecture/i386/math.h:472"""
# /usr/include/architecture/i386/math.h 473
nearbyintl = _libraries['cublas'].nearbyintl
nearbyintl.restype = c_longdouble
# nearbyintl(p1)
nearbyintl.argtypes = [c_longdouble]
nearbyintl.__doc__ = \
"""long double nearbyintl(long double p1)
/usr/include/architecture/i386/math.h:473"""
# /usr/include/architecture/i386/math.h 474
rintl = _libraries['cublas'].rintl
rintl.restype = c_longdouble
# rintl(p1)
rintl.argtypes = [c_longdouble]
rintl.__doc__ = \
"""long double rintl(long double p1)
/usr/include/architecture/i386/math.h:474"""
# /usr/include/architecture/i386/math.h 475
lrintl = _libraries['cublas'].lrintl
lrintl.restype = c_long
# lrintl(p1)
lrintl.argtypes = [c_longdouble]
lrintl.__doc__ = \
"""long int lrintl(long double p1)
/usr/include/architecture/i386/math.h:475"""
# /usr/include/architecture/i386/math.h 476
roundl = _libraries['cublas'].roundl
roundl.restype = c_longdouble
# roundl(p1)
roundl.argtypes = [c_longdouble]
roundl.__doc__ = \
"""long double roundl(long double p1)
/usr/include/architecture/i386/math.h:476"""
# /usr/include/architecture/i386/math.h 477
lroundl = _libraries['cublas'].lroundl
lroundl.restype = c_long
# lroundl(p1)
lroundl.argtypes = [c_longdouble]
lroundl.__doc__ = \
"""long int lroundl(long double p1)
/usr/include/architecture/i386/math.h:477"""
# /usr/include/architecture/i386/math.h 481
llrintl = _libraries['cublas'].llrintl
llrintl.restype = c_longlong
# llrintl(p1)
llrintl.argtypes = [c_longdouble]
llrintl.__doc__ = \
"""long long int llrintl(long double p1)
/usr/include/architecture/i386/math.h:481"""
# /usr/include/architecture/i386/math.h 482
llroundl = _libraries['cublas'].llroundl
llroundl.restype = c_longlong
# llroundl(p1)
llroundl.argtypes = [c_longdouble]
llroundl.__doc__ = \
"""long long int llroundl(long double p1)
/usr/include/architecture/i386/math.h:482"""
# /usr/include/architecture/i386/math.h 485
truncl = _libraries['cublas'].truncl
truncl.restype = c_longdouble
# truncl(p1)
truncl.argtypes = [c_longdouble]
truncl.__doc__ = \
"""long double truncl(long double p1)
/usr/include/architecture/i386/math.h:485"""
# /usr/include/architecture/i386/math.h 486
fmodl = _libraries['cublas'].fmodl
fmodl.restype = c_longdouble
# fmodl(p1, p2)
fmodl.argtypes = [c_longdouble, c_longdouble]
fmodl.__doc__ = \
"""long double fmodl(long double p1, long double p2)
/usr/include/architecture/i386/math.h:486"""
# /usr/include/architecture/i386/math.h 487
remainderl = _libraries['cublas'].remainderl
remainderl.restype = c_longdouble
# remainderl(p1, p2)
remainderl.argtypes = [c_longdouble, c_longdouble]
remainderl.__doc__ = \
"""long double remainderl(long double p1, long double p2)
/usr/include/architecture/i386/math.h:487"""
# /usr/include/architecture/i386/math.h 488
remquol = _libraries['cublas'].remquol
remquol.restype = c_longdouble
# remquol(p1, p2, p3)
remquol.argtypes = [c_longdouble, c_longdouble, POINTER(c_int)]
remquol.__doc__ = \
"""long double remquol(long double p1, long double p2, int * p3)
/usr/include/architecture/i386/math.h:488"""
# /usr/include/architecture/i386/math.h 489
copysignl = _libraries['cublas'].copysignl
copysignl.restype = c_longdouble
# copysignl(p1, p2)
copysignl.argtypes = [c_longdouble, c_longdouble]
copysignl.__doc__ = \
"""long double copysignl(long double p1, long double p2)
/usr/include/architecture/i386/math.h:489"""
# /usr/include/architecture/i386/math.h 490
nanl = _libraries['cublas'].nanl
nanl.restype = c_longdouble
# nanl(p1)
nanl.argtypes = [STRING]
nanl.__doc__ = \
"""long double nanl(unknown * p1)
/usr/include/architecture/i386/math.h:490"""
# /usr/include/architecture/i386/math.h 491
nextafterl = _libraries['cublas'].nextafterl
nextafterl.restype = c_longdouble
# nextafterl(p1, p2)
nextafterl.argtypes = [c_longdouble, c_longdouble]
nextafterl.__doc__ = \
"""long double nextafterl(long double p1, long double p2)
/usr/include/architecture/i386/math.h:491"""
# /usr/include/architecture/i386/math.h 492
nexttoward = _libraries['cublas'].nexttoward
nexttoward.restype = c_double
# nexttoward(p1, p2)
nexttoward.argtypes = [c_double, c_longdouble]
nexttoward.__doc__ = \
"""double nexttoward(double p1, long double p2)
/usr/include/architecture/i386/math.h:492"""
# /usr/include/architecture/i386/math.h 493
nexttowardf = _libraries['cublas'].nexttowardf
nexttowardf.restype = c_float
# nexttowardf(p1, p2)
nexttowardf.argtypes = [c_float, c_longdouble]
nexttowardf.__doc__ = \
"""float nexttowardf(float p1, long double p2)
/usr/include/architecture/i386/math.h:493"""
# /usr/include/architecture/i386/math.h 494
nexttowardl = _libraries['cublas'].nexttowardl
nexttowardl.restype = c_longdouble
# nexttowardl(p1, p2)
nexttowardl.argtypes = [c_longdouble, c_longdouble]
nexttowardl.__doc__ = \
"""long double nexttowardl(long double p1, long double p2)
/usr/include/architecture/i386/math.h:494"""
# /usr/include/architecture/i386/math.h 495
fdiml = _libraries['cublas'].fdiml
fdiml.restype = c_longdouble
# fdiml(p1, p2)
fdiml.argtypes = [c_longdouble, c_longdouble]
fdiml.__doc__ = \
"""long double fdiml(long double p1, long double p2)
/usr/include/architecture/i386/math.h:495"""
# /usr/include/architecture/i386/math.h 496
fmaxl = _libraries['cublas'].fmaxl
fmaxl.restype = c_longdouble
# fmaxl(p1, p2)
fmaxl.argtypes = [c_longdouble, c_longdouble]
fmaxl.__doc__ = \
"""long double fmaxl(long double p1, long double p2)
/usr/include/architecture/i386/math.h:496"""
# /usr/include/architecture/i386/math.h 497
fminl = _libraries['cublas'].fminl
fminl.restype = c_longdouble
# fminl(p1, p2)
fminl.argtypes = [c_longdouble, c_longdouble]
fminl.__doc__ = \
"""long double fminl(long double p1, long double p2)
/usr/include/architecture/i386/math.h:497"""
# /usr/include/architecture/i386/math.h 498
fmal = _libraries['cublas'].fmal
fmal.restype = c_longdouble
# fmal(p1, p2, p3)
fmal.argtypes = [c_longdouble, c_longdouble, c_longdouble]
fmal.__doc__ = \
"""long double fmal(long double p1, long double p2, long double p3)
/usr/include/architecture/i386/math.h:498"""
# /usr/include/architecture/i386/math.h 507
__inf = _libraries['cublas'].__inf
__inf.restype = c_double
# __inf()
__inf.argtypes = []
__inf.__doc__ = \
"""double __inf()
/usr/include/architecture/i386/math.h:507"""
# /usr/include/architecture/i386/math.h 508
__inff = _libraries['cublas'].__inff
__inff.restype = c_float
# __inff()
__inff.argtypes = []
__inff.__doc__ = \
"""float __inff()
/usr/include/architecture/i386/math.h:508"""
# /usr/include/architecture/i386/math.h 510
__nan = _libraries['cublas'].__nan
__nan.restype = c_float
# __nan()
__nan.argtypes = []
__nan.__doc__ = \
"""float __nan()
/usr/include/architecture/i386/math.h:510"""
# /usr/include/architecture/i386/math.h 513
j0 = _libraries['cublas'].j0
j0.restype = c_double
# j0(p1)
j0.argtypes = [c_double]
j0.__doc__ = \
"""double j0(double p1)
/usr/include/architecture/i386/math.h:513"""
# /usr/include/architecture/i386/math.h 515
j1 = _libraries['cublas'].j1
j1.restype = c_double
# j1(p1)
j1.argtypes = [c_double]
j1.__doc__ = \
"""double j1(double p1)
/usr/include/architecture/i386/math.h:515"""
# /usr/include/architecture/i386/math.h 517
jn = _libraries['cublas'].jn
jn.restype = c_double
# jn(p1, p2)
jn.argtypes = [c_int, c_double]
jn.__doc__ = \
"""double jn(int p1, double p2)
/usr/include/architecture/i386/math.h:517"""
# /usr/include/architecture/i386/math.h 519
y0 = _libraries['cublas'].y0
y0.restype = c_double
# y0(p1)
y0.argtypes = [c_double]
y0.__doc__ = \
"""double y0(double p1)
/usr/include/architecture/i386/math.h:519"""
# /usr/include/architecture/i386/math.h 521
y1 = _libraries['cublas'].y1
y1.restype = c_double
# y1(p1)
y1.argtypes = [c_double]
y1.__doc__ = \
"""double y1(double p1)
/usr/include/architecture/i386/math.h:521"""
# /usr/include/architecture/i386/math.h 523
yn = _libraries['cublas'].yn
yn.restype = c_double
# yn(p1, p2)
yn.argtypes = [c_int, c_double]
yn.__doc__ = \
"""double yn(int p1, double p2)
/usr/include/architecture/i386/math.h:523"""
# /usr/include/architecture/i386/math.h 525
scalb = _libraries['cublas'].scalb
scalb.restype = c_double
# scalb(p1, p2)
scalb.argtypes = [c_double, c_double]
scalb.__doc__ = \
"""double scalb(double p1, double p2)
/usr/include/architecture/i386/math.h:525"""
signgam = (c_int).in_dll(_libraries['cublas'], 'signgam')
# /usr/include/architecture/i386/math.h 557
rinttol = _libraries['cublas'].rinttol
rinttol.restype = c_long
# rinttol(p1)
rinttol.argtypes = [c_double]
rinttol.__doc__ = \
"""long int rinttol(double p1)
/usr/include/architecture/i386/math.h:557"""
# /usr/include/architecture/i386/math.h 559
roundtol = _libraries['cublas'].roundtol
roundtol.restype = c_long
# roundtol(p1)
roundtol.argtypes = [c_double]
roundtol.__doc__ = \
"""long int roundtol(double p1)
/usr/include/architecture/i386/math.h:559"""
# /usr/include/architecture/i386/math.h 597
finite = _libraries['cublas'].finite
finite.restype = c_int
# finite(p1)
finite.argtypes = [c_double]
finite.__doc__ = \
"""int finite(double p1)
/usr/include/architecture/i386/math.h:597"""
# /usr/include/architecture/i386/math.h 599
gamma = _libraries['cublas'].gamma
gamma.restype = c_double
# gamma(p1)
gamma.argtypes = [c_double]
gamma.__doc__ = \
"""double gamma(double p1)
/usr/include/architecture/i386/math.h:599"""
# /usr/include/architecture/i386/math.h 610
significand = _libraries['cublas'].significand
significand.restype = c_double
# significand(p1)
significand.argtypes = [c_double]
significand.__doc__ = \
"""double significand(double p1)
/usr/include/architecture/i386/math.h:610"""
# /usr/include/architecture/i386/math.h 615
drem = _libraries['cublas'].drem
drem.restype = c_double
# drem(p1, p2)
drem.argtypes = [c_double, c_double]
drem.__doc__ = \
"""double drem(double p1, double p2)
/usr/include/architecture/i386/math.h:615"""
# /usr/local/cuda/include/vector_types.h 269
class float2(Structure):
    pass
cuFloatComplex = float2
# /usr/local/cuda/include/vector_types.h 293
class double2(Structure):
    pass
cuDoubleComplex = double2
cuComplex = cuFloatComplex
cublasStatus = c_uint
# /usr/local/cuda/include/cublas.h 120
cublasInit = _libraries['cublas'].cublasInit
cublasInit.restype = cublasStatus
# cublasInit()
cublasInit.argtypes = []
cublasInit.__doc__ = \
"""cublasStatus cublasInit()
/usr/local/cuda/include/cublas.h:120"""
# /usr/local/cuda/include/cublas.h 134
cublasShutdown = _libraries['cublas'].cublasShutdown
cublasShutdown.restype = cublasStatus
# cublasShutdown()
cublasShutdown.argtypes = []
cublasShutdown.__doc__ = \
"""cublasStatus cublasShutdown()
/usr/local/cuda/include/cublas.h:134"""
# /usr/local/cuda/include/cublas.h 148
cublasGetError = _libraries['cublas'].cublasGetError
cublasGetError.restype = cublasStatus
# cublasGetError()
cublasGetError.argtypes = []
cublasGetError.__doc__ = \
"""cublasStatus cublasGetError()
/usr/local/cuda/include/cublas.h:148"""
# /usr/local/cuda/include/cublas.h 168
cublasAlloc = _libraries['cublas'].cublasAlloc
cublasAlloc.restype = cublasStatus
# cublasAlloc(n, elemSize, devicePtr)
cublasAlloc.argtypes = [c_int, c_int, POINTER(c_void_p)]
cublasAlloc.__doc__ = \
"""cublasStatus cublasAlloc(int n, int elemSize, void * * devicePtr)
/usr/local/cuda/include/cublas.h:168"""
# /usr/local/cuda/include/cublas.h 182
cublasFree = _libraries['cublas'].cublasFree
cublasFree.restype = cublasStatus
# cublasFree(devicePtr)
cublasFree.argtypes = [c_void_p]
cublasFree.__doc__ = \
"""cublasStatus cublasFree(unknown * devicePtr)
/usr/local/cuda/include/cublas.h:182"""
# /usr/local/cuda/include/cublas.h 208
cublasSetVector = _libraries['cublas'].cublasSetVector
cublasSetVector.restype = cublasStatus
# cublasSetVector(n, elemSize, x, incx, devicePtr, incy)
cublasSetVector.argtypes = [c_int, c_int, c_void_p, c_int, c_void_p, c_int]
cublasSetVector.__doc__ = \
"""cublasStatus cublasSetVector(int n, int elemSize, unknown * x, int incx, void * devicePtr, int incy)
/usr/local/cuda/include/cublas.h:208"""
# /usr/local/cuda/include/cublas.h 234
cublasGetVector = _libraries['cublas'].cublasGetVector
cublasGetVector.restype = cublasStatus
# cublasGetVector(n, elemSize, x, incx, y, incy)
cublasGetVector.argtypes = [c_int, c_int, c_void_p, c_int, c_void_p, c_int]
cublasGetVector.__doc__ = \
"""cublasStatus cublasGetVector(int n, int elemSize, unknown * x, int incx, void * y, int incy)
/usr/local/cuda/include/cublas.h:234"""
# /usr/local/cuda/include/cublas.h 259
cublasSetMatrix = _libraries['cublas'].cublasSetMatrix
cublasSetMatrix.restype = cublasStatus
# cublasSetMatrix(rows, cols, elemSize, A, lda, B, ldb)
cublasSetMatrix.argtypes = [c_int, c_int, c_int, c_void_p, c_int, c_void_p, c_int]
cublasSetMatrix.__doc__ = \
"""cublasStatus cublasSetMatrix(int rows, int cols, int elemSize, unknown * A, int lda, void * B, int ldb)
/usr/local/cuda/include/cublas.h:259"""
# /usr/local/cuda/include/cublas.h 283
cublasGetMatrix = _libraries['cublas'].cublasGetMatrix
cublasGetMatrix.restype = cublasStatus
# cublasGetMatrix(rows, cols, elemSize, A, lda, B, ldb)
cublasGetMatrix.argtypes = [c_int, c_int, c_int, c_void_p, c_int, c_void_p, c_int]
cublasGetMatrix.__doc__ = \
"""cublasStatus cublasGetMatrix(int rows, int cols, int elemSize, unknown * A, int lda, void * B, int ldb)
/usr/local/cuda/include/cublas.h:283"""
# /usr/local/cuda/include/cublas.h 315
cublasIsamax = _libraries['cublas'].cublasIsamax
cublasIsamax.restype = c_int
# cublasIsamax(n, x, incx)
cublasIsamax.argtypes = [c_int, POINTER(c_float), c_int]
cublasIsamax.__doc__ = \
"""int cublasIsamax(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:315"""
# /usr/local/cuda/include/cublas.h 344
cublasIsamin = _libraries['cublas'].cublasIsamin
cublasIsamin.restype = c_int
# cublasIsamin(n, x, incx)
cublasIsamin.argtypes = [c_int, POINTER(c_float), c_int]
cublasIsamin.__doc__ = \
"""int cublasIsamin(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:344"""
# /usr/local/cuda/include/cublas.h 374
cublasSasum = _libraries['cublas'].cublasSasum
cublasSasum.restype = c_float
# cublasSasum(n, x, incx)
cublasSasum.argtypes = [c_int, POINTER(c_float), c_int]
cublasSasum.__doc__ = \
"""float cublasSasum(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:374"""
# /usr/local/cuda/include/cublas.h 411
cublasSaxpy = _libraries['cublas'].cublasSaxpy
cublasSaxpy.restype = None
# cublasSaxpy(n, alpha, x, incx, y, incy)
cublasSaxpy.argtypes = [c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasSaxpy.__doc__ = \
"""void cublasSaxpy(int n, float alpha, unknown * x, int incx, float * y, int incy)
/usr/local/cuda/include/cublas.h:411"""
# /usr/local/cuda/include/cublas.h 444
cublasScopy = _libraries['cublas'].cublasScopy
cublasScopy.restype = None
# cublasScopy(n, x, incx, y, incy)
cublasScopy.argtypes = [c_int, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasScopy.__doc__ = \
"""void cublasScopy(int n, unknown * x, int incx, float * y, int incy)
/usr/local/cuda/include/cublas.h:444"""
# /usr/local/cuda/include/cublas.h 478
cublasSdot = _libraries['cublas'].cublasSdot
cublasSdot.restype = c_float
# cublasSdot(n, x, incx, y, incy)
cublasSdot.argtypes = [c_int, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasSdot.__doc__ = \
"""float cublasSdot(int n, unknown * x, int incx, unknown * y, int incy)
/usr/local/cuda/include/cublas.h:478"""
# /usr/local/cuda/include/cublas.h 508
cublasSnrm2 = _libraries['cublas'].cublasSnrm2
cublasSnrm2.restype = c_float
# cublasSnrm2(n, x, incx)
cublasSnrm2.argtypes = [c_int, POINTER(c_float), c_int]
cublasSnrm2.__doc__ = \
"""float cublasSnrm2(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:508"""
# /usr/local/cuda/include/cublas.h 547
cublasSrot = _libraries['cublas'].cublasSrot
cublasSrot.restype = None
# cublasSrot(n, x, incx, y, incy, sc, ss)
cublasSrot.argtypes = [c_int, POINTER(c_float), c_int, POINTER(c_float), c_int, c_float, c_float]
cublasSrot.__doc__ = \
"""void cublasSrot(int n, float * x, int incx, float * y, int incy, float sc, float ss)
/usr/local/cuda/include/cublas.h:547"""
# /usr/local/cuda/include/cublas.h 588
cublasSrotg = _libraries['cublas'].cublasSrotg
cublasSrotg.restype = None
# cublasSrotg(sa, sb, sc, ss)
cublasSrotg.argtypes = [POINTER(c_float), POINTER(c_float), POINTER(c_float), POINTER(c_float)]
cublasSrotg.__doc__ = \
"""void cublasSrotg(float * sa, float * sb, float * sc, float * ss)
/usr/local/cuda/include/cublas.h:588"""
# /usr/local/cuda/include/cublas.h 637
cublasSrotm = _libraries['cublas'].cublasSrotm
cublasSrotm.restype = None
# cublasSrotm(n, x, incx, y, incy, sparam)
cublasSrotm.argtypes = [c_int, POINTER(c_float), c_int, POINTER(c_float), c_int, POINTER(c_float)]
cublasSrotm.__doc__ = \
"""void cublasSrotm(int n, float * x, int incx, float * y, int incy, unknown * sparam)
/usr/local/cuda/include/cublas.h:637"""
# /usr/local/cuda/include/cublas.h 680
cublasSrotmg = _libraries['cublas'].cublasSrotmg
cublasSrotmg.restype = None
# cublasSrotmg(sd1, sd2, sx1, sy1, sparam)
cublasSrotmg.argtypes = [POINTER(c_float), POINTER(c_float), POINTER(c_float), POINTER(c_float), POINTER(c_float)]
cublasSrotmg.__doc__ = \
"""void cublasSrotmg(float * sd1, float * sd2, float * sx1, unknown * sy1, float * sparam)
/usr/local/cuda/include/cublas.h:680"""
# /usr/local/cuda/include/cublas.h 710
cublasSscal = _libraries['cublas'].cublasSscal
cublasSscal.restype = None
# cublasSscal(n, alpha, x, incx)
cublasSscal.argtypes = [c_int, c_float, POINTER(c_float), c_int]
cublasSscal.__doc__ = \
"""void cublasSscal(int n, float alpha, float * x, int incx)
/usr/local/cuda/include/cublas.h:710"""
# /usr/local/cuda/include/cublas.h 740
cublasSswap = _libraries['cublas'].cublasSswap
cublasSswap.restype = None
# cublasSswap(n, x, incx, y, incy)
cublasSswap.argtypes = [c_int, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasSswap.__doc__ = \
"""void cublasSswap(int n, float * x, int incx, float * y, int incy)
/usr/local/cuda/include/cublas.h:740"""
# /usr/local/cuda/include/cublas.h 779
cublasCaxpy = _libraries['cublas'].cublasCaxpy
cublasCaxpy.restype = None
# cublasCaxpy(n, alpha, x, incx, y, incy)
cublasCaxpy.argtypes = [c_int, cuComplex, POINTER(cuComplex), c_int, POINTER(cuComplex), c_int]
cublasCaxpy.__doc__ = \
"""void cublasCaxpy(int n, cuComplex alpha, unknown * x, int incx, cuComplex * y, int incy)
/usr/local/cuda/include/cublas.h:779"""
# /usr/local/cuda/include/cublas.h 812
cublasCcopy = _libraries['cublas'].cublasCcopy
cublasCcopy.restype = None
# cublasCcopy(n, x, incx, y, incy)
cublasCcopy.argtypes = [c_int, POINTER(cuComplex), c_int, POINTER(cuComplex), c_int]
cublasCcopy.__doc__ = \
"""void cublasCcopy(int n, unknown * x, int incx, cuComplex * y, int incy)
/usr/local/cuda/include/cublas.h:812"""
# /usr/local/cuda/include/cublas.h 842
cublasCscal = _libraries['cublas'].cublasCscal
cublasCscal.restype = None
# cublasCscal(n, alpha, x, incx)
cublasCscal.argtypes = [c_int, cuComplex, POINTER(cuComplex), c_int]
cublasCscal.__doc__ = \
"""void cublasCscal(int n, cuComplex alpha, cuComplex * x, int incx)
/usr/local/cuda/include/cublas.h:842"""
# /usr/local/cuda/include/cublas.h 876
cublasCrotg = _libraries['cublas'].cublasCrotg
cublasCrotg.restype = None
# cublasCrotg(pca, cb, psc, pcs)
cublasCrotg.argtypes = [POINTER(cuComplex), cuComplex, POINTER(c_float), POINTER(cuComplex)]
cublasCrotg.__doc__ = \
"""void cublasCrotg(cuComplex * pca, cuComplex cb, float * psc, cuComplex * pcs)
/usr/local/cuda/include/cublas.h:876"""
# /usr/local/cuda/include/cublas.h 915
cublasCrot = _libraries['cublas'].cublasCrot
cublasCrot.restype = None
# cublasCrot(n, x, incx, y, incy, c, s)
cublasCrot.argtypes = [c_int, POINTER(cuComplex), c_int, POINTER(cuComplex), c_int, c_float, cuComplex]
cublasCrot.__doc__ = \
"""void cublasCrot(int n, cuComplex * x, int incx, cuComplex * y, int incy, float c, cuComplex s)
/usr/local/cuda/include/cublas.h:915"""
# /usr/local/cuda/include/cublas.h 954
cublasCsrot = _libraries['cublas'].cublasCsrot
cublasCsrot.restype = None
# cublasCsrot(n, x, incx, y, incy, c, s)
cublasCsrot.argtypes = [c_int, POINTER(cuComplex), c_int, POINTER(cuComplex), c_int, c_float, c_float]
cublasCsrot.__doc__ = \
"""void cublasCsrot(int n, cuComplex * x, int incx, cuComplex * y, int incy, float c, float s)
/usr/local/cuda/include/cublas.h:954"""
# /usr/local/cuda/include/cublas.h 984
cublasCsscal = _libraries['cublas'].cublasCsscal
cublasCsscal.restype = None
# cublasCsscal(n, alpha, x, incx)
cublasCsscal.argtypes = [c_int, c_float, POINTER(cuComplex), c_int]
cublasCsscal.__doc__ = \
"""void cublasCsscal(int n, float alpha, cuComplex * x, int incx)
/usr/local/cuda/include/cublas.h:984"""
# /usr/local/cuda/include/cublas.h 1018
cublasCswap = _libraries['cublas'].cublasCswap
cublasCswap.restype = None
# cublasCswap(n, x, incx, y, incy)
cublasCswap.argtypes = [c_int, POINTER(cuComplex), c_int, POINTER(cuComplex), c_int]
cublasCswap.__doc__ = \
"""void cublasCswap(int n, cuComplex * x, int incx, cuComplex * y, int incy)
/usr/local/cuda/include/cublas.h:1018"""
# /usr/local/cuda/include/cublas.h 1052
cublasCdotu = _libraries['cublas'].cublasCdotu
cublasCdotu.restype = cuComplex
# cublasCdotu(n, x, incx, y, incy)
cublasCdotu.argtypes = [c_int, POINTER(cuComplex), c_int, POINTER(cuComplex), c_int]
cublasCdotu.__doc__ = \
"""cuComplex cublasCdotu(int n, unknown * x, int incx, unknown * y, int incy)
/usr/local/cuda/include/cublas.h:1052"""
# /usr/local/cuda/include/cublas.h 1087
cublasCdotc = _libraries['cublas'].cublasCdotc
cublasCdotc.restype = cuComplex
# cublasCdotc(n, x, incx, y, incy)
cublasCdotc.argtypes = [c_int, POINTER(cuComplex), c_int, POINTER(cuComplex), c_int]
cublasCdotc.__doc__ = \
"""cuComplex cublasCdotc(int n, unknown * x, int incx, unknown * y, int incy)
/usr/local/cuda/include/cublas.h:1087"""
# /usr/local/cuda/include/cublas.h 1116
cublasIcamax = _libraries['cublas'].cublasIcamax
cublasIcamax.restype = c_int
# cublasIcamax(n, x, incx)
cublasIcamax.argtypes = [c_int, POINTER(cuComplex), c_int]
cublasIcamax.__doc__ = \
"""int cublasIcamax(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:1116"""
# /usr/local/cuda/include/cublas.h 1145
cublasIcamin = _libraries['cublas'].cublasIcamin
cublasIcamin.restype = c_int
# cublasIcamin(n, x, incx)
cublasIcamin.argtypes = [c_int, POINTER(cuComplex), c_int]
cublasIcamin.__doc__ = \
"""int cublasIcamin(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:1145"""
# /usr/local/cuda/include/cublas.h 1176
cublasScasum = _libraries['cublas'].cublasScasum
cublasScasum.restype = c_float
# cublasScasum(n, x, incx)
cublasScasum.argtypes = [c_int, POINTER(cuComplex), c_int]
cublasScasum.__doc__ = \
"""float cublasScasum(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:1176"""
# /usr/local/cuda/include/cublas.h 1204
cublasScnrm2 = _libraries['cublas'].cublasScnrm2
cublasScnrm2.restype = c_float
# cublasScnrm2(n, x, incx)
cublasScnrm2.argtypes = [c_int, POINTER(cuComplex), c_int]
cublasScnrm2.__doc__ = \
"""float cublasScnrm2(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:1204"""
# /usr/local/cuda/include/cublas.h 1271
cublasSgbmv = _libraries['cublas'].cublasSgbmv
cublasSgbmv.restype = None
# cublasSgbmv(trans, m, n, kl, ku, alpha, A, lda, x, incx, beta, y, incy)
cublasSgbmv.argtypes = [c_char, c_int, c_int, c_int, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int, c_float, POINTER(c_float), c_int]
cublasSgbmv.__doc__ = \
"""void cublasSgbmv(char trans, int m, int n, int kl, int ku, float alpha, unknown * A, int lda, unknown * x, int incx, float beta, float * y, int incy)
/usr/local/cuda/include/cublas.h:1271"""
# /usr/local/cuda/include/cublas.h 1332
cublasSgemv = _libraries['cublas'].cublasSgemv
cublasSgemv.restype = None
# cublasSgemv(trans, m, n, alpha, A, lda, x, incx, beta, y, incy)
cublasSgemv.argtypes = [c_char, c_int, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int, c_float, POINTER(c_float), c_int]
cublasSgemv.__doc__ = \
"""void cublasSgemv(char trans, int m, int n, float alpha, unknown * A, int lda, unknown * x, int incx, float beta, float * y, int incy)
/usr/local/cuda/include/cublas.h:1332"""
# /usr/local/cuda/include/cublas.h 1379
cublasSger = _libraries['cublas'].cublasSger
cublasSger.restype = None
# cublasSger(m, n, alpha, x, incx, y, incy, A, lda)
cublasSger.argtypes = [c_int, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasSger.__doc__ = \
"""void cublasSger(int m, int n, float alpha, unknown * x, int incx, unknown * y, int incy, float * A, int lda)
/usr/local/cuda/include/cublas.h:1379"""
# /usr/local/cuda/include/cublas.h 1444
cublasSsbmv = _libraries['cublas'].cublasSsbmv
cublasSsbmv.restype = None
# cublasSsbmv(uplo, n, k, alpha, A, lda, x, incx, beta, y, incy)
cublasSsbmv.argtypes = [c_char, c_int, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int, c_float, POINTER(c_float), c_int]
cublasSsbmv.__doc__ = \
"""void cublasSsbmv(char uplo, int n, int k, float alpha, unknown * A, int lda, unknown * x, int incx, float beta, float * y, int incy)
/usr/local/cuda/include/cublas.h:1444"""
# /usr/local/cuda/include/cublas.h 1497
cublasSspmv = _libraries['cublas'].cublasSspmv
cublasSspmv.restype = None
# cublasSspmv(uplo, n, alpha, AP, x, incx, beta, y, incy)
cublasSspmv.argtypes = [c_char, c_int, c_float, POINTER(c_float), POINTER(c_float), c_int, c_float, POINTER(c_float), c_int]
cublasSspmv.__doc__ = \
"""void cublasSspmv(char uplo, int n, float alpha, unknown * AP, unknown * x, int incx, float beta, float * y, int incy)
/usr/local/cuda/include/cublas.h:1497"""
# /usr/local/cuda/include/cublas.h 1546
cublasSspr = _libraries['cublas'].cublasSspr
cublasSspr.restype = None
# cublasSspr(uplo, n, alpha, x, incx, AP)
cublasSspr.argtypes = [c_char, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float)]
cublasSspr.__doc__ = \
"""void cublasSspr(char uplo, int n, float alpha, unknown * x, int incx, float * AP)
/usr/local/cuda/include/cublas.h:1546"""
# /usr/local/cuda/include/cublas.h 1600
cublasSspr2 = _libraries['cublas'].cublasSspr2
cublasSspr2.restype = None
# cublasSspr2(uplo, n, alpha, x, incx, y, incy, AP)
cublasSspr2.argtypes = [c_char, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int, POINTER(c_float)]
cublasSspr2.__doc__ = \
"""void cublasSspr2(char uplo, int n, float alpha, unknown * x, int incx, unknown * y, int incy, float * AP)
/usr/local/cuda/include/cublas.h:1600"""
# /usr/local/cuda/include/cublas.h 1660
cublasSsymv = _libraries['cublas'].cublasSsymv
cublasSsymv.restype = None
# cublasSsymv(uplo, n, alpha, A, lda, x, incx, beta, y, incy)
cublasSsymv.argtypes = [c_char, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int, c_float, POINTER(c_float), c_int]
cublasSsymv.__doc__ = \
"""void cublasSsymv(char uplo, int n, float alpha, unknown * A, int lda, unknown * x, int incx, float beta, float * y, int incy)
/usr/local/cuda/include/cublas.h:1660"""
# /usr/local/cuda/include/cublas.h 1714
cublasSsyr = _libraries['cublas'].cublasSsyr
cublasSsyr.restype = None
# cublasSsyr(uplo, n, alpha, x, incx, A, lda)
cublasSsyr.argtypes = [c_char, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasSsyr.__doc__ = \
"""void cublasSsyr(char uplo, int n, float alpha, unknown * x, int incx, float * A, int lda)
/usr/local/cuda/include/cublas.h:1714"""
# /usr/local/cuda/include/cublas.h 1768
cublasSsyr2 = _libraries['cublas'].cublasSsyr2
cublasSsyr2.restype = None
# cublasSsyr2(uplo, n, alpha, x, incx, y, incy, A, lda)
cublasSsyr2.argtypes = [c_char, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasSsyr2.__doc__ = \
"""void cublasSsyr2(char uplo, int n, float alpha, unknown * x, int incx, unknown * y, int incy, float * A, int lda)
/usr/local/cuda/include/cublas.h:1768"""
# /usr/local/cuda/include/cublas.h 1828
cublasStbmv = _libraries['cublas'].cublasStbmv
cublasStbmv.restype = None
# cublasStbmv(uplo, trans, diag, n, k, A, lda, x, incx)
cublasStbmv.argtypes = [c_char, c_char, c_char, c_int, c_int, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasStbmv.__doc__ = \
"""void cublasStbmv(char uplo, char trans, char diag, int n, int k, unknown * A, int lda, float * x, int incx)
/usr/local/cuda/include/cublas.h:1828"""
# /usr/local/cuda/include/cublas.h 1889
cublasStbsv = _libraries['cublas'].cublasStbsv
cublasStbsv.restype = None
# cublasStbsv(uplo, trans, diag, n, k, A, lda, x, incx)
cublasStbsv.argtypes = [c_char, c_char, c_char, c_int, c_int, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasStbsv.__doc__ = \
"""void cublasStbsv(char uplo, char trans, char diag, int n, int k, unknown * A, int lda, float * x, int incx)
/usr/local/cuda/include/cublas.h:1889"""
# /usr/local/cuda/include/cublas.h 1941
cublasStpmv = _libraries['cublas'].cublasStpmv
cublasStpmv.restype = None
# cublasStpmv(uplo, trans, diag, n, AP, x, incx)
cublasStpmv.argtypes = [c_char, c_char, c_char, c_int, POINTER(c_float), POINTER(c_float), c_int]
cublasStpmv.__doc__ = \
"""void cublasStpmv(char uplo, char trans, char diag, int n, unknown * AP, float * x, int incx)
/usr/local/cuda/include/cublas.h:1941"""
# /usr/local/cuda/include/cublas.h 1995
cublasStpsv = _libraries['cublas'].cublasStpsv
cublasStpsv.restype = None
# cublasStpsv(uplo, trans, diag, n, AP, x, incx)
cublasStpsv.argtypes = [c_char, c_char, c_char, c_int, POINTER(c_float), POINTER(c_float), c_int]
cublasStpsv.__doc__ = \
"""void cublasStpsv(char uplo, char trans, char diag, int n, unknown * AP, float * x, int incx)
/usr/local/cuda/include/cublas.h:1995"""
# /usr/local/cuda/include/cublas.h 2049
cublasStrmv = _libraries['cublas'].cublasStrmv
cublasStrmv.restype = None
# cublasStrmv(uplo, trans, diag, n, A, lda, x, incx)
cublasStrmv.argtypes = [c_char, c_char, c_char, c_int, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasStrmv.__doc__ = \
"""void cublasStrmv(char uplo, char trans, char diag, int n, unknown * A, int lda, float * x, int incx)
/usr/local/cuda/include/cublas.h:2049"""
# /usr/local/cuda/include/cublas.h 2109
cublasStrsv = _libraries['cublas'].cublasStrsv
cublasStrsv.restype = None
# cublasStrsv(uplo, trans, diag, n, A, lda, x, incx)
cublasStrsv.argtypes = [c_char, c_char, c_char, c_int, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasStrsv.__doc__ = \
"""void cublasStrsv(char uplo, char trans, char diag, int n, unknown * A, int lda, float * x, int incx)
/usr/local/cuda/include/cublas.h:2109"""
# /usr/local/cuda/include/cublas.h 2231
cublasSgemm = _libraries['cublas'].cublasSgemm
cublasSgemm.restype = None
# cublasSgemm(transa, transb, m, n, k, alpha, A, lda, B, ldb, beta, C, ldc)
cublasSgemm.argtypes = [c_char, c_char, c_int, c_int, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int, c_float, POINTER(c_float), c_int]
cublasSgemm.__doc__ = \
"""void cublasSgemm(char transa, char transb, int m, int n, int k, float alpha, unknown * A, int lda, unknown * B, int ldb, float beta, float * C, int ldc)
/usr/local/cuda/include/cublas.h:2231"""
# /usr/local/cuda/include/cublas.h 2312
cublasSsymm = _libraries['cublas'].cublasSsymm
cublasSsymm.restype = None
# cublasSsymm(side, uplo, m, n, alpha, A, lda, B, ldb, beta, C, ldc)
cublasSsymm.argtypes = [c_char, c_char, c_int, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int, c_float, POINTER(c_float), c_int]
cublasSsymm.__doc__ = \
"""void cublasSsymm(char side, char uplo, int m, int n, float alpha, unknown * A, int lda, unknown * B, int ldb, float beta, float * C, int ldc)
/usr/local/cuda/include/cublas.h:2312"""
# /usr/local/cuda/include/cublas.h 2389
cublasSsyrk = _libraries['cublas'].cublasSsyrk
cublasSsyrk.restype = None
# cublasSsyrk(uplo, trans, n, k, alpha, A, lda, beta, C, ldc)
cublasSsyrk.argtypes = [c_char, c_char, c_int, c_int, c_float, POINTER(c_float), c_int, c_float, POINTER(c_float), c_int]
cublasSsyrk.__doc__ = \
"""void cublasSsyrk(char uplo, char trans, int n, int k, float alpha, unknown * A, int lda, float beta, float * C, int ldc)
/usr/local/cuda/include/cublas.h:2389"""
# /usr/local/cuda/include/cublas.h 2474
cublasSsyr2k = _libraries['cublas'].cublasSsyr2k
cublasSsyr2k.restype = None
# cublasSsyr2k(uplo, trans, n, k, alpha, A, lda, B, ldb, beta, C, ldc)
cublasSsyr2k.argtypes = [c_char, c_char, c_int, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int, c_float, POINTER(c_float), c_int]
cublasSsyr2k.__doc__ = \
"""void cublasSsyr2k(char uplo, char trans, int n, int k, float alpha, unknown * A, int lda, unknown * B, int ldb, float beta, float * C, int ldc)
/usr/local/cuda/include/cublas.h:2474"""
# /usr/local/cuda/include/cublas.h 2547
cublasStrmm = _libraries['cublas'].cublasStrmm
cublasStrmm.restype = None
# cublasStrmm(side, uplo, transa, diag, m, n, alpha, A, lda, B, ldb)
cublasStrmm.argtypes = [c_char, c_char, c_char, c_char, c_int, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasStrmm.__doc__ = \
"""void cublasStrmm(char side, char uplo, char transa, char diag, int m, int n, float alpha, unknown * A, int lda, float * B, int ldb)
/usr/local/cuda/include/cublas.h:2547"""
# /usr/local/cuda/include/cublas.h 2625
cublasStrsm = _libraries['cublas'].cublasStrsm
cublasStrsm.restype = None
# cublasStrsm(side, uplo, transa, diag, m, n, alpha, A, lda, B, ldb)
cublasStrsm.argtypes = [c_char, c_char, c_char, c_char, c_int, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasStrsm.__doc__ = \
"""void cublasStrsm(char side, char uplo, char transa, char diag, int m, int n, float alpha, unknown * A, int lda, float * B, int ldb)
/usr/local/cuda/include/cublas.h:2625"""
# /usr/local/cuda/include/cublas.h 2692
cublasCgemm = _libraries['cublas'].cublasCgemm
cublasCgemm.restype = None
# cublasCgemm(transa, transb, m, n, k, alpha, A, lda, B, ldb, beta, C, ldc)
cublasCgemm.argtypes = [c_char, c_char, c_int, c_int, c_int, cuComplex, POINTER(cuComplex), c_int, POINTER(cuComplex), c_int, cuComplex, POINTER(cuComplex), c_int]
cublasCgemm.__doc__ = \
"""void cublasCgemm(char transa, char transb, int m, int n, int k, cuComplex alpha, unknown * A, int lda, unknown * B, int ldb, cuComplex beta, cuComplex * C, int ldc)
/usr/local/cuda/include/cublas.h:2692"""
# /usr/local/cuda/include/cublas.h 2722
cublasXerbla = _libraries['cublas'].cublasXerbla
cublasXerbla.restype = None
# cublasXerbla(srName, info)
cublasXerbla.argtypes = [STRING, c_int]
cublasXerbla.__doc__ = \
"""void cublasXerbla(unknown * srName, int info)
/usr/local/cuda/include/cublas.h:2722"""
# /usr/local/cuda/include/cublas.h 2755
cublasDasum = _libraries['cublas'].cublasDasum
cublasDasum.restype = c_double
# cublasDasum(n, x, incx)
cublasDasum.argtypes = [c_int, POINTER(c_double), c_int]
cublasDasum.__doc__ = \
"""double cublasDasum(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:2755"""
# /usr/local/cuda/include/cublas.h 2793
cublasDaxpy = _libraries['cublas'].cublasDaxpy
cublasDaxpy.restype = None
# cublasDaxpy(n, alpha, x, incx, y, incy)
cublasDaxpy.argtypes = [c_int, c_double, POINTER(c_double), c_int, POINTER(c_double), c_int]
cublasDaxpy.__doc__ = \
"""void cublasDaxpy(int n, double alpha, unknown * x, int incx, double * y, int incy)
/usr/local/cuda/include/cublas.h:2793"""
# /usr/local/cuda/include/cublas.h 2827
cublasDcopy = _libraries['cublas'].cublasDcopy
cublasDcopy.restype = None
# cublasDcopy(n, x, incx, y, incy)
cublasDcopy.argtypes = [c_int, POINTER(c_double), c_int, POINTER(c_double), c_int]
cublasDcopy.__doc__ = \
"""void cublasDcopy(int n, unknown * x, int incx, double * y, int incy)
/usr/local/cuda/include/cublas.h:2827"""
# /usr/local/cuda/include/cublas.h 2862
cublasDdot = _libraries['cublas'].cublasDdot
cublasDdot.restype = c_double
# cublasDdot(n, x, incx, y, incy)
cublasDdot.argtypes = [c_int, POINTER(c_double), c_int, POINTER(c_double), c_int]
cublasDdot.__doc__ = \
"""double cublasDdot(int n, unknown * x, int incx, unknown * y, int incy)
/usr/local/cuda/include/cublas.h:2862"""
# /usr/local/cuda/include/cublas.h 2893
cublasDnrm2 = _libraries['cublas'].cublasDnrm2
cublasDnrm2.restype = c_double
# cublasDnrm2(n, x, incx)
cublasDnrm2.argtypes = [c_int, POINTER(c_double), c_int]
cublasDnrm2.__doc__ = \
"""double cublasDnrm2(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:2893"""
# /usr/local/cuda/include/cublas.h 2933
cublasDrot = _libraries['cublas'].cublasDrot
cublasDrot.restype = None
# cublasDrot(n, x, incx, y, incy, sc, ss)
cublasDrot.argtypes = [c_int, POINTER(c_double), c_int, POINTER(c_double), c_int, c_double, c_double]
cublasDrot.__doc__ = \
"""void cublasDrot(int n, double * x, int incx, double * y, int incy, double sc, double ss)
/usr/local/cuda/include/cublas.h:2933"""
# /usr/local/cuda/include/cublas.h 2974
cublasDrotg = _libraries['cublas'].cublasDrotg
cublasDrotg.restype = None
# cublasDrotg(sa, sb, sc, ss)
cublasDrotg.argtypes = [POINTER(c_double), POINTER(c_double), POINTER(c_double), POINTER(c_double)]
cublasDrotg.__doc__ = \
"""void cublasDrotg(double * sa, double * sb, double * sc, double * ss)
/usr/local/cuda/include/cublas.h:2974"""
# /usr/local/cuda/include/cublas.h 3024
cublasDrotm = _libraries['cublas'].cublasDrotm
cublasDrotm.restype = None
# cublasDrotm(n, x, incx, y, incy, sparam)
cublasDrotm.argtypes = [c_int, POINTER(c_double), c_int, POINTER(c_double), c_int, POINTER(c_double)]
cublasDrotm.__doc__ = \
"""void cublasDrotm(int n, double * x, int incx, double * y, int incy, unknown * sparam)
/usr/local/cuda/include/cublas.h:3024"""
# /usr/local/cuda/include/cublas.h 3067
cublasDrotmg = _libraries['cublas'].cublasDrotmg
cublasDrotmg.restype = None
# cublasDrotmg(sd1, sd2, sx1, sy1, sparam)
cublasDrotmg.argtypes = [POINTER(c_double), POINTER(c_double), POINTER(c_double), POINTER(c_double), POINTER(c_double)]
cublasDrotmg.__doc__ = \
"""void cublasDrotmg(double * sd1, double * sd2, double * sx1, unknown * sy1, double * sparam)
/usr/local/cuda/include/cublas.h:3067"""
# /usr/local/cuda/include/cublas.h 3098
cublasDscal = _libraries['cublas'].cublasDscal
cublasDscal.restype = None
# cublasDscal(n, alpha, x, incx)
cublasDscal.argtypes = [c_int, c_double, POINTER(c_double), c_int]
cublasDscal.__doc__ = \
"""void cublasDscal(int n, double alpha, double * x, int incx)
/usr/local/cuda/include/cublas.h:3098"""
# /usr/local/cuda/include/cublas.h 3129
cublasDswap = _libraries['cublas'].cublasDswap
cublasDswap.restype = None
# cublasDswap(n, x, incx, y, incy)
cublasDswap.argtypes = [c_int, POINTER(c_double), c_int, POINTER(c_double), c_int]
cublasDswap.__doc__ = \
"""void cublasDswap(int n, double * x, int incx, double * y, int incy)
/usr/local/cuda/include/cublas.h:3129"""
# /usr/local/cuda/include/cublas.h 3159
cublasIdamax = _libraries['cublas'].cublasIdamax
cublasIdamax.restype = c_int
# cublasIdamax(n, x, incx)
cublasIdamax.argtypes = [c_int, POINTER(c_double), c_int]
cublasIdamax.__doc__ = \
"""int cublasIdamax(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:3159"""
# /usr/local/cuda/include/cublas.h 3189
cublasIdamin = _libraries['cublas'].cublasIdamin
cublasIdamin.restype = c_int
# cublasIdamin(n, x, incx)
cublasIdamin.argtypes = [c_int, POINTER(c_double), c_int]
cublasIdamin.__doc__ = \
"""int cublasIdamin(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:3189"""
# /usr/local/cuda/include/cublas.h 3255
cublasDgemv = _libraries['cublas'].cublasDgemv
cublasDgemv.restype = None
# cublasDgemv(trans, m, n, alpha, A, lda, x, incx, beta, y, incy)
cublasDgemv.argtypes = [c_char, c_int, c_int, c_double, POINTER(c_double), c_int, POINTER(c_double), c_int, c_double, POINTER(c_double), c_int]
cublasDgemv.__doc__ = \
"""void cublasDgemv(char trans, int m, int n, double alpha, unknown * A, int lda, unknown * x, int incx, double beta, double * y, int incy)
/usr/local/cuda/include/cublas.h:3255"""
# /usr/local/cuda/include/cublas.h 3304
cublasDger = _libraries['cublas'].cublasDger
cublasDger.restype = None
# cublasDger(m, n, alpha, x, incx, y, incy, A, lda)
cublasDger.argtypes = [c_int, c_int, c_double, POINTER(c_double), c_int, POINTER(c_double), c_int, POINTER(c_double), c_int]
cublasDger.__doc__ = \
"""void cublasDger(int m, int n, double alpha, unknown * x, int incx, unknown * y, int incy, double * A, int lda)
/usr/local/cuda/include/cublas.h:3304"""
# /usr/local/cuda/include/cublas.h 3360
cublasDsyr = _libraries['cublas'].cublasDsyr
cublasDsyr.restype = None
# cublasDsyr(uplo, n, alpha, x, incx, A, lda)
cublasDsyr.argtypes = [c_char, c_int, c_double, POINTER(c_double), c_int, POINTER(c_double), c_int]
cublasDsyr.__doc__ = \
"""void cublasDsyr(char uplo, int n, double alpha, unknown * x, int incx, double * A, int lda)
/usr/local/cuda/include/cublas.h:3360"""
# /usr/local/cuda/include/cublas.h 3422
cublasDtrsv = _libraries['cublas'].cublasDtrsv
cublasDtrsv.restype = None
# cublasDtrsv(uplo, trans, diag, n, A, lda, x, incx)
cublasDtrsv.argtypes = [c_char, c_char, c_char, c_int, POINTER(c_double), c_int, POINTER(c_double), c_int]
cublasDtrsv.__doc__ = \
"""void cublasDtrsv(char uplo, char trans, char diag, int n, unknown * A, int lda, double * x, int incx)
/usr/local/cuda/include/cublas.h:3422"""
# /usr/local/cuda/include/cublas.h 3493
cublasDgemm = _libraries['cublas'].cublasDgemm
cublasDgemm.restype = None
# cublasDgemm(transa, transb, m, n, k, alpha, A, lda, B, ldb, beta, C, ldc)
cublasDgemm.argtypes = [c_char, c_char, c_int, c_int, c_int, c_double, POINTER(c_double), c_int, POINTER(c_double), c_int, c_double, POINTER(c_double), c_int]
cublasDgemm.__doc__ = \
"""void cublasDgemm(char transa, char transb, int m, int n, int k, double alpha, unknown * A, int lda, unknown * B, int ldb, double beta, double * C, int ldc)
/usr/local/cuda/include/cublas.h:3493"""
# /usr/local/cuda/include/cublas.h 3573
cublasDtrsm = _libraries['cublas'].cublasDtrsm
cublasDtrsm.restype = None
# cublasDtrsm(side, uplo, transa, diag, m, n, alpha, A, lda, B, ldb)
cublasDtrsm.argtypes = [c_char, c_char, c_char, c_char, c_int, c_int, c_double, POINTER(c_double), c_int, POINTER(c_double), c_int]
cublasDtrsm.__doc__ = \
"""void cublasDtrsm(char side, char uplo, char transa, char diag, int m, int n, double alpha, unknown * A, int lda, double * B, int ldb)
/usr/local/cuda/include/cublas.h:3573"""
# /usr/local/cuda/include/cublas.h 3648
cublasDtrmm = _libraries['cublas'].cublasDtrmm
cublasDtrmm.restype = None
# cublasDtrmm(side, uplo, transa, diag, m, n, alpha, A, lda, B, ldb)
cublasDtrmm.argtypes = [c_char, c_char, c_char, c_char, c_int, c_int, c_double, POINTER(c_double), c_int, POINTER(c_double), c_int]
cublasDtrmm.__doc__ = \
"""void cublasDtrmm(char side, char uplo, char transa, char diag, int m, int n, double alpha, unknown * A, int lda, double * B, int ldb)
/usr/local/cuda/include/cublas.h:3648"""
# /usr/local/cuda/include/cublas.h 3731
cublasDsymm = _libraries['cublas'].cublasDsymm
cublasDsymm.restype = None
# cublasDsymm(side, uplo, m, n, alpha, A, lda, B, ldb, beta, C, ldc)
cublasDsymm.argtypes = [c_char, c_char, c_int, c_int, c_double, POINTER(c_double), c_int, POINTER(c_double), c_int, c_double, POINTER(c_double), c_int]
cublasDsymm.__doc__ = \
"""void cublasDsymm(char side, char uplo, int m, int n, double alpha, unknown * A, int lda, unknown * B, int ldb, double beta, double * C, int ldc)
/usr/local/cuda/include/cublas.h:3731"""
# /usr/local/cuda/include/cublas.h 3809
cublasDsyrk = _libraries['cublas'].cublasDsyrk
cublasDsyrk.restype = None
# cublasDsyrk(uplo, trans, n, k, alpha, A, lda, beta, C, ldc)
cublasDsyrk.argtypes = [c_char, c_char, c_int, c_int, c_double, POINTER(c_double), c_int, c_double, POINTER(c_double), c_int]
cublasDsyrk.__doc__ = \
"""void cublasDsyrk(char uplo, char trans, int n, int k, double alpha, unknown * A, int lda, double beta, double * C, int ldc)
/usr/local/cuda/include/cublas.h:3809"""
# /usr/local/cuda/include/cublas.h 3896
cublasDsyr2k = _libraries['cublas'].cublasDsyr2k
cublasDsyr2k.restype = None
# cublasDsyr2k(uplo, trans, n, k, alpha, A, lda, B, ldb, beta, C, ldc)
cublasDsyr2k.argtypes = [c_char, c_char, c_int, c_int, c_double, POINTER(c_double), c_int, POINTER(c_double), c_int, c_double, POINTER(c_double), c_int]
cublasDsyr2k.__doc__ = \
"""void cublasDsyr2k(char uplo, char trans, int n, int k, double alpha, unknown * A, int lda, unknown * B, int ldb, double beta, double * C, int ldc)
/usr/local/cuda/include/cublas.h:3896"""
# /usr/local/cuda/include/cublas.h 3964
cublasZgemm = _libraries['cublas'].cublasZgemm
cublasZgemm.restype = None
# cublasZgemm(transa, transb, m, n, k, alpha, A, lda, B, ldb, beta, C, ldc)
cublasZgemm.argtypes = [c_char, c_char, c_int, c_int, c_int, cuDoubleComplex, POINTER(cuDoubleComplex), c_int, POINTER(cuDoubleComplex), c_int, cuDoubleComplex, POINTER(cuDoubleComplex), c_int]
cublasZgemm.__doc__ = \
"""void cublasZgemm(char transa, char transb, int m, int n, int k, cuDoubleComplex alpha, unknown * A, int lda, unknown * B, int ldb, cuDoubleComplex beta, cuDoubleComplex * C, int ldc)
/usr/local/cuda/include/cublas.h:3964"""
# /usr/local/cuda/include/vector_types.h 55
class char1(Structure):
    pass
char1._fields_ = [
    # /usr/local/cuda/include/vector_types.h 55
    ('x', c_byte),
]
# /usr/local/cuda/include/vector_types.h 61
class uchar1(Structure):
    pass
uchar1._fields_ = [
    # /usr/local/cuda/include/vector_types.h 61
    ('x', c_ubyte),
]
# /usr/local/cuda/include/vector_types.h 67
class char2(Structure):
    pass
char2._fields_ = [
    # /usr/local/cuda/include/vector_types.h 67
    ('x', c_byte),
    ('y', c_byte),
]
# /usr/local/cuda/include/vector_types.h 73
class uchar2(Structure):
    pass
uchar2._fields_ = [
    # /usr/local/cuda/include/vector_types.h 73
    ('x', c_ubyte),
    ('y', c_ubyte),
]
# /usr/local/cuda/include/vector_types.h 79
class char3(Structure):
    pass
char3._fields_ = [
    # /usr/local/cuda/include/vector_types.h 79
    ('x', c_byte),
    ('y', c_byte),
    ('z', c_byte),
]
# /usr/local/cuda/include/vector_types.h 85
class uchar3(Structure):
    pass
uchar3._fields_ = [
    # /usr/local/cuda/include/vector_types.h 85
    ('x', c_ubyte),
    ('y', c_ubyte),
    ('z', c_ubyte),
]
# /usr/local/cuda/include/vector_types.h 91
class char4(Structure):
    pass
char4._fields_ = [
    # /usr/local/cuda/include/vector_types.h 91
    ('x', c_byte),
    ('y', c_byte),
    ('z', c_byte),
    ('w', c_byte),
]
# /usr/local/cuda/include/vector_types.h 97
class uchar4(Structure):
    pass
uchar4._fields_ = [
    # /usr/local/cuda/include/vector_types.h 97
    ('x', c_ubyte),
    ('y', c_ubyte),
    ('z', c_ubyte),
    ('w', c_ubyte),
]
# /usr/local/cuda/include/vector_types.h 103
class short1(Structure):
    pass
short1._fields_ = [
    # /usr/local/cuda/include/vector_types.h 103
    ('x', c_short),
]
# /usr/local/cuda/include/vector_types.h 109
class ushort1(Structure):
    pass
ushort1._fields_ = [
    # /usr/local/cuda/include/vector_types.h 109
    ('x', c_ushort),
]
# /usr/local/cuda/include/vector_types.h 115
class short2(Structure):
    pass
short2._fields_ = [
    # /usr/local/cuda/include/vector_types.h 115
    ('x', c_short),
    ('y', c_short),
]
# /usr/local/cuda/include/vector_types.h 121
class ushort2(Structure):
    pass
ushort2._fields_ = [
    # /usr/local/cuda/include/vector_types.h 121
    ('x', c_ushort),
    ('y', c_ushort),
]
# /usr/local/cuda/include/vector_types.h 127
class short3(Structure):
    pass
short3._fields_ = [
    # /usr/local/cuda/include/vector_types.h 127
    ('x', c_short),
    ('y', c_short),
    ('z', c_short),
]
# /usr/local/cuda/include/vector_types.h 133
class ushort3(Structure):
    pass
ushort3._fields_ = [
    # /usr/local/cuda/include/vector_types.h 133
    ('x', c_ushort),
    ('y', c_ushort),
    ('z', c_ushort),
]
# /usr/local/cuda/include/vector_types.h 139
class short4(Structure):
    pass
short4._fields_ = [
    # /usr/local/cuda/include/vector_types.h 139
    ('x', c_short),
    ('y', c_short),
    ('z', c_short),
    ('w', c_short),
]
# /usr/local/cuda/include/vector_types.h 145
class ushort4(Structure):
    pass
ushort4._fields_ = [
    # /usr/local/cuda/include/vector_types.h 145
    ('x', c_ushort),
    ('y', c_ushort),
    ('z', c_ushort),
    ('w', c_ushort),
]
# /usr/local/cuda/include/vector_types.h 151
class int1(Structure):
    pass
int1._fields_ = [
    # /usr/local/cuda/include/vector_types.h 151
    ('x', c_int),
]
# /usr/local/cuda/include/vector_types.h 157
class uint1(Structure):
    pass
uint1._fields_ = [
    # /usr/local/cuda/include/vector_types.h 157
    ('x', c_uint),
]
# /usr/local/cuda/include/vector_types.h 163
class int2(Structure):
    pass
int2._fields_ = [
    # /usr/local/cuda/include/vector_types.h 163
    ('x', c_int),
    ('y', c_int),
]
# /usr/local/cuda/include/vector_types.h 169
class uint2(Structure):
    pass
uint2._fields_ = [
    # /usr/local/cuda/include/vector_types.h 169
    ('x', c_uint),
    ('y', c_uint),
]
# /usr/local/cuda/include/vector_types.h 175
class int3(Structure):
    pass
int3._fields_ = [
    # /usr/local/cuda/include/vector_types.h 175
    ('x', c_int),
    ('y', c_int),
    ('z', c_int),
]
# /usr/local/cuda/include/vector_types.h 181
class uint3(Structure):
    pass
uint3._fields_ = [
    # /usr/local/cuda/include/vector_types.h 181
    ('x', c_uint),
    ('y', c_uint),
    ('z', c_uint),
]
# /usr/local/cuda/include/vector_types.h 187
class int4(Structure):
    pass
int4._fields_ = [
    # /usr/local/cuda/include/vector_types.h 187
    ('x', c_int),
    ('y', c_int),
    ('z', c_int),
    ('w', c_int),
]
# /usr/local/cuda/include/vector_types.h 193
class uint4(Structure):
    pass
uint4._fields_ = [
    # /usr/local/cuda/include/vector_types.h 193
    ('x', c_uint),
    ('y', c_uint),
    ('z', c_uint),
    ('w', c_uint),
]
# /usr/local/cuda/include/vector_types.h 199
class long1(Structure):
    pass
long1._fields_ = [
    # /usr/local/cuda/include/vector_types.h 199
    ('x', c_long),
]
# /usr/local/cuda/include/vector_types.h 205
class ulong1(Structure):
    pass
ulong1._fields_ = [
    # /usr/local/cuda/include/vector_types.h 205
    ('x', c_ulong),
]
# /usr/local/cuda/include/vector_types.h 217
class long2(Structure):
    pass
long2._fields_ = [
    # /usr/local/cuda/include/vector_types.h 217
    ('x', c_long),
    ('y', c_long),
]
# /usr/local/cuda/include/vector_types.h 229
class ulong2(Structure):
    pass
ulong2._fields_ = [
    # /usr/local/cuda/include/vector_types.h 229
    ('x', c_ulong),
    ('y', c_ulong),
]
# /usr/local/cuda/include/vector_types.h 237
class long3(Structure):
    pass
long3._fields_ = [
    # /usr/local/cuda/include/vector_types.h 237
    ('x', c_long),
    ('y', c_long),
    ('z', c_long),
]
# /usr/local/cuda/include/vector_types.h 243
class ulong3(Structure):
    pass
ulong3._fields_ = [
    # /usr/local/cuda/include/vector_types.h 243
    ('x', c_ulong),
    ('y', c_ulong),
    ('z', c_ulong),
]
# /usr/local/cuda/include/vector_types.h 249
class long4(Structure):
    pass
long4._fields_ = [
    # /usr/local/cuda/include/vector_types.h 249
    ('x', c_long),
    ('y', c_long),
    ('z', c_long),
    ('w', c_long),
]
# /usr/local/cuda/include/vector_types.h 255
class ulong4(Structure):
    pass
ulong4._fields_ = [
    # /usr/local/cuda/include/vector_types.h 255
    ('x', c_ulong),
    ('y', c_ulong),
    ('z', c_ulong),
    ('w', c_ulong),
]
# /usr/local/cuda/include/vector_types.h 263
class float1(Structure):
    pass
float1._fields_ = [
    # /usr/local/cuda/include/vector_types.h 263
    ('x', c_float),
]
float2._fields_ = [
    # /usr/local/cuda/include/vector_types.h 269
    ('x', c_float),
    ('y', c_float),
]
# /usr/local/cuda/include/vector_types.h 275
class float3(Structure):
    pass
float3._fields_ = [
    # /usr/local/cuda/include/vector_types.h 275
    ('x', c_float),
    ('y', c_float),
    ('z', c_float),
]
# /usr/local/cuda/include/vector_types.h 281
class float4(Structure):
    pass
float4._fields_ = [
    # /usr/local/cuda/include/vector_types.h 281
    ('x', c_float),
    ('y', c_float),
    ('z', c_float),
    ('w', c_float),
]
# /usr/local/cuda/include/vector_types.h 287
class double1(Structure):
    pass
double1._pack_ = 4
double1._fields_ = [
    # /usr/local/cuda/include/vector_types.h 287
    ('x', c_double),
]
double2._pack_ = 4
double2._fields_ = [
    # /usr/local/cuda/include/vector_types.h 293
    ('x', c_double),
    ('y', c_double),
]
# /usr/local/cuda/include/vector_types.h 391
class dim3(Structure):
    pass
dim3._fields_ = [
    # /usr/local/cuda/include/vector_types.h 391
]
__all__ = ['cublasDswap', 'short4', 'coshf', 'cublasSsymv', 'cbrtf',
           'nearbyint', 'coshl', 'cbrtl', 'cublasCaxpy',
           'cublasGetError', 'acosl', 'cublasSspr', 'expm1f',
           'cublasSsymm', 'acosh', 'y1', 'acosf', 'cublasDdot',
           '_FP_SUPERNORMAL', 'cublasSasum', 'lrintl', 'log2f',
           'fmodl', 'cuDoubleComplex', 'cublasStrsm', 'log2l',
           '__fpclassify', 'lrintf', 'ilogb', 'uint4', 'short3',
           'frexp', 'ushort1', 'ushort2', 'cublasStrsv', 'ushort4',
           'cublasAlloc', '_FP_NORMAL', 'double2', 'ulong4',
           'cublasIdamax', '__inf', 'cublasSspmv', 'fmodf',
           'cublasSaxpy', 'cublasSscal', 'lgammaf', 'scalbnf', 'yn',
           'tgamma', 'scalbn', 'scalbnl', 'cublasStpsv', 'lgammal',
           'ceil', 'cublasIdamin', 'rintl', 'truncl', '_FP_ZERO',
           'cublasGetVector', 'fmaf', 'long4', 'scalblnf', 'float_t',
           'cublasZgemm', 'uchar1', 'cublasSgemm', 'uchar3', 'uchar2',
           'cublasDgemv', 'uchar4', 'modf', 'cublasCgemm', 'float4',
           'modfl', 'round', 'cublasXerbla', 'ldexpl', 'tanhl',
           'cosf', 'nextafterl', 'nexttoward', 'cublasScopy',
           'cublasCrotg', '__math_errhandling', 'tanhf', 'cosl', 'j0',
           '__inff', 'cosh', 'logf', 'fminl', 'hypot', 'logb',
           'sinhf', 'y0', 'int1', 'scalbln', 'logl', 'cublasDrotg',
           'float1', 'float2', 'sinhl', '__nan', 'asin',
           'cublasSswap', 'exp2f', 'nanl', 'cublasDrotmg', 'exp2l',
           'nanf', 'cublasDsyrk', 'cuComplex', 'erfcf', 'llroundl',
           'atan2l', 'long2', 'cublasDasum', 'erfcl', 'ldexpf',
           'atan2f', 'llroundf', 'cublasSsyr', 'log1pl',
           'cublasStbsv', 'log2', 'fmod', 'tgammal', 'fmax',
           'copysign', 'cublasScnrm2', 'log1pf', 'tgammaf',
           'cublasScasum', 'char3', 'cublasSger', 'cublasDtrsv',
           'ilogbl', 'sinl', 'drem', 'truncf', 'sinh', 'sinf',
           'uint3', 'ilogbf', 'remainder', 'char4', 'trunc', 'atanhl',
           'frexpl', 'expm1', 'lroundf', 'cublasShutdown',
           'cuFloatComplex', 'atanhf', 'cublasDsymm', 'jn', 'lroundl',
           'erff', 'remainderf', 'erfc', 'fmin', 'llround', 'acos',
           'erfl', 'cublasCswap', 'ulong2', 'gamma', 'cublasSrotmg',
           'remquol', 'roundl', 'cublasCrot', 'acoshf', 'floorf',
           'fmaxf', 'roundf', 'pow', 'double_t', 'floorl', 'fmaxl',
           'fabsl', 'ldexp', 'cublasCsrot', 'fmal', 'roundtol',
           'cublasDtrsm', 'sqrtl', 'cublasDcopy', 'cublasStrmv',
           'cublasDtrmm', 'cublasCscal', 'sqrtf', 'cublasStbmv',
           'hypotf', 'copysignf', 'log', 'cublasFree', 'fdimf',
           'hypotl', 'exp2', 'lround', 'fdiml', 'float3', 'ushort3',
           'cublasSgbmv', 'fminf', 'nextafterf', 'cublasSetVector',
           'cublasCcopy', 'log10', 'remquof', 'fma', 'cublasDsyr2k',
           'asinh', 'char2', 'uint1', 'asinl', 'nexttowardf',
           'nearbyintf', 'cublasSspr2', 'cublasDrot', 'asinf', 'cos',
           'j1', 'cublasDnrm2', 'int4', 'llrint', 'llrintl',
           'cublasIcamin', 'int3', 'int2', 'cublasDger', 'lrint',
           'llrintf', 'tanl', '_FP_NAN', 'cublasSetMatrix',
           'cublasSsyr2', 'tanh', 'fdim', 'tanf', 'cublasIcamax',
           'double1', 'scalblnl', 'rintf', 'uint2', 'lgamma', 'erf',
           'cublasSgemv', 'short1', 'ulong1', 'expl', 'cublasCsscal',
           'cublasGetMatrix', 'remquo', 'log1p', 'expf', 'log10l',
           'cublasSnrm2', 'cublasDaxpy', 'char1', '_FP_SUBNORMAL',
           'log10f', 'nearbyintl', 'remainderl', 'short2', 'long3',
           'cublasSrot', '_FP_INFINITE', '__fpclassifyf', 'tan',
           '__fpclassifyd', 'cublasCdotc', 'atanf', 'fabs', 'floor',
           'cublasDrotm', 'atanh', 'nan', 'copysignl', 'sqrt',
           'atanl', 'rint', 'cublasSrotm', 'signgam', 'cublasCdotu',
           'modff', 'cublasDscal', 'cublasSrotg', 'finite', 'dim3',
           'sin', 'nextafter', 'frexpf', 'ceilf', 'powl', 'atan',
           'ceill', 'cublasStrmm', 'long1', 'cublasDgemm', 'rinttol',
           'nexttowardl', 'cublasSsbmv', 'logbf', 'cublasSsyrk',
           'cublasStpmv', 'significand', 'logbl', 'ulong3', 'cbrt',
           'cublasDsyr', 'cublasSsyr2k', 'cublasIsamin',
           'cublasIsamax', 'fabsf', 'expm1l', 'cublasInit', 'atan2',
           'scalb', 'cublasStatus', 'asinhf', 'exp', 'cublasSdot',
           'acoshl', 'powf', 'asinhl']
