#!/bin/tcsh -f
set flag1=""
#set flopt="--maxrregcount 12 --use_fast_math --gpu-code sm_11"
set flopt="--use_fast_math --gpu-code sm_11 --ptxas-options=-v"
set lib="-L$CUDA/lib -lcudart -lcuda"
#nvcc ${flag1} ${flopt} ${1}.cu -c -o ${1}.o |& grep -iv warning
nvcc ${flag1} ${flopt} ${1}.cu -c -o ${1}.o
g++ -shared ${lib} -o lib${1}.so ${1}.o
strip -x lib${1}.so
rm ${1}.o 
