# generated by 'xml2py'
# flags 'cublas.xml -c -d -v -l cublas'
from ctypes import *
from cuda.utils import get_lib
c_longdouble = c_double

_libraries = {}
_libraries['cublas'] = get_lib('cublas')
STRING = c_char_p


# ./my_CUDA2100_vector_types.h 55
class char1(Structure):
    pass
char1._fields_ = [
    # ./my_CUDA2100_vector_types.h 55
    ('x', c_byte),
]
# ./my_CUDA2100_vector_types.h 61
class uchar1(Structure):
    pass
uchar1._fields_ = [
    # ./my_CUDA2100_vector_types.h 61
    ('x', c_ubyte),
]
# ./my_CUDA2100_vector_types.h 67
class char2(Structure):
    pass
char2._fields_ = [
    # ./my_CUDA2100_vector_types.h 67
    ('x', c_byte),
    ('y', c_byte),
]
# ./my_CUDA2100_vector_types.h 73
class uchar2(Structure):
    pass
uchar2._fields_ = [
    # ./my_CUDA2100_vector_types.h 73
    ('x', c_ubyte),
    ('y', c_ubyte),
]
# ./my_CUDA2100_vector_types.h 79
class char3(Structure):
    pass
char3._fields_ = [
    # ./my_CUDA2100_vector_types.h 79
    ('x', c_byte),
    ('y', c_byte),
    ('z', c_byte),
]
# ./my_CUDA2100_vector_types.h 85
class uchar3(Structure):
    pass
uchar3._fields_ = [
    # ./my_CUDA2100_vector_types.h 85
    ('x', c_ubyte),
    ('y', c_ubyte),
    ('z', c_ubyte),
]
# ./my_CUDA2100_vector_types.h 91
class char4(Structure):
    pass
char4._fields_ = [
    # ./my_CUDA2100_vector_types.h 91
    ('x', c_byte),
    ('y', c_byte),
    ('z', c_byte),
    ('w', c_byte),
]
# ./my_CUDA2100_vector_types.h 97
class uchar4(Structure):
    pass
uchar4._fields_ = [
    # ./my_CUDA2100_vector_types.h 97
    ('x', c_ubyte),
    ('y', c_ubyte),
    ('z', c_ubyte),
    ('w', c_ubyte),
]
# ./my_CUDA2100_vector_types.h 103
class short1(Structure):
    pass
short1._fields_ = [
    # ./my_CUDA2100_vector_types.h 103
    ('x', c_short),
]
# ./my_CUDA2100_vector_types.h 109
class ushort1(Structure):
    pass
ushort1._fields_ = [
    # ./my_CUDA2100_vector_types.h 109
    ('x', c_ushort),
]
# ./my_CUDA2100_vector_types.h 115
class short2(Structure):
    pass
short2._fields_ = [
    # ./my_CUDA2100_vector_types.h 115
    ('x', c_short),
    ('y', c_short),
]
# ./my_CUDA2100_vector_types.h 121
class ushort2(Structure):
    pass
ushort2._fields_ = [
    # ./my_CUDA2100_vector_types.h 121
    ('x', c_ushort),
    ('y', c_ushort),
]
# ./my_CUDA2100_vector_types.h 127
class short3(Structure):
    pass
short3._fields_ = [
    # ./my_CUDA2100_vector_types.h 127
    ('x', c_short),
    ('y', c_short),
    ('z', c_short),
]
# ./my_CUDA2100_vector_types.h 133
class ushort3(Structure):
    pass
ushort3._fields_ = [
    # ./my_CUDA2100_vector_types.h 133
    ('x', c_ushort),
    ('y', c_ushort),
    ('z', c_ushort),
]
# ./my_CUDA2100_vector_types.h 139
class short4(Structure):
    pass
short4._fields_ = [
    # ./my_CUDA2100_vector_types.h 139
    ('x', c_short),
    ('y', c_short),
    ('z', c_short),
    ('w', c_short),
]
# ./my_CUDA2100_vector_types.h 145
class ushort4(Structure):
    pass
ushort4._fields_ = [
    # ./my_CUDA2100_vector_types.h 145
    ('x', c_ushort),
    ('y', c_ushort),
    ('z', c_ushort),
    ('w', c_ushort),
]
# ./my_CUDA2100_vector_types.h 151
class int1(Structure):
    pass
int1._fields_ = [
    # ./my_CUDA2100_vector_types.h 151
    ('x', c_int),
]
# ./my_CUDA2100_vector_types.h 157
class uint1(Structure):
    pass
uint1._fields_ = [
    # ./my_CUDA2100_vector_types.h 157
    ('x', c_uint),
]
# ./my_CUDA2100_vector_types.h 163
class int2(Structure):
    pass
int2._fields_ = [
    # ./my_CUDA2100_vector_types.h 163
    ('x', c_int),
    ('y', c_int),
]
# ./my_CUDA2100_vector_types.h 169
class uint2(Structure):
    pass
uint2._fields_ = [
    # ./my_CUDA2100_vector_types.h 169
    ('x', c_uint),
    ('y', c_uint),
]
# ./my_CUDA2100_vector_types.h 175
class int3(Structure):
    pass
int3._fields_ = [
    # ./my_CUDA2100_vector_types.h 175
    ('x', c_int),
    ('y', c_int),
    ('z', c_int),
]
# ./my_CUDA2100_vector_types.h 181
class uint3(Structure):
    pass
uint3._fields_ = [
    # ./my_CUDA2100_vector_types.h 181
    ('x', c_uint),
    ('y', c_uint),
    ('z', c_uint),
]
# ./my_CUDA2100_vector_types.h 187
class int4(Structure):
    pass
int4._fields_ = [
    # ./my_CUDA2100_vector_types.h 187
    ('x', c_int),
    ('y', c_int),
    ('z', c_int),
    ('w', c_int),
]
# ./my_CUDA2100_vector_types.h 193
class uint4(Structure):
    pass
uint4._fields_ = [
    # ./my_CUDA2100_vector_types.h 193
    ('x', c_uint),
    ('y', c_uint),
    ('z', c_uint),
    ('w', c_uint),
]
# ./my_CUDA2100_vector_types.h 199
class long1(Structure):
    pass
long1._fields_ = [
    # ./my_CUDA2100_vector_types.h 199
    ('x', c_long),
]
# ./my_CUDA2100_vector_types.h 205
class ulong1(Structure):
    pass
ulong1._fields_ = [
    # ./my_CUDA2100_vector_types.h 205
    ('x', c_ulong),
]
# ./my_CUDA2100_vector_types.h 217
class long2(Structure):
    pass
long2._fields_ = [
    # ./my_CUDA2100_vector_types.h 217
    ('x', c_long),
    ('y', c_long),
]
# ./my_CUDA2100_vector_types.h 229
class ulong2(Structure):
    pass
ulong2._fields_ = [
    # ./my_CUDA2100_vector_types.h 229
    ('x', c_ulong),
    ('y', c_ulong),
]
# ./my_CUDA2100_vector_types.h 263
class float1(Structure):
    pass
float1._fields_ = [
    # ./my_CUDA2100_vector_types.h 263
    ('x', c_float),
]
# ./my_CUDA2100_vector_types.h 269
class float2(Structure):
    pass
float2._fields_ = [
    # ./my_CUDA2100_vector_types.h 269
    ('x', c_float),
    ('y', c_float),
]
# ./my_CUDA2100_vector_types.h 275
class float3(Structure):
    pass
float3._fields_ = [
    # ./my_CUDA2100_vector_types.h 275
    ('x', c_float),
    ('y', c_float),
    ('z', c_float),
]
# ./my_CUDA2100_vector_types.h 281
class float4(Structure):
    pass
float4._fields_ = [
    # ./my_CUDA2100_vector_types.h 281
    ('x', c_float),
    ('y', c_float),
    ('z', c_float),
    ('w', c_float),
]
# ./my_CUDA2100_vector_types.h 287
class longlong1(Structure):
    pass
longlong1._fields_ = [
    # ./my_CUDA2100_vector_types.h 287
    ('x', c_longlong),
]
# ./my_CUDA2100_vector_types.h 293
class ulonglong1(Structure):
    pass
ulonglong1._fields_ = [
    # ./my_CUDA2100_vector_types.h 293
    ('x', c_ulonglong),
]
# ./my_CUDA2100_vector_types.h 299
class longlong2(Structure):
    pass
longlong2._fields_ = [
    # ./my_CUDA2100_vector_types.h 299
    ('x', c_longlong),
    ('y', c_longlong),
]
# ./my_CUDA2100_vector_types.h 305
class ulonglong2(Structure):
    pass
ulonglong2._fields_ = [
    # ./my_CUDA2100_vector_types.h 305
    ('x', c_ulonglong),
    ('y', c_ulonglong),
]
# ./my_CUDA2100_vector_types.h 311
class double1(Structure):
    pass
double1._fields_ = [
    # ./my_CUDA2100_vector_types.h 311
    ('x', c_double),
]
# ./my_CUDA2100_vector_types.h 317
class double2(Structure):
    pass
double2._fields_ = [
    # ./my_CUDA2100_vector_types.h 317
    ('x', c_double),
    ('y', c_double),
]
# ./my_CUDA2100_vector_types.h 384
class long3(Structure):
    pass
long3._fields_ = [
    # ./my_CUDA2100_vector_types.h 384
]
# ./my_CUDA2100_vector_types.h 386
class ulong3(Structure):
    pass
ulong3._fields_ = [
    # ./my_CUDA2100_vector_types.h 386
]
# ./my_CUDA2100_vector_types.h 388
class long4(Structure):
    pass
long4._fields_ = [
    # ./my_CUDA2100_vector_types.h 388
]
# ./my_CUDA2100_vector_types.h 390
class ulong4(Structure):
    pass
ulong4._fields_ = [
    # ./my_CUDA2100_vector_types.h 390
]
# ./my_CUDA2100_vector_types.h 423
class dim3(Structure):
    pass
dim3._fields_ = [
    # ./my_CUDA2100_vector_types.h 423
    ('x', c_uint),
    ('y', c_uint),
    ('z', c_uint),
]
cuFloatComplex = float2
cuDoubleComplex = double2
cuComplex = cuFloatComplex
cublasStatus = c_uint
# /usr/local/cuda/include/cublas.h 124
cublasInit = _libraries['cublas'].cublasInit
cublasInit.restype = cublasStatus
# cublasInit()
cublasInit.argtypes = []
cublasInit.__doc__ = \
"""cublasStatus cublasInit()
/usr/local/cuda/include/cublas.h:124"""
# /usr/local/cuda/include/cublas.h 138
cublasShutdown = _libraries['cublas'].cublasShutdown
cublasShutdown.restype = cublasStatus
# cublasShutdown()
cublasShutdown.argtypes = []
cublasShutdown.__doc__ = \
"""cublasStatus cublasShutdown()
/usr/local/cuda/include/cublas.h:138"""
# /usr/local/cuda/include/cublas.h 152
cublasGetError = _libraries['cublas'].cublasGetError
cublasGetError.restype = cublasStatus
# cublasGetError()
cublasGetError.argtypes = []
cublasGetError.__doc__ = \
"""cublasStatus cublasGetError()
/usr/local/cuda/include/cublas.h:152"""
# /usr/local/cuda/include/cublas.h 172
cublasAlloc = _libraries['cublas'].cublasAlloc
cublasAlloc.restype = cublasStatus
# cublasAlloc(n, elemSize, devicePtr)
cublasAlloc.argtypes = [c_int, c_int, POINTER(c_void_p)]
cublasAlloc.__doc__ = \
"""cublasStatus cublasAlloc(int n, int elemSize, void * * devicePtr)
/usr/local/cuda/include/cublas.h:172"""
# /usr/local/cuda/include/cublas.h 186
cublasFree = _libraries['cublas'].cublasFree
cublasFree.restype = cublasStatus
# cublasFree(devicePtr)
cublasFree.argtypes = [c_void_p]
cublasFree.__doc__ = \
"""cublasStatus cublasFree(unknown * devicePtr)
/usr/local/cuda/include/cublas.h:186"""
# /usr/local/cuda/include/cublas.h 212
cublasSetVector = _libraries['cublas'].cublasSetVector
cublasSetVector.restype = cublasStatus
# cublasSetVector(n, elemSize, x, incx, devicePtr, incy)
cublasSetVector.argtypes = [c_int, c_int, c_void_p, c_int, c_void_p, c_int]
cublasSetVector.__doc__ = \
"""cublasStatus cublasSetVector(int n, int elemSize, unknown * x, int incx, void * devicePtr, int incy)
/usr/local/cuda/include/cublas.h:212"""
# /usr/local/cuda/include/cublas.h 238
cublasGetVector = _libraries['cublas'].cublasGetVector
cublasGetVector.restype = cublasStatus
# cublasGetVector(n, elemSize, x, incx, y, incy)
cublasGetVector.argtypes = [c_int, c_int, c_void_p, c_int, c_void_p, c_int]
cublasGetVector.__doc__ = \
"""cublasStatus cublasGetVector(int n, int elemSize, unknown * x, int incx, void * y, int incy)
/usr/local/cuda/include/cublas.h:238"""
# /usr/local/cuda/include/cublas.h 263
cublasSetMatrix = _libraries['cublas'].cublasSetMatrix
cublasSetMatrix.restype = cublasStatus
# cublasSetMatrix(rows, cols, elemSize, A, lda, B, ldb)
cublasSetMatrix.argtypes = [c_int, c_int, c_int, c_void_p, c_int, c_void_p, c_int]
cublasSetMatrix.__doc__ = \
"""cublasStatus cublasSetMatrix(int rows, int cols, int elemSize, unknown * A, int lda, void * B, int ldb)
/usr/local/cuda/include/cublas.h:263"""
# /usr/local/cuda/include/cublas.h 287
cublasGetMatrix = _libraries['cublas'].cublasGetMatrix
cublasGetMatrix.restype = cublasStatus
# cublasGetMatrix(rows, cols, elemSize, A, lda, B, ldb)
cublasGetMatrix.argtypes = [c_int, c_int, c_int, c_void_p, c_int, c_void_p, c_int]
cublasGetMatrix.__doc__ = \
"""cublasStatus cublasGetMatrix(int rows, int cols, int elemSize, unknown * A, int lda, void * B, int ldb)
/usr/local/cuda/include/cublas.h:287"""
# /usr/local/cuda/include/cublas.h 319
cublasIsamax = _libraries['cublas'].cublasIsamax
cublasIsamax.restype = c_int
# cublasIsamax(n, x, incx)
cublasIsamax.argtypes = [c_int, POINTER(c_float), c_int]
cublasIsamax.__doc__ = \
"""int cublasIsamax(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:319"""
# /usr/local/cuda/include/cublas.h 348
cublasIsamin = _libraries['cublas'].cublasIsamin
cublasIsamin.restype = c_int
# cublasIsamin(n, x, incx)
cublasIsamin.argtypes = [c_int, POINTER(c_float), c_int]
cublasIsamin.__doc__ = \
"""int cublasIsamin(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:348"""
# /usr/local/cuda/include/cublas.h 378
cublasSasum = _libraries['cublas'].cublasSasum
cublasSasum.restype = c_float
# cublasSasum(n, x, incx)
cublasSasum.argtypes = [c_int, POINTER(c_float), c_int]
cublasSasum.__doc__ = \
"""float cublasSasum(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:378"""
# /usr/local/cuda/include/cublas.h 415
cublasSaxpy = _libraries['cublas'].cublasSaxpy
cublasSaxpy.restype = None
# cublasSaxpy(n, alpha, x, incx, y, incy)
cublasSaxpy.argtypes = [c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasSaxpy.__doc__ = \
"""void cublasSaxpy(int n, float alpha, unknown * x, int incx, float * y, int incy)
/usr/local/cuda/include/cublas.h:415"""
# /usr/local/cuda/include/cublas.h 448
cublasScopy = _libraries['cublas'].cublasScopy
cublasScopy.restype = None
# cublasScopy(n, x, incx, y, incy)
cublasScopy.argtypes = [c_int, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasScopy.__doc__ = \
"""void cublasScopy(int n, unknown * x, int incx, float * y, int incy)
/usr/local/cuda/include/cublas.h:448"""
# /usr/local/cuda/include/cublas.h 482
cublasSdot = _libraries['cublas'].cublasSdot
cublasSdot.restype = c_float
# cublasSdot(n, x, incx, y, incy)
cublasSdot.argtypes = [c_int, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasSdot.__doc__ = \
"""float cublasSdot(int n, unknown * x, int incx, unknown * y, int incy)
/usr/local/cuda/include/cublas.h:482"""
# /usr/local/cuda/include/cublas.h 512
cublasSnrm2 = _libraries['cublas'].cublasSnrm2
cublasSnrm2.restype = c_float
# cublasSnrm2(n, x, incx)
cublasSnrm2.argtypes = [c_int, POINTER(c_float), c_int]
cublasSnrm2.__doc__ = \
"""float cublasSnrm2(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:512"""
# /usr/local/cuda/include/cublas.h 551
cublasSrot = _libraries['cublas'].cublasSrot
cublasSrot.restype = None
# cublasSrot(n, x, incx, y, incy, sc, ss)
cublasSrot.argtypes = [c_int, POINTER(c_float), c_int, POINTER(c_float), c_int, c_float, c_float]
cublasSrot.__doc__ = \
"""void cublasSrot(int n, float * x, int incx, float * y, int incy, float sc, float ss)
/usr/local/cuda/include/cublas.h:551"""
# /usr/local/cuda/include/cublas.h 592
cublasSrotg = _libraries['cublas'].cublasSrotg
cublasSrotg.restype = None
# cublasSrotg(sa, sb, sc, ss)
cublasSrotg.argtypes = [POINTER(c_float), POINTER(c_float), POINTER(c_float), POINTER(c_float)]
cublasSrotg.__doc__ = \
"""void cublasSrotg(float * sa, float * sb, float * sc, float * ss)
/usr/local/cuda/include/cublas.h:592"""
# /usr/local/cuda/include/cublas.h 641
cublasSrotm = _libraries['cublas'].cublasSrotm
cublasSrotm.restype = None
# cublasSrotm(n, x, incx, y, incy, sparam)
cublasSrotm.argtypes = [c_int, POINTER(c_float), c_int, POINTER(c_float), c_int, POINTER(c_float)]
cublasSrotm.__doc__ = \
"""void cublasSrotm(int n, float * x, int incx, float * y, int incy, unknown * sparam)
/usr/local/cuda/include/cublas.h:641"""
# /usr/local/cuda/include/cublas.h 684
cublasSrotmg = _libraries['cublas'].cublasSrotmg
cublasSrotmg.restype = None
# cublasSrotmg(sd1, sd2, sx1, sy1, sparam)
cublasSrotmg.argtypes = [POINTER(c_float), POINTER(c_float), POINTER(c_float), POINTER(c_float), POINTER(c_float)]
cublasSrotmg.__doc__ = \
"""void cublasSrotmg(float * sd1, float * sd2, float * sx1, unknown * sy1, float * sparam)
/usr/local/cuda/include/cublas.h:684"""
# /usr/local/cuda/include/cublas.h 714
cublasSscal = _libraries['cublas'].cublasSscal
cublasSscal.restype = None
# cublasSscal(n, alpha, x, incx)
cublasSscal.argtypes = [c_int, c_float, POINTER(c_float), c_int]
cublasSscal.__doc__ = \
"""void cublasSscal(int n, float alpha, float * x, int incx)
/usr/local/cuda/include/cublas.h:714"""
# /usr/local/cuda/include/cublas.h 744
cublasSswap = _libraries['cublas'].cublasSswap
cublasSswap.restype = None
# cublasSswap(n, x, incx, y, incy)
cublasSswap.argtypes = [c_int, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasSswap.__doc__ = \
"""void cublasSswap(int n, float * x, int incx, float * y, int incy)
/usr/local/cuda/include/cublas.h:744"""
# /usr/local/cuda/include/cublas.h 783
cublasCaxpy = _libraries['cublas'].cublasCaxpy
cublasCaxpy.restype = None
# cublasCaxpy(n, alpha, x, incx, y, incy)
cublasCaxpy.argtypes = [c_int, cuComplex, POINTER(cuComplex), c_int, POINTER(cuComplex), c_int]
cublasCaxpy.__doc__ = \
"""void cublasCaxpy(int n, cuComplex alpha, unknown * x, int incx, cuComplex * y, int incy)
/usr/local/cuda/include/cublas.h:783"""
# /usr/local/cuda/include/cublas.h 816
cublasCcopy = _libraries['cublas'].cublasCcopy
cublasCcopy.restype = None
# cublasCcopy(n, x, incx, y, incy)
cublasCcopy.argtypes = [c_int, POINTER(cuComplex), c_int, POINTER(cuComplex), c_int]
cublasCcopy.__doc__ = \
"""void cublasCcopy(int n, unknown * x, int incx, cuComplex * y, int incy)
/usr/local/cuda/include/cublas.h:816"""
# /usr/local/cuda/include/cublas.h 846
cublasCscal = _libraries['cublas'].cublasCscal
cublasCscal.restype = None
# cublasCscal(n, alpha, x, incx)
cublasCscal.argtypes = [c_int, cuComplex, POINTER(cuComplex), c_int]
cublasCscal.__doc__ = \
"""void cublasCscal(int n, cuComplex alpha, cuComplex * x, int incx)
/usr/local/cuda/include/cublas.h:846"""
# /usr/local/cuda/include/cublas.h 880
cublasCrotg = _libraries['cublas'].cublasCrotg
cublasCrotg.restype = None
# cublasCrotg(pca, cb, psc, pcs)
cublasCrotg.argtypes = [POINTER(cuComplex), cuComplex, POINTER(c_float), POINTER(cuComplex)]
cublasCrotg.__doc__ = \
"""void cublasCrotg(cuComplex * pca, cuComplex cb, float * psc, cuComplex * pcs)
/usr/local/cuda/include/cublas.h:880"""
# /usr/local/cuda/include/cublas.h 919
cublasCrot = _libraries['cublas'].cublasCrot
cublasCrot.restype = None
# cublasCrot(n, x, incx, y, incy, c, s)
cublasCrot.argtypes = [c_int, POINTER(cuComplex), c_int, POINTER(cuComplex), c_int, c_float, cuComplex]
cublasCrot.__doc__ = \
"""void cublasCrot(int n, cuComplex * x, int incx, cuComplex * y, int incy, float c, cuComplex s)
/usr/local/cuda/include/cublas.h:919"""
# /usr/local/cuda/include/cublas.h 958
cublasCsrot = _libraries['cublas'].cublasCsrot
cublasCsrot.restype = None
# cublasCsrot(n, x, incx, y, incy, c, s)
cublasCsrot.argtypes = [c_int, POINTER(cuComplex), c_int, POINTER(cuComplex), c_int, c_float, c_float]
cublasCsrot.__doc__ = \
"""void cublasCsrot(int n, cuComplex * x, int incx, cuComplex * y, int incy, float c, float s)
/usr/local/cuda/include/cublas.h:958"""
# /usr/local/cuda/include/cublas.h 988
cublasCsscal = _libraries['cublas'].cublasCsscal
cublasCsscal.restype = None
# cublasCsscal(n, alpha, x, incx)
cublasCsscal.argtypes = [c_int, c_float, POINTER(cuComplex), c_int]
cublasCsscal.__doc__ = \
"""void cublasCsscal(int n, float alpha, cuComplex * x, int incx)
/usr/local/cuda/include/cublas.h:988"""
# /usr/local/cuda/include/cublas.h 1022
cublasCswap = _libraries['cublas'].cublasCswap
cublasCswap.restype = None
# cublasCswap(n, x, incx, y, incy)
cublasCswap.argtypes = [c_int, POINTER(cuComplex), c_int, POINTER(cuComplex), c_int]
cublasCswap.__doc__ = \
"""void cublasCswap(int n, cuComplex * x, int incx, cuComplex * y, int incy)
/usr/local/cuda/include/cublas.h:1022"""
# /usr/local/cuda/include/cublas.h 1056
cublasCdotu = _libraries['cublas'].cublasCdotu
cublasCdotu.restype = cuComplex
# cublasCdotu(n, x, incx, y, incy)
cublasCdotu.argtypes = [c_int, POINTER(cuComplex), c_int, POINTER(cuComplex), c_int]
cublasCdotu.__doc__ = \
"""cuComplex cublasCdotu(int n, unknown * x, int incx, unknown * y, int incy)
/usr/local/cuda/include/cublas.h:1056"""
# /usr/local/cuda/include/cublas.h 1091
cublasCdotc = _libraries['cublas'].cublasCdotc
cublasCdotc.restype = cuComplex
# cublasCdotc(n, x, incx, y, incy)
cublasCdotc.argtypes = [c_int, POINTER(cuComplex), c_int, POINTER(cuComplex), c_int]
cublasCdotc.__doc__ = \
"""cuComplex cublasCdotc(int n, unknown * x, int incx, unknown * y, int incy)
/usr/local/cuda/include/cublas.h:1091"""
# /usr/local/cuda/include/cublas.h 1120
cublasIcamax = _libraries['cublas'].cublasIcamax
cublasIcamax.restype = c_int
# cublasIcamax(n, x, incx)
cublasIcamax.argtypes = [c_int, POINTER(cuComplex), c_int]
cublasIcamax.__doc__ = \
"""int cublasIcamax(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:1120"""
# /usr/local/cuda/include/cublas.h 1149
cublasIcamin = _libraries['cublas'].cublasIcamin
cublasIcamin.restype = c_int
# cublasIcamin(n, x, incx)
cublasIcamin.argtypes = [c_int, POINTER(cuComplex), c_int]
cublasIcamin.__doc__ = \
"""int cublasIcamin(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:1149"""
# /usr/local/cuda/include/cublas.h 1180
cublasScasum = _libraries['cublas'].cublasScasum
cublasScasum.restype = c_float
# cublasScasum(n, x, incx)
cublasScasum.argtypes = [c_int, POINTER(cuComplex), c_int]
cublasScasum.__doc__ = \
"""float cublasScasum(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:1180"""
# /usr/local/cuda/include/cublas.h 1208
cublasScnrm2 = _libraries['cublas'].cublasScnrm2
cublasScnrm2.restype = c_float
# cublasScnrm2(n, x, incx)
cublasScnrm2.argtypes = [c_int, POINTER(cuComplex), c_int]
cublasScnrm2.__doc__ = \
"""float cublasScnrm2(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:1208"""
# /usr/local/cuda/include/cublas.h 1275
cublasSgbmv = _libraries['cublas'].cublasSgbmv
cublasSgbmv.restype = None
# cublasSgbmv(trans, m, n, kl, ku, alpha, A, lda, x, incx, beta, y, incy)
cublasSgbmv.argtypes = [c_char, c_int, c_int, c_int, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int, c_float, POINTER(c_float), c_int]
cublasSgbmv.__doc__ = \
"""void cublasSgbmv(char trans, int m, int n, int kl, int ku, float alpha, unknown * A, int lda, unknown * x, int incx, float beta, float * y, int incy)
/usr/local/cuda/include/cublas.h:1275"""
# /usr/local/cuda/include/cublas.h 1336
cublasSgemv = _libraries['cublas'].cublasSgemv
cublasSgemv.restype = None
# cublasSgemv(trans, m, n, alpha, A, lda, x, incx, beta, y, incy)
cublasSgemv.argtypes = [c_char, c_int, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int, c_float, POINTER(c_float), c_int]
cublasSgemv.__doc__ = \
"""void cublasSgemv(char trans, int m, int n, float alpha, unknown * A, int lda, unknown * x, int incx, float beta, float * y, int incy)
/usr/local/cuda/include/cublas.h:1336"""
# /usr/local/cuda/include/cublas.h 1383
cublasSger = _libraries['cublas'].cublasSger
cublasSger.restype = None
# cublasSger(m, n, alpha, x, incx, y, incy, A, lda)
cublasSger.argtypes = [c_int, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasSger.__doc__ = \
"""void cublasSger(int m, int n, float alpha, unknown * x, int incx, unknown * y, int incy, float * A, int lda)
/usr/local/cuda/include/cublas.h:1383"""
# /usr/local/cuda/include/cublas.h 1448
cublasSsbmv = _libraries['cublas'].cublasSsbmv
cublasSsbmv.restype = None
# cublasSsbmv(uplo, n, k, alpha, A, lda, x, incx, beta, y, incy)
cublasSsbmv.argtypes = [c_char, c_int, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int, c_float, POINTER(c_float), c_int]
cublasSsbmv.__doc__ = \
"""void cublasSsbmv(char uplo, int n, int k, float alpha, unknown * A, int lda, unknown * x, int incx, float beta, float * y, int incy)
/usr/local/cuda/include/cublas.h:1448"""
# /usr/local/cuda/include/cublas.h 1501
cublasSspmv = _libraries['cublas'].cublasSspmv
cublasSspmv.restype = None
# cublasSspmv(uplo, n, alpha, AP, x, incx, beta, y, incy)
cublasSspmv.argtypes = [c_char, c_int, c_float, POINTER(c_float), POINTER(c_float), c_int, c_float, POINTER(c_float), c_int]
cublasSspmv.__doc__ = \
"""void cublasSspmv(char uplo, int n, float alpha, unknown * AP, unknown * x, int incx, float beta, float * y, int incy)
/usr/local/cuda/include/cublas.h:1501"""
# /usr/local/cuda/include/cublas.h 1550
cublasSspr = _libraries['cublas'].cublasSspr
cublasSspr.restype = None
# cublasSspr(uplo, n, alpha, x, incx, AP)
cublasSspr.argtypes = [c_char, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float)]
cublasSspr.__doc__ = \
"""void cublasSspr(char uplo, int n, float alpha, unknown * x, int incx, float * AP)
/usr/local/cuda/include/cublas.h:1550"""
# /usr/local/cuda/include/cublas.h 1604
cublasSspr2 = _libraries['cublas'].cublasSspr2
cublasSspr2.restype = None
# cublasSspr2(uplo, n, alpha, x, incx, y, incy, AP)
cublasSspr2.argtypes = [c_char, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int, POINTER(c_float)]
cublasSspr2.__doc__ = \
"""void cublasSspr2(char uplo, int n, float alpha, unknown * x, int incx, unknown * y, int incy, float * AP)
/usr/local/cuda/include/cublas.h:1604"""
# /usr/local/cuda/include/cublas.h 1664
cublasSsymv = _libraries['cublas'].cublasSsymv
cublasSsymv.restype = None
# cublasSsymv(uplo, n, alpha, A, lda, x, incx, beta, y, incy)
cublasSsymv.argtypes = [c_char, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int, c_float, POINTER(c_float), c_int]
cublasSsymv.__doc__ = \
"""void cublasSsymv(char uplo, int n, float alpha, unknown * A, int lda, unknown * x, int incx, float beta, float * y, int incy)
/usr/local/cuda/include/cublas.h:1664"""
# /usr/local/cuda/include/cublas.h 1718
cublasSsyr = _libraries['cublas'].cublasSsyr
cublasSsyr.restype = None
# cublasSsyr(uplo, n, alpha, x, incx, A, lda)
cublasSsyr.argtypes = [c_char, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasSsyr.__doc__ = \
"""void cublasSsyr(char uplo, int n, float alpha, unknown * x, int incx, float * A, int lda)
/usr/local/cuda/include/cublas.h:1718"""
# /usr/local/cuda/include/cublas.h 1772
cublasSsyr2 = _libraries['cublas'].cublasSsyr2
cublasSsyr2.restype = None
# cublasSsyr2(uplo, n, alpha, x, incx, y, incy, A, lda)
cublasSsyr2.argtypes = [c_char, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasSsyr2.__doc__ = \
"""void cublasSsyr2(char uplo, int n, float alpha, unknown * x, int incx, unknown * y, int incy, float * A, int lda)
/usr/local/cuda/include/cublas.h:1772"""
# /usr/local/cuda/include/cublas.h 1832
cublasStbmv = _libraries['cublas'].cublasStbmv
cublasStbmv.restype = None
# cublasStbmv(uplo, trans, diag, n, k, A, lda, x, incx)
cublasStbmv.argtypes = [c_char, c_char, c_char, c_int, c_int, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasStbmv.__doc__ = \
"""void cublasStbmv(char uplo, char trans, char diag, int n, int k, unknown * A, int lda, float * x, int incx)
/usr/local/cuda/include/cublas.h:1832"""
# /usr/local/cuda/include/cublas.h 1893
cublasStbsv = _libraries['cublas'].cublasStbsv
cublasStbsv.restype = None
# cublasStbsv(uplo, trans, diag, n, k, A, lda, x, incx)
cublasStbsv.argtypes = [c_char, c_char, c_char, c_int, c_int, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasStbsv.__doc__ = \
"""void cublasStbsv(char uplo, char trans, char diag, int n, int k, unknown * A, int lda, float * x, int incx)
/usr/local/cuda/include/cublas.h:1893"""
# /usr/local/cuda/include/cublas.h 1945
cublasStpmv = _libraries['cublas'].cublasStpmv
cublasStpmv.restype = None
# cublasStpmv(uplo, trans, diag, n, AP, x, incx)
cublasStpmv.argtypes = [c_char, c_char, c_char, c_int, POINTER(c_float), POINTER(c_float), c_int]
cublasStpmv.__doc__ = \
"""void cublasStpmv(char uplo, char trans, char diag, int n, unknown * AP, float * x, int incx)
/usr/local/cuda/include/cublas.h:1945"""
# /usr/local/cuda/include/cublas.h 1999
cublasStpsv = _libraries['cublas'].cublasStpsv
cublasStpsv.restype = None
# cublasStpsv(uplo, trans, diag, n, AP, x, incx)
cublasStpsv.argtypes = [c_char, c_char, c_char, c_int, POINTER(c_float), POINTER(c_float), c_int]
cublasStpsv.__doc__ = \
"""void cublasStpsv(char uplo, char trans, char diag, int n, unknown * AP, float * x, int incx)
/usr/local/cuda/include/cublas.h:1999"""
# /usr/local/cuda/include/cublas.h 2053
cublasStrmv = _libraries['cublas'].cublasStrmv
cublasStrmv.restype = None
# cublasStrmv(uplo, trans, diag, n, A, lda, x, incx)
cublasStrmv.argtypes = [c_char, c_char, c_char, c_int, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasStrmv.__doc__ = \
"""void cublasStrmv(char uplo, char trans, char diag, int n, unknown * A, int lda, float * x, int incx)
/usr/local/cuda/include/cublas.h:2053"""
# /usr/local/cuda/include/cublas.h 2113
cublasStrsv = _libraries['cublas'].cublasStrsv
cublasStrsv.restype = None
# cublasStrsv(uplo, trans, diag, n, A, lda, x, incx)
cublasStrsv.argtypes = [c_char, c_char, c_char, c_int, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasStrsv.__doc__ = \
"""void cublasStrsv(char uplo, char trans, char diag, int n, unknown * A, int lda, float * x, int incx)
/usr/local/cuda/include/cublas.h:2113"""
# /usr/local/cuda/include/cublas.h 2235
cublasSgemm = _libraries['cublas'].cublasSgemm
cublasSgemm.restype = None
# cublasSgemm(transa, transb, m, n, k, alpha, A, lda, B, ldb, beta, C, ldc)
cublasSgemm.argtypes = [c_char, c_char, c_int, c_int, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int, c_float, POINTER(c_float), c_int]
cublasSgemm.__doc__ = \
"""void cublasSgemm(char transa, char transb, int m, int n, int k, float alpha, unknown * A, int lda, unknown * B, int ldb, float beta, float * C, int ldc)
/usr/local/cuda/include/cublas.h:2235"""
# /usr/local/cuda/include/cublas.h 2316
cublasSsymm = _libraries['cublas'].cublasSsymm
cublasSsymm.restype = None
# cublasSsymm(side, uplo, m, n, alpha, A, lda, B, ldb, beta, C, ldc)
cublasSsymm.argtypes = [c_char, c_char, c_int, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int, c_float, POINTER(c_float), c_int]
cublasSsymm.__doc__ = \
"""void cublasSsymm(char side, char uplo, int m, int n, float alpha, unknown * A, int lda, unknown * B, int ldb, float beta, float * C, int ldc)
/usr/local/cuda/include/cublas.h:2316"""
# /usr/local/cuda/include/cublas.h 2393
cublasSsyrk = _libraries['cublas'].cublasSsyrk
cublasSsyrk.restype = None
# cublasSsyrk(uplo, trans, n, k, alpha, A, lda, beta, C, ldc)
cublasSsyrk.argtypes = [c_char, c_char, c_int, c_int, c_float, POINTER(c_float), c_int, c_float, POINTER(c_float), c_int]
cublasSsyrk.__doc__ = \
"""void cublasSsyrk(char uplo, char trans, int n, int k, float alpha, unknown * A, int lda, float beta, float * C, int ldc)
/usr/local/cuda/include/cublas.h:2393"""
# /usr/local/cuda/include/cublas.h 2478
cublasSsyr2k = _libraries['cublas'].cublasSsyr2k
cublasSsyr2k.restype = None
# cublasSsyr2k(uplo, trans, n, k, alpha, A, lda, B, ldb, beta, C, ldc)
cublasSsyr2k.argtypes = [c_char, c_char, c_int, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int, c_float, POINTER(c_float), c_int]
cublasSsyr2k.__doc__ = \
"""void cublasSsyr2k(char uplo, char trans, int n, int k, float alpha, unknown * A, int lda, unknown * B, int ldb, float beta, float * C, int ldc)
/usr/local/cuda/include/cublas.h:2478"""
# /usr/local/cuda/include/cublas.h 2551
cublasStrmm = _libraries['cublas'].cublasStrmm
cublasStrmm.restype = None
# cublasStrmm(side, uplo, transa, diag, m, n, alpha, A, lda, B, ldb)
cublasStrmm.argtypes = [c_char, c_char, c_char, c_char, c_int, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasStrmm.__doc__ = \
"""void cublasStrmm(char side, char uplo, char transa, char diag, int m, int n, float alpha, unknown * A, int lda, float * B, int ldb)
/usr/local/cuda/include/cublas.h:2551"""
# /usr/local/cuda/include/cublas.h 2629
cublasStrsm = _libraries['cublas'].cublasStrsm
cublasStrsm.restype = None
# cublasStrsm(side, uplo, transa, diag, m, n, alpha, A, lda, B, ldb)
cublasStrsm.argtypes = [c_char, c_char, c_char, c_char, c_int, c_int, c_float, POINTER(c_float), c_int, POINTER(c_float), c_int]
cublasStrsm.__doc__ = \
"""void cublasStrsm(char side, char uplo, char transa, char diag, int m, int n, float alpha, unknown * A, int lda, float * B, int ldb)
/usr/local/cuda/include/cublas.h:2629"""
# /usr/local/cuda/include/cublas.h 2696
cublasCgemm = _libraries['cublas'].cublasCgemm
cublasCgemm.restype = None
# cublasCgemm(transa, transb, m, n, k, alpha, A, lda, B, ldb, beta, C, ldc)
cublasCgemm.argtypes = [c_char, c_char, c_int, c_int, c_int, cuComplex, POINTER(cuComplex), c_int, POINTER(cuComplex), c_int, cuComplex, POINTER(cuComplex), c_int]
cublasCgemm.__doc__ = \
"""void cublasCgemm(char transa, char transb, int m, int n, int k, cuComplex alpha, unknown * A, int lda, unknown * B, int ldb, cuComplex beta, cuComplex * C, int ldc)
/usr/local/cuda/include/cublas.h:2696"""
# /usr/local/cuda/include/cublas.h 2726
cublasXerbla = _libraries['cublas'].cublasXerbla
cublasXerbla.restype = None
# cublasXerbla(srName, info)
cublasXerbla.argtypes = [STRING, c_int]
cublasXerbla.__doc__ = \
"""void cublasXerbla(unknown * srName, int info)
/usr/local/cuda/include/cublas.h:2726"""
# /usr/local/cuda/include/cublas.h 2759
cublasDasum = _libraries['cublas'].cublasDasum
cublasDasum.restype = c_double
# cublasDasum(n, x, incx)
cublasDasum.argtypes = [c_int, POINTER(c_double), c_int]
cublasDasum.__doc__ = \
"""double cublasDasum(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:2759"""
# /usr/local/cuda/include/cublas.h 2797
cublasDaxpy = _libraries['cublas'].cublasDaxpy
cublasDaxpy.restype = None
# cublasDaxpy(n, alpha, x, incx, y, incy)
cublasDaxpy.argtypes = [c_int, c_double, POINTER(c_double), c_int, POINTER(c_double), c_int]
cublasDaxpy.__doc__ = \
"""void cublasDaxpy(int n, double alpha, unknown * x, int incx, double * y, int incy)
/usr/local/cuda/include/cublas.h:2797"""
# /usr/local/cuda/include/cublas.h 2831
cublasDcopy = _libraries['cublas'].cublasDcopy
cublasDcopy.restype = None
# cublasDcopy(n, x, incx, y, incy)
cublasDcopy.argtypes = [c_int, POINTER(c_double), c_int, POINTER(c_double), c_int]
cublasDcopy.__doc__ = \
"""void cublasDcopy(int n, unknown * x, int incx, double * y, int incy)
/usr/local/cuda/include/cublas.h:2831"""
# /usr/local/cuda/include/cublas.h 2866
cublasDdot = _libraries['cublas'].cublasDdot
cublasDdot.restype = c_double
# cublasDdot(n, x, incx, y, incy)
cublasDdot.argtypes = [c_int, POINTER(c_double), c_int, POINTER(c_double), c_int]
cublasDdot.__doc__ = \
"""double cublasDdot(int n, unknown * x, int incx, unknown * y, int incy)
/usr/local/cuda/include/cublas.h:2866"""
# /usr/local/cuda/include/cublas.h 2897
cublasDnrm2 = _libraries['cublas'].cublasDnrm2
cublasDnrm2.restype = c_double
# cublasDnrm2(n, x, incx)
cublasDnrm2.argtypes = [c_int, POINTER(c_double), c_int]
cublasDnrm2.__doc__ = \
"""double cublasDnrm2(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:2897"""
# /usr/local/cuda/include/cublas.h 2937
cublasDrot = _libraries['cublas'].cublasDrot
cublasDrot.restype = None
# cublasDrot(n, x, incx, y, incy, sc, ss)
cublasDrot.argtypes = [c_int, POINTER(c_double), c_int, POINTER(c_double), c_int, c_double, c_double]
cublasDrot.__doc__ = \
"""void cublasDrot(int n, double * x, int incx, double * y, int incy, double sc, double ss)
/usr/local/cuda/include/cublas.h:2937"""
# /usr/local/cuda/include/cublas.h 2978
cublasDrotg = _libraries['cublas'].cublasDrotg
cublasDrotg.restype = None
# cublasDrotg(sa, sb, sc, ss)
cublasDrotg.argtypes = [POINTER(c_double), POINTER(c_double), POINTER(c_double), POINTER(c_double)]
cublasDrotg.__doc__ = \
"""void cublasDrotg(double * sa, double * sb, double * sc, double * ss)
/usr/local/cuda/include/cublas.h:2978"""
# /usr/local/cuda/include/cublas.h 3028
cublasDrotm = _libraries['cublas'].cublasDrotm
cublasDrotm.restype = None
# cublasDrotm(n, x, incx, y, incy, sparam)
cublasDrotm.argtypes = [c_int, POINTER(c_double), c_int, POINTER(c_double), c_int, POINTER(c_double)]
cublasDrotm.__doc__ = \
"""void cublasDrotm(int n, double * x, int incx, double * y, int incy, unknown * sparam)
/usr/local/cuda/include/cublas.h:3028"""
# /usr/local/cuda/include/cublas.h 3071
cublasDrotmg = _libraries['cublas'].cublasDrotmg
cublasDrotmg.restype = None
# cublasDrotmg(sd1, sd2, sx1, sy1, sparam)
cublasDrotmg.argtypes = [POINTER(c_double), POINTER(c_double), POINTER(c_double), POINTER(c_double), POINTER(c_double)]
cublasDrotmg.__doc__ = \
"""void cublasDrotmg(double * sd1, double * sd2, double * sx1, unknown * sy1, double * sparam)
/usr/local/cuda/include/cublas.h:3071"""
# /usr/local/cuda/include/cublas.h 3102
cublasDscal = _libraries['cublas'].cublasDscal
cublasDscal.restype = None
# cublasDscal(n, alpha, x, incx)
cublasDscal.argtypes = [c_int, c_double, POINTER(c_double), c_int]
cublasDscal.__doc__ = \
"""void cublasDscal(int n, double alpha, double * x, int incx)
/usr/local/cuda/include/cublas.h:3102"""
# /usr/local/cuda/include/cublas.h 3133
cublasDswap = _libraries['cublas'].cublasDswap
cublasDswap.restype = None
# cublasDswap(n, x, incx, y, incy)
cublasDswap.argtypes = [c_int, POINTER(c_double), c_int, POINTER(c_double), c_int]
cublasDswap.__doc__ = \
"""void cublasDswap(int n, double * x, int incx, double * y, int incy)
/usr/local/cuda/include/cublas.h:3133"""
# /usr/local/cuda/include/cublas.h 3163
cublasIdamax = _libraries['cublas'].cublasIdamax
cublasIdamax.restype = c_int
# cublasIdamax(n, x, incx)
cublasIdamax.argtypes = [c_int, POINTER(c_double), c_int]
cublasIdamax.__doc__ = \
"""int cublasIdamax(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:3163"""
# /usr/local/cuda/include/cublas.h 3193
cublasIdamin = _libraries['cublas'].cublasIdamin
cublasIdamin.restype = c_int
# cublasIdamin(n, x, incx)
cublasIdamin.argtypes = [c_int, POINTER(c_double), c_int]
cublasIdamin.__doc__ = \
"""int cublasIdamin(int n, unknown * x, int incx)
/usr/local/cuda/include/cublas.h:3193"""
# /usr/local/cuda/include/cublas.h 3259
cublasDgemv = _libraries['cublas'].cublasDgemv
cublasDgemv.restype = None
# cublasDgemv(trans, m, n, alpha, A, lda, x, incx, beta, y, incy)
cublasDgemv.argtypes = [c_char, c_int, c_int, c_double, POINTER(c_double), c_int, POINTER(c_double), c_int, c_double, POINTER(c_double), c_int]
cublasDgemv.__doc__ = \
"""void cublasDgemv(char trans, int m, int n, double alpha, unknown * A, int lda, unknown * x, int incx, double beta, double * y, int incy)
/usr/local/cuda/include/cublas.h:3259"""
# /usr/local/cuda/include/cublas.h 3308
cublasDger = _libraries['cublas'].cublasDger
cublasDger.restype = None
# cublasDger(m, n, alpha, x, incx, y, incy, A, lda)
cublasDger.argtypes = [c_int, c_int, c_double, POINTER(c_double), c_int, POINTER(c_double), c_int, POINTER(c_double), c_int]
cublasDger.__doc__ = \
"""void cublasDger(int m, int n, double alpha, unknown * x, int incx, unknown * y, int incy, double * A, int lda)
/usr/local/cuda/include/cublas.h:3308"""
# /usr/local/cuda/include/cublas.h 3364
cublasDsyr = _libraries['cublas'].cublasDsyr
cublasDsyr.restype = None
# cublasDsyr(uplo, n, alpha, x, incx, A, lda)
cublasDsyr.argtypes = [c_char, c_int, c_double, POINTER(c_double), c_int, POINTER(c_double), c_int]
cublasDsyr.__doc__ = \
"""void cublasDsyr(char uplo, int n, double alpha, unknown * x, int incx, double * A, int lda)
/usr/local/cuda/include/cublas.h:3364"""
# /usr/local/cuda/include/cublas.h 3426
cublasDtrsv = _libraries['cublas'].cublasDtrsv
cublasDtrsv.restype = None
# cublasDtrsv(uplo, trans, diag, n, A, lda, x, incx)
cublasDtrsv.argtypes = [c_char, c_char, c_char, c_int, POINTER(c_double), c_int, POINTER(c_double), c_int]
cublasDtrsv.__doc__ = \
"""void cublasDtrsv(char uplo, char trans, char diag, int n, unknown * A, int lda, double * x, int incx)
/usr/local/cuda/include/cublas.h:3426"""
# /usr/local/cuda/include/cublas.h 3497
cublasDgemm = _libraries['cublas'].cublasDgemm
cublasDgemm.restype = None
# cublasDgemm(transa, transb, m, n, k, alpha, A, lda, B, ldb, beta, C, ldc)
cublasDgemm.argtypes = [c_char, c_char, c_int, c_int, c_int, c_double, POINTER(c_double), c_int, POINTER(c_double), c_int, c_double, POINTER(c_double), c_int]
cublasDgemm.__doc__ = \
"""void cublasDgemm(char transa, char transb, int m, int n, int k, double alpha, unknown * A, int lda, unknown * B, int ldb, double beta, double * C, int ldc)
/usr/local/cuda/include/cublas.h:3497"""
# /usr/local/cuda/include/cublas.h 3577
cublasDtrsm = _libraries['cublas'].cublasDtrsm
cublasDtrsm.restype = None
# cublasDtrsm(side, uplo, transa, diag, m, n, alpha, A, lda, B, ldb)
cublasDtrsm.argtypes = [c_char, c_char, c_char, c_char, c_int, c_int, c_double, POINTER(c_double), c_int, POINTER(c_double), c_int]
cublasDtrsm.__doc__ = \
"""void cublasDtrsm(char side, char uplo, char transa, char diag, int m, int n, double alpha, unknown * A, int lda, double * B, int ldb)
/usr/local/cuda/include/cublas.h:3577"""
# /usr/local/cuda/include/cublas.h 3652
cublasDtrmm = _libraries['cublas'].cublasDtrmm
cublasDtrmm.restype = None
# cublasDtrmm(side, uplo, transa, diag, m, n, alpha, A, lda, B, ldb)
cublasDtrmm.argtypes = [c_char, c_char, c_char, c_char, c_int, c_int, c_double, POINTER(c_double), c_int, POINTER(c_double), c_int]
cublasDtrmm.__doc__ = \
"""void cublasDtrmm(char side, char uplo, char transa, char diag, int m, int n, double alpha, unknown * A, int lda, double * B, int ldb)
/usr/local/cuda/include/cublas.h:3652"""
# /usr/local/cuda/include/cublas.h 3735
cublasDsymm = _libraries['cublas'].cublasDsymm
cublasDsymm.restype = None
# cublasDsymm(side, uplo, m, n, alpha, A, lda, B, ldb, beta, C, ldc)
cublasDsymm.argtypes = [c_char, c_char, c_int, c_int, c_double, POINTER(c_double), c_int, POINTER(c_double), c_int, c_double, POINTER(c_double), c_int]
cublasDsymm.__doc__ = \
"""void cublasDsymm(char side, char uplo, int m, int n, double alpha, unknown * A, int lda, unknown * B, int ldb, double beta, double * C, int ldc)
/usr/local/cuda/include/cublas.h:3735"""
# /usr/local/cuda/include/cublas.h 3813
cublasDsyrk = _libraries['cublas'].cublasDsyrk
cublasDsyrk.restype = None
# cublasDsyrk(uplo, trans, n, k, alpha, A, lda, beta, C, ldc)
cublasDsyrk.argtypes = [c_char, c_char, c_int, c_int, c_double, POINTER(c_double), c_int, c_double, POINTER(c_double), c_int]
cublasDsyrk.__doc__ = \
"""void cublasDsyrk(char uplo, char trans, int n, int k, double alpha, unknown * A, int lda, double beta, double * C, int ldc)
/usr/local/cuda/include/cublas.h:3813"""
# /usr/local/cuda/include/cublas.h 3900
cublasDsyr2k = _libraries['cublas'].cublasDsyr2k
cublasDsyr2k.restype = None
# cublasDsyr2k(uplo, trans, n, k, alpha, A, lda, B, ldb, beta, C, ldc)
cublasDsyr2k.argtypes = [c_char, c_char, c_int, c_int, c_double, POINTER(c_double), c_int, POINTER(c_double), c_int, c_double, POINTER(c_double), c_int]
cublasDsyr2k.__doc__ = \
"""void cublasDsyr2k(char uplo, char trans, int n, int k, double alpha, unknown * A, int lda, unknown * B, int ldb, double beta, double * C, int ldc)
/usr/local/cuda/include/cublas.h:3900"""
# /usr/local/cuda/include/cublas.h 3968
cublasZgemm = _libraries['cublas'].cublasZgemm
cublasZgemm.restype = None
# cublasZgemm(transa, transb, m, n, k, alpha, A, lda, B, ldb, beta, C, ldc)
cublasZgemm.argtypes = [c_char, c_char, c_int, c_int, c_int, cuDoubleComplex, POINTER(cuDoubleComplex), c_int, POINTER(cuDoubleComplex), c_int, cuDoubleComplex, POINTER(cuDoubleComplex), c_int]
cublasZgemm.__doc__ = \
"""void cublasZgemm(char transa, char transb, int m, int n, int k, cuDoubleComplex alpha, unknown * A, int lda, unknown * B, int ldb, cuDoubleComplex beta, cuDoubleComplex * C, int ldc)
/usr/local/cuda/include/cublas.h:3968"""
__all__ = ['cublasDswap', 'cublasSrotmg', 'cublasSsymv', 'cublasInit',
           'cublasCaxpy', 'cublasGetError', 'cublasSspr',
           'cublasSsymm', 'cublasDrotmg', 'cublasStrsm', 'ushort1',
           'ushort2', 'ushort3', 'ushort4', 'cublasAlloc', 'double2',
           'double1', 'ulong3', 'ulong2', 'ulong1', 'cublasStpsv',
           'cublasIdamin', 'longlong2', 'cublasDdot',
           'cublasGetVector', 'cublasSaxpy', 'cublasSscal', 'uchar1',
           'uchar3', 'uchar2', 'uchar4', 'cublasCgemm',
           'cublasXerbla', 'cublasCrotg', 'cublasDrotm', 'float4',
           'cublasDrotg', 'float1', 'float2', 'float3', 'cublasSswap',
           'cublasDsyrk', 'cuComplex', 'cublasSsyr', 'cublasScopy',
           'cublasStbsv', 'cublasIsamin', 'cublasDtrsm', 'cublasSger',
           'cublasDtrsv', 'cublasDcopy', 'cublasSasum', 'cublasDgemv',
           'cublasSetMatrix', 'ulonglong1', 'cublasStrmm',
           'cublasDsymm', 'cublasStrmv', 'cublasDsyr', 'cublasIsamax',
           'short4', 'cublasDasum', 'short1', 'short2', 'short3',
           'cublasCscal', 'cublasStbmv', 'cublasScasum', 'cublasFree',
           'cublasStrsv', 'cublasSgbmv', 'cublasDrot',
           'cublasSetVector', 'cublasSsyrk', 'uint4', 'uint1',
           'cublasCrot', 'uint2', 'cublasDsyr2k', 'cublasDnrm2',
           'int4', 'cublasCswap', 'int1', 'cublasIcamin', 'int3',
           'int2', 'cublasDger', 'longlong1', 'ulong4',
           'cublasShutdown', 'cublasSsyr2', 'cublasCcopy',
           'cublasSgemm', 'cublasIdamax', 'cublasIcamax',
           'cublasSgemv', 'cublasSspmv', 'cublasCsscal',
           'cublasGetMatrix', 'cuFloatComplex', 'ulonglong2',
           'cublasSnrm2', 'cublasDaxpy', 'char1', 'char3', 'char2',
           'char4', 'dim3', 'cublasSrot', 'cublasCdotc', 'uint3',
           'cublasDscal', 'cuDoubleComplex', 'cublasSrotm',
           'cublasCdotu', 'cublasSrotg', 'cublasZgemm',
           'cublasScnrm2', 'long3', 'long2', 'long1', 'cublasDgemm',
           'long4', 'cublasSsbmv', 'cublasStpmv', 'cublasCsrot',
           'cublasSsyr2k', 'cublasSspr2', 'cublasStatus',
           'cublasSdot', 'cublasDtrmm']
