# generated by 'xml2py'
# flags 'cufft.xml -c -d -v -l cufft'
from ctypes import *
from cuda.utils import get_lib
c_longdouble = c_double

_libraries = {}
_libraries['cufft'] = get_lib('cufft')


CUFFT_ALLOC_FAILED = 2
CUFFT_SETUP_FAILED = 7
CUFFT_C2C = 41
CUFFT_INVALID_SIZE = 8
CUFFT_INVALID_VALUE = 4
CUFFT_SUCCESS = 0
CUFFT_INTERNAL_ERROR = 5
CUFFT_INVALID_PLAN = 1
CUFFT_R2C = 42
CUFFT_EXEC_FAILED = 6
CUFFT_C2R = 44
CUFFT_INVALID_TYPE = 3
# ./my_CUDA2100_vector_types.h 55
class char1(Structure):
    pass
char1._fields_ = [
    # ./my_CUDA2100_vector_types.h 55
    ('x', c_byte),
]
# ./my_CUDA2100_vector_types.h 61
class uchar1(Structure):
    pass
uchar1._fields_ = [
    # ./my_CUDA2100_vector_types.h 61
    ('x', c_ubyte),
]
# ./my_CUDA2100_vector_types.h 67
class char2(Structure):
    pass
char2._fields_ = [
    # ./my_CUDA2100_vector_types.h 67
    ('x', c_byte),
    ('y', c_byte),
]
# ./my_CUDA2100_vector_types.h 73
class uchar2(Structure):
    pass
uchar2._fields_ = [
    # ./my_CUDA2100_vector_types.h 73
    ('x', c_ubyte),
    ('y', c_ubyte),
]
# ./my_CUDA2100_vector_types.h 79
class char3(Structure):
    pass
char3._fields_ = [
    # ./my_CUDA2100_vector_types.h 79
    ('x', c_byte),
    ('y', c_byte),
    ('z', c_byte),
]
# ./my_CUDA2100_vector_types.h 85
class uchar3(Structure):
    pass
uchar3._fields_ = [
    # ./my_CUDA2100_vector_types.h 85
    ('x', c_ubyte),
    ('y', c_ubyte),
    ('z', c_ubyte),
]
# ./my_CUDA2100_vector_types.h 91
class char4(Structure):
    pass
char4._fields_ = [
    # ./my_CUDA2100_vector_types.h 91
    ('x', c_byte),
    ('y', c_byte),
    ('z', c_byte),
    ('w', c_byte),
]
# ./my_CUDA2100_vector_types.h 97
class uchar4(Structure):
    pass
uchar4._fields_ = [
    # ./my_CUDA2100_vector_types.h 97
    ('x', c_ubyte),
    ('y', c_ubyte),
    ('z', c_ubyte),
    ('w', c_ubyte),
]
# ./my_CUDA2100_vector_types.h 103
class short1(Structure):
    pass
short1._fields_ = [
    # ./my_CUDA2100_vector_types.h 103
    ('x', c_short),
]
# ./my_CUDA2100_vector_types.h 109
class ushort1(Structure):
    pass
ushort1._fields_ = [
    # ./my_CUDA2100_vector_types.h 109
    ('x', c_ushort),
]
# ./my_CUDA2100_vector_types.h 115
class short2(Structure):
    pass
short2._fields_ = [
    # ./my_CUDA2100_vector_types.h 115
    ('x', c_short),
    ('y', c_short),
]
# ./my_CUDA2100_vector_types.h 121
class ushort2(Structure):
    pass
ushort2._fields_ = [
    # ./my_CUDA2100_vector_types.h 121
    ('x', c_ushort),
    ('y', c_ushort),
]
# ./my_CUDA2100_vector_types.h 127
class short3(Structure):
    pass
short3._fields_ = [
    # ./my_CUDA2100_vector_types.h 127
    ('x', c_short),
    ('y', c_short),
    ('z', c_short),
]
# ./my_CUDA2100_vector_types.h 133
class ushort3(Structure):
    pass
ushort3._fields_ = [
    # ./my_CUDA2100_vector_types.h 133
    ('x', c_ushort),
    ('y', c_ushort),
    ('z', c_ushort),
]
# ./my_CUDA2100_vector_types.h 139
class short4(Structure):
    pass
short4._fields_ = [
    # ./my_CUDA2100_vector_types.h 139
    ('x', c_short),
    ('y', c_short),
    ('z', c_short),
    ('w', c_short),
]
# ./my_CUDA2100_vector_types.h 145
class ushort4(Structure):
    pass
ushort4._fields_ = [
    # ./my_CUDA2100_vector_types.h 145
    ('x', c_ushort),
    ('y', c_ushort),
    ('z', c_ushort),
    ('w', c_ushort),
]
# ./my_CUDA2100_vector_types.h 151
class int1(Structure):
    pass
int1._fields_ = [
    # ./my_CUDA2100_vector_types.h 151
    ('x', c_int),
]
# ./my_CUDA2100_vector_types.h 157
class uint1(Structure):
    pass
uint1._fields_ = [
    # ./my_CUDA2100_vector_types.h 157
    ('x', c_uint),
]
# ./my_CUDA2100_vector_types.h 163
class int2(Structure):
    pass
int2._fields_ = [
    # ./my_CUDA2100_vector_types.h 163
    ('x', c_int),
    ('y', c_int),
]
# ./my_CUDA2100_vector_types.h 169
class uint2(Structure):
    pass
uint2._fields_ = [
    # ./my_CUDA2100_vector_types.h 169
    ('x', c_uint),
    ('y', c_uint),
]
# ./my_CUDA2100_vector_types.h 175
class int3(Structure):
    pass
int3._fields_ = [
    # ./my_CUDA2100_vector_types.h 175
    ('x', c_int),
    ('y', c_int),
    ('z', c_int),
]
# ./my_CUDA2100_vector_types.h 181
class uint3(Structure):
    pass
uint3._fields_ = [
    # ./my_CUDA2100_vector_types.h 181
    ('x', c_uint),
    ('y', c_uint),
    ('z', c_uint),
]
# ./my_CUDA2100_vector_types.h 187
class int4(Structure):
    pass
int4._fields_ = [
    # ./my_CUDA2100_vector_types.h 187
    ('x', c_int),
    ('y', c_int),
    ('z', c_int),
    ('w', c_int),
]
# ./my_CUDA2100_vector_types.h 193
class uint4(Structure):
    pass
uint4._fields_ = [
    # ./my_CUDA2100_vector_types.h 193
    ('x', c_uint),
    ('y', c_uint),
    ('z', c_uint),
    ('w', c_uint),
]
# ./my_CUDA2100_vector_types.h 199
class long1(Structure):
    pass
long1._fields_ = [
    # ./my_CUDA2100_vector_types.h 199
    ('x', c_long),
]
# ./my_CUDA2100_vector_types.h 205
class ulong1(Structure):
    pass
ulong1._fields_ = [
    # ./my_CUDA2100_vector_types.h 205
    ('x', c_ulong),
]
# ./my_CUDA2100_vector_types.h 217
class long2(Structure):
    pass
long2._fields_ = [
    # ./my_CUDA2100_vector_types.h 217
    ('x', c_long),
    ('y', c_long),
]
# ./my_CUDA2100_vector_types.h 229
class ulong2(Structure):
    pass
ulong2._fields_ = [
    # ./my_CUDA2100_vector_types.h 229
    ('x', c_ulong),
    ('y', c_ulong),
]
# ./my_CUDA2100_vector_types.h 263
class float1(Structure):
    pass
float1._fields_ = [
    # ./my_CUDA2100_vector_types.h 263
    ('x', c_float),
]
# ./my_CUDA2100_vector_types.h 269
class float2(Structure):
    pass
float2._fields_ = [
    # ./my_CUDA2100_vector_types.h 269
    ('x', c_float),
    ('y', c_float),
]
# ./my_CUDA2100_vector_types.h 275
class float3(Structure):
    pass
float3._fields_ = [
    # ./my_CUDA2100_vector_types.h 275
    ('x', c_float),
    ('y', c_float),
    ('z', c_float),
]
# ./my_CUDA2100_vector_types.h 281
class float4(Structure):
    pass
float4._fields_ = [
    # ./my_CUDA2100_vector_types.h 281
    ('x', c_float),
    ('y', c_float),
    ('z', c_float),
    ('w', c_float),
]
# ./my_CUDA2100_vector_types.h 287
class longlong1(Structure):
    pass
longlong1._fields_ = [
    # ./my_CUDA2100_vector_types.h 287
    ('x', c_longlong),
]
# ./my_CUDA2100_vector_types.h 293
class ulonglong1(Structure):
    pass
ulonglong1._fields_ = [
    # ./my_CUDA2100_vector_types.h 293
    ('x', c_ulonglong),
]
# ./my_CUDA2100_vector_types.h 299
class longlong2(Structure):
    pass
longlong2._fields_ = [
    # ./my_CUDA2100_vector_types.h 299
    ('x', c_longlong),
    ('y', c_longlong),
]
# ./my_CUDA2100_vector_types.h 305
class ulonglong2(Structure):
    pass
ulonglong2._fields_ = [
    # ./my_CUDA2100_vector_types.h 305
    ('x', c_ulonglong),
    ('y', c_ulonglong),
]
# ./my_CUDA2100_vector_types.h 311
class double1(Structure):
    pass
double1._fields_ = [
    # ./my_CUDA2100_vector_types.h 311
    ('x', c_double),
]
# ./my_CUDA2100_vector_types.h 317
class double2(Structure):
    pass
double2._fields_ = [
    # ./my_CUDA2100_vector_types.h 317
    ('x', c_double),
    ('y', c_double),
]
# ./my_CUDA2100_vector_types.h 384
class long3(Structure):
    pass
long3._fields_ = [
    # ./my_CUDA2100_vector_types.h 384
]
# ./my_CUDA2100_vector_types.h 386
class ulong3(Structure):
    pass
ulong3._fields_ = [
    # ./my_CUDA2100_vector_types.h 386
]
# ./my_CUDA2100_vector_types.h 388
class long4(Structure):
    pass
long4._fields_ = [
    # ./my_CUDA2100_vector_types.h 388
]
# ./my_CUDA2100_vector_types.h 390
class ulong4(Structure):
    pass
ulong4._fields_ = [
    # ./my_CUDA2100_vector_types.h 390
]
# ./my_CUDA2100_vector_types.h 423
class dim3(Structure):
    pass
dim3._fields_ = [
    # ./my_CUDA2100_vector_types.h 423
    ('x', c_uint),
    ('y', c_uint),
    ('z', c_uint),
]
cuFloatComplex = float2
cuDoubleComplex = double2
cuComplex = cuFloatComplex

# values for enumeration 'cufftResult_t'
cufftResult_t = c_int # enum
cufftResult = cufftResult_t
cufftHandle = c_uint
cufftReal = c_float
cufftComplex = cuComplex

# values for enumeration 'cufftType_t'
cufftType_t = c_int # enum
cufftType = cufftType_t
# /usr/local/cuda/include/cufft.h 103
cufftPlan1d = _libraries['cufft'].cufftPlan1d
cufftPlan1d.restype = cufftResult
# cufftPlan1d(plan, nx, type, batch)
cufftPlan1d.argtypes = [POINTER(cufftHandle), c_int, cufftType, c_int]
cufftPlan1d.__doc__ = \
"""cufftResult cufftPlan1d(cufftHandle * plan, int nx, cufftType type, int batch)
/usr/local/cuda/include/cufft.h:103"""
# /usr/local/cuda/include/cufft.h 107
cufftPlan2d = _libraries['cufft'].cufftPlan2d
cufftPlan2d.restype = cufftResult
# cufftPlan2d(plan, nx, ny, type)
cufftPlan2d.argtypes = [POINTER(cufftHandle), c_int, c_int, cufftType]
cufftPlan2d.__doc__ = \
"""cufftResult cufftPlan2d(cufftHandle * plan, int nx, int ny, cufftType type)
/usr/local/cuda/include/cufft.h:107"""
# /usr/local/cuda/include/cufft.h 111
cufftPlan3d = _libraries['cufft'].cufftPlan3d
cufftPlan3d.restype = cufftResult
# cufftPlan3d(plan, nx, ny, nz, type)
cufftPlan3d.argtypes = [POINTER(cufftHandle), c_int, c_int, c_int, cufftType]
cufftPlan3d.__doc__ = \
"""cufftResult cufftPlan3d(cufftHandle * plan, int nx, int ny, int nz, cufftType type)
/usr/local/cuda/include/cufft.h:111"""
# /usr/local/cuda/include/cufft.h 113
cufftDestroy = _libraries['cufft'].cufftDestroy
cufftDestroy.restype = cufftResult
# cufftDestroy(plan)
cufftDestroy.argtypes = [cufftHandle]
cufftDestroy.__doc__ = \
"""cufftResult cufftDestroy(cufftHandle plan)
/usr/local/cuda/include/cufft.h:113"""
# /usr/local/cuda/include/cufft.h 118
cufftExecC2C = _libraries['cufft'].cufftExecC2C
cufftExecC2C.restype = cufftResult
# cufftExecC2C(plan, idata, odata, direction)
cufftExecC2C.argtypes = [cufftHandle, POINTER(cufftComplex), POINTER(cufftComplex), c_int]
cufftExecC2C.__doc__ = \
"""cufftResult cufftExecC2C(cufftHandle plan, cufftComplex * idata, cufftComplex * odata, int direction)
/usr/local/cuda/include/cufft.h:118"""
# /usr/local/cuda/include/cufft.h 122
cufftExecR2C = _libraries['cufft'].cufftExecR2C
cufftExecR2C.restype = cufftResult
# cufftExecR2C(plan, idata, odata)
cufftExecR2C.argtypes = [cufftHandle, POINTER(cufftReal), POINTER(cufftComplex)]
cufftExecR2C.__doc__ = \
"""cufftResult cufftExecR2C(cufftHandle plan, cufftReal * idata, cufftComplex * odata)
/usr/local/cuda/include/cufft.h:122"""
# /usr/local/cuda/include/cufft.h 126
cufftExecC2R = _libraries['cufft'].cufftExecC2R
cufftExecC2R.restype = cufftResult
# cufftExecC2R(plan, idata, odata)
cufftExecC2R.argtypes = [cufftHandle, POINTER(cufftComplex), POINTER(cufftReal)]
cufftExecC2R.__doc__ = \
"""cufftResult cufftExecC2R(cufftHandle plan, cufftComplex * idata, cufftReal * odata)
/usr/local/cuda/include/cufft.h:126"""
__all__ = ['short4', 'CUFFT_EXEC_FAILED', 'short2', 'short3', 'char1',
           'char3', 'char2', 'char4', 'CUFFT_C2R',
           'CUFFT_INVALID_PLAN', 'double1', 'cufftExecC2R', 'float4',
           'cuFloatComplex', 'CUFFT_SETUP_FAILED', 'float1',
           'CUFFT_C2C', 'short1', 'cufftPlan2d',
           'CUFFT_INVALID_VALUE', 'cufftComplex',
           'CUFFT_INTERNAL_ERROR', 'cuComplex', 'cuDoubleComplex',
           'cufftHandle', 'ushort1', 'ushort2', 'ushort3', 'ushort4',
           'float2', 'cufftDestroy', 'double2', 'CUFFT_SUCCESS',
           'float3', 'ulong3', 'long1', 'ulong1', 'cufftExecC2C',
           'uint4', 'cufftPlan3d', 'uint1', 'uint3', 'uint2', 'long3',
           'long2', 'CUFFT_INVALID_SIZE', 'cufftReal',
           'CUFFT_ALLOC_FAILED', 'long4', 'ulong4', 'int4',
           'CUFFT_R2C', 'int1', 'int3', 'int2', 'cufftPlan1d',
           'cufftExecR2C', 'longlong1', 'longlong2', 'cufftType',
           'dim3', 'CUFFT_INVALID_TYPE', 'cufftResult_t',
           'cufftType_t', 'ulong2', 'uchar1', 'uchar3', 'uchar2',
           'cufftResult', 'uchar4', 'ulonglong1', 'ulonglong2']
