# generated by 'xml2py'
# flags 'cufft.xml -c -d -v -l /usr/local/cuda/lib/libcufft.dylib -o cufft.py'
from ctypes import *

_libraries = {}
_libraries['/usr/local/cuda/lib/libcufft.dylib'] = CDLL('/usr/local/cuda/lib/libcufft.dylib')
STRING = c_char_p


_FP_NORMAL = 4
_FP_NAN = 1
CUFFT_R2C = 42
_FP_INFINITE = 2
CUFFT_EXEC_FAILED = 6
CUFFT_SETUP_FAILED = 7
_FP_SUPERNORMAL = 6
CUFFT_INVALID_SIZE = 8
CUFFT_INVALID_PLAN = 1
CUFFT_INVALID_TYPE = 3
CUFFT_INVALID_VALUE = 4
_FP_ZERO = 3
CUFFT_C2R = 44
_FP_SUBNORMAL = 5
CUFFT_C2C = 41
CUFFT_INTERNAL_ERROR = 5
CUFFT_ALLOC_FAILED = 2
CUFFT_SUCCESS = 0
__darwin_nl_item = c_int
__darwin_wctrans_t = c_int
__darwin_wctype_t = c_ulong
float_t = c_float
double_t = c_double

# values for unnamed enumeration
# /usr/include/architecture/i386/math.h 117
__math_errhandling = _libraries['/usr/local/cuda/lib/libcufft.dylib'].__math_errhandling
__math_errhandling.restype = c_uint
# __math_errhandling()
__math_errhandling.argtypes = []
__math_errhandling.__doc__ = \
"""unsigned int __math_errhandling()
/usr/include/architecture/i386/math.h:117"""
# /usr/include/architecture/i386/math.h 137
__fpclassifyf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].__fpclassifyf
__fpclassifyf.restype = c_int
# __fpclassifyf(p1)
__fpclassifyf.argtypes = [c_float]
__fpclassifyf.__doc__ = \
"""int __fpclassifyf(float p1)
/usr/include/architecture/i386/math.h:137"""
# /usr/include/architecture/i386/math.h 138
__fpclassifyd = _libraries['/usr/local/cuda/lib/libcufft.dylib'].__fpclassifyd
__fpclassifyd.restype = c_int
# __fpclassifyd(p1)
__fpclassifyd.argtypes = [c_double]
__fpclassifyd.__doc__ = \
"""int __fpclassifyd(double p1)
/usr/include/architecture/i386/math.h:138"""
# /usr/include/architecture/i386/math.h 139
__fpclassify = _libraries['/usr/local/cuda/lib/libcufft.dylib'].__fpclassify
__fpclassify.restype = c_int
# __fpclassify(p1)
__fpclassify.argtypes = [c_longdouble]
__fpclassify.__doc__ = \
"""int __fpclassify(long double p1)
/usr/include/architecture/i386/math.h:139"""
# /usr/include/architecture/i386/math.h 262
acos = _libraries['/usr/local/cuda/lib/libcufft.dylib'].acos
acos.restype = c_double
# acos(p1)
acos.argtypes = [c_double]
acos.__doc__ = \
"""double acos(double p1)
/usr/include/architecture/i386/math.h:262"""
# /usr/include/architecture/i386/math.h 263
acosf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].acosf
acosf.restype = c_float
# acosf(p1)
acosf.argtypes = [c_float]
acosf.__doc__ = \
"""float acosf(float p1)
/usr/include/architecture/i386/math.h:263"""
# /usr/include/architecture/i386/math.h 265
asin = _libraries['/usr/local/cuda/lib/libcufft.dylib'].asin
asin.restype = c_double
# asin(p1)
asin.argtypes = [c_double]
asin.__doc__ = \
"""double asin(double p1)
/usr/include/architecture/i386/math.h:265"""
# /usr/include/architecture/i386/math.h 266
asinf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].asinf
asinf.restype = c_float
# asinf(p1)
asinf.argtypes = [c_float]
asinf.__doc__ = \
"""float asinf(float p1)
/usr/include/architecture/i386/math.h:266"""
# /usr/include/architecture/i386/math.h 268
atan = _libraries['/usr/local/cuda/lib/libcufft.dylib'].atan
atan.restype = c_double
# atan(p1)
atan.argtypes = [c_double]
atan.__doc__ = \
"""double atan(double p1)
/usr/include/architecture/i386/math.h:268"""
# /usr/include/architecture/i386/math.h 269
atanf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].atanf
atanf.restype = c_float
# atanf(p1)
atanf.argtypes = [c_float]
atanf.__doc__ = \
"""float atanf(float p1)
/usr/include/architecture/i386/math.h:269"""
# /usr/include/architecture/i386/math.h 271
atan2 = _libraries['/usr/local/cuda/lib/libcufft.dylib'].atan2
atan2.restype = c_double
# atan2(p1, p2)
atan2.argtypes = [c_double, c_double]
atan2.__doc__ = \
"""double atan2(double p1, double p2)
/usr/include/architecture/i386/math.h:271"""
# /usr/include/architecture/i386/math.h 272
atan2f = _libraries['/usr/local/cuda/lib/libcufft.dylib'].atan2f
atan2f.restype = c_float
# atan2f(p1, p2)
atan2f.argtypes = [c_float, c_float]
atan2f.__doc__ = \
"""float atan2f(float p1, float p2)
/usr/include/architecture/i386/math.h:272"""
# /usr/include/architecture/i386/math.h 274
cos = _libraries['/usr/local/cuda/lib/libcufft.dylib'].cos
cos.restype = c_double
# cos(p1)
cos.argtypes = [c_double]
cos.__doc__ = \
"""double cos(double p1)
/usr/include/architecture/i386/math.h:274"""
# /usr/include/architecture/i386/math.h 275
cosf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].cosf
cosf.restype = c_float
# cosf(p1)
cosf.argtypes = [c_float]
cosf.__doc__ = \
"""float cosf(float p1)
/usr/include/architecture/i386/math.h:275"""
# /usr/include/architecture/i386/math.h 277
sin = _libraries['/usr/local/cuda/lib/libcufft.dylib'].sin
sin.restype = c_double
# sin(p1)
sin.argtypes = [c_double]
sin.__doc__ = \
"""double sin(double p1)
/usr/include/architecture/i386/math.h:277"""
# /usr/include/architecture/i386/math.h 278
sinf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].sinf
sinf.restype = c_float
# sinf(p1)
sinf.argtypes = [c_float]
sinf.__doc__ = \
"""float sinf(float p1)
/usr/include/architecture/i386/math.h:278"""
# /usr/include/architecture/i386/math.h 280
tan = _libraries['/usr/local/cuda/lib/libcufft.dylib'].tan
tan.restype = c_double
# tan(p1)
tan.argtypes = [c_double]
tan.__doc__ = \
"""double tan(double p1)
/usr/include/architecture/i386/math.h:280"""
# /usr/include/architecture/i386/math.h 281
tanf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].tanf
tanf.restype = c_float
# tanf(p1)
tanf.argtypes = [c_float]
tanf.__doc__ = \
"""float tanf(float p1)
/usr/include/architecture/i386/math.h:281"""
# /usr/include/architecture/i386/math.h 283
acosh = _libraries['/usr/local/cuda/lib/libcufft.dylib'].acosh
acosh.restype = c_double
# acosh(p1)
acosh.argtypes = [c_double]
acosh.__doc__ = \
"""double acosh(double p1)
/usr/include/architecture/i386/math.h:283"""
# /usr/include/architecture/i386/math.h 284
acoshf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].acoshf
acoshf.restype = c_float
# acoshf(p1)
acoshf.argtypes = [c_float]
acoshf.__doc__ = \
"""float acoshf(float p1)
/usr/include/architecture/i386/math.h:284"""
# /usr/include/architecture/i386/math.h 286
asinh = _libraries['/usr/local/cuda/lib/libcufft.dylib'].asinh
asinh.restype = c_double
# asinh(p1)
asinh.argtypes = [c_double]
asinh.__doc__ = \
"""double asinh(double p1)
/usr/include/architecture/i386/math.h:286"""
# /usr/include/architecture/i386/math.h 287
asinhf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].asinhf
asinhf.restype = c_float
# asinhf(p1)
asinhf.argtypes = [c_float]
asinhf.__doc__ = \
"""float asinhf(float p1)
/usr/include/architecture/i386/math.h:287"""
# /usr/include/architecture/i386/math.h 289
atanh = _libraries['/usr/local/cuda/lib/libcufft.dylib'].atanh
atanh.restype = c_double
# atanh(p1)
atanh.argtypes = [c_double]
atanh.__doc__ = \
"""double atanh(double p1)
/usr/include/architecture/i386/math.h:289"""
# /usr/include/architecture/i386/math.h 290
atanhf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].atanhf
atanhf.restype = c_float
# atanhf(p1)
atanhf.argtypes = [c_float]
atanhf.__doc__ = \
"""float atanhf(float p1)
/usr/include/architecture/i386/math.h:290"""
# /usr/include/architecture/i386/math.h 292
cosh = _libraries['/usr/local/cuda/lib/libcufft.dylib'].cosh
cosh.restype = c_double
# cosh(p1)
cosh.argtypes = [c_double]
cosh.__doc__ = \
"""double cosh(double p1)
/usr/include/architecture/i386/math.h:292"""
# /usr/include/architecture/i386/math.h 293
coshf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].coshf
coshf.restype = c_float
# coshf(p1)
coshf.argtypes = [c_float]
coshf.__doc__ = \
"""float coshf(float p1)
/usr/include/architecture/i386/math.h:293"""
# /usr/include/architecture/i386/math.h 295
sinh = _libraries['/usr/local/cuda/lib/libcufft.dylib'].sinh
sinh.restype = c_double
# sinh(p1)
sinh.argtypes = [c_double]
sinh.__doc__ = \
"""double sinh(double p1)
/usr/include/architecture/i386/math.h:295"""
# /usr/include/architecture/i386/math.h 296
sinhf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].sinhf
sinhf.restype = c_float
# sinhf(p1)
sinhf.argtypes = [c_float]
sinhf.__doc__ = \
"""float sinhf(float p1)
/usr/include/architecture/i386/math.h:296"""
# /usr/include/architecture/i386/math.h 298
tanh = _libraries['/usr/local/cuda/lib/libcufft.dylib'].tanh
tanh.restype = c_double
# tanh(p1)
tanh.argtypes = [c_double]
tanh.__doc__ = \
"""double tanh(double p1)
/usr/include/architecture/i386/math.h:298"""
# /usr/include/architecture/i386/math.h 299
tanhf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].tanhf
tanhf.restype = c_float
# tanhf(p1)
tanhf.argtypes = [c_float]
tanhf.__doc__ = \
"""float tanhf(float p1)
/usr/include/architecture/i386/math.h:299"""
# /usr/include/architecture/i386/math.h 301
exp = _libraries['/usr/local/cuda/lib/libcufft.dylib'].exp
exp.restype = c_double
# exp(p1)
exp.argtypes = [c_double]
exp.__doc__ = \
"""double exp(double p1)
/usr/include/architecture/i386/math.h:301"""
# /usr/include/architecture/i386/math.h 302
expf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].expf
expf.restype = c_float
# expf(p1)
expf.argtypes = [c_float]
expf.__doc__ = \
"""float expf(float p1)
/usr/include/architecture/i386/math.h:302"""
# /usr/include/architecture/i386/math.h 304
exp2 = _libraries['/usr/local/cuda/lib/libcufft.dylib'].exp2
exp2.restype = c_double
# exp2(p1)
exp2.argtypes = [c_double]
exp2.__doc__ = \
"""double exp2(double p1)
/usr/include/architecture/i386/math.h:304"""
# /usr/include/architecture/i386/math.h 305
exp2f = _libraries['/usr/local/cuda/lib/libcufft.dylib'].exp2f
exp2f.restype = c_float
# exp2f(p1)
exp2f.argtypes = [c_float]
exp2f.__doc__ = \
"""float exp2f(float p1)
/usr/include/architecture/i386/math.h:305"""
# /usr/include/architecture/i386/math.h 307
expm1 = _libraries['/usr/local/cuda/lib/libcufft.dylib'].expm1
expm1.restype = c_double
# expm1(p1)
expm1.argtypes = [c_double]
expm1.__doc__ = \
"""double expm1(double p1)
/usr/include/architecture/i386/math.h:307"""
# /usr/include/architecture/i386/math.h 308
expm1f = _libraries['/usr/local/cuda/lib/libcufft.dylib'].expm1f
expm1f.restype = c_float
# expm1f(p1)
expm1f.argtypes = [c_float]
expm1f.__doc__ = \
"""float expm1f(float p1)
/usr/include/architecture/i386/math.h:308"""
# /usr/include/architecture/i386/math.h 310
log = _libraries['/usr/local/cuda/lib/libcufft.dylib'].log
log.restype = c_double
# log(p1)
log.argtypes = [c_double]
log.__doc__ = \
"""double log(double p1)
/usr/include/architecture/i386/math.h:310"""
# /usr/include/architecture/i386/math.h 311
logf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].logf
logf.restype = c_float
# logf(p1)
logf.argtypes = [c_float]
logf.__doc__ = \
"""float logf(float p1)
/usr/include/architecture/i386/math.h:311"""
# /usr/include/architecture/i386/math.h 313
log10 = _libraries['/usr/local/cuda/lib/libcufft.dylib'].log10
log10.restype = c_double
# log10(p1)
log10.argtypes = [c_double]
log10.__doc__ = \
"""double log10(double p1)
/usr/include/architecture/i386/math.h:313"""
# /usr/include/architecture/i386/math.h 314
log10f = _libraries['/usr/local/cuda/lib/libcufft.dylib'].log10f
log10f.restype = c_float
# log10f(p1)
log10f.argtypes = [c_float]
log10f.__doc__ = \
"""float log10f(float p1)
/usr/include/architecture/i386/math.h:314"""
# /usr/include/architecture/i386/math.h 316
log2 = _libraries['/usr/local/cuda/lib/libcufft.dylib'].log2
log2.restype = c_double
# log2(p1)
log2.argtypes = [c_double]
log2.__doc__ = \
"""double log2(double p1)
/usr/include/architecture/i386/math.h:316"""
# /usr/include/architecture/i386/math.h 317
log2f = _libraries['/usr/local/cuda/lib/libcufft.dylib'].log2f
log2f.restype = c_float
# log2f(p1)
log2f.argtypes = [c_float]
log2f.__doc__ = \
"""float log2f(float p1)
/usr/include/architecture/i386/math.h:317"""
# /usr/include/architecture/i386/math.h 319
log1p = _libraries['/usr/local/cuda/lib/libcufft.dylib'].log1p
log1p.restype = c_double
# log1p(p1)
log1p.argtypes = [c_double]
log1p.__doc__ = \
"""double log1p(double p1)
/usr/include/architecture/i386/math.h:319"""
# /usr/include/architecture/i386/math.h 320
log1pf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].log1pf
log1pf.restype = c_float
# log1pf(p1)
log1pf.argtypes = [c_float]
log1pf.__doc__ = \
"""float log1pf(float p1)
/usr/include/architecture/i386/math.h:320"""
# /usr/include/architecture/i386/math.h 322
logb = _libraries['/usr/local/cuda/lib/libcufft.dylib'].logb
logb.restype = c_double
# logb(p1)
logb.argtypes = [c_double]
logb.__doc__ = \
"""double logb(double p1)
/usr/include/architecture/i386/math.h:322"""
# /usr/include/architecture/i386/math.h 323
logbf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].logbf
logbf.restype = c_float
# logbf(p1)
logbf.argtypes = [c_float]
logbf.__doc__ = \
"""float logbf(float p1)
/usr/include/architecture/i386/math.h:323"""
# /usr/include/architecture/i386/math.h 325
modf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].modf
modf.restype = c_double
# modf(p1, p2)
modf.argtypes = [c_double, POINTER(c_double)]
modf.__doc__ = \
"""double modf(double p1, double * p2)
/usr/include/architecture/i386/math.h:325"""
# /usr/include/architecture/i386/math.h 326
modff = _libraries['/usr/local/cuda/lib/libcufft.dylib'].modff
modff.restype = c_float
# modff(p1, p2)
modff.argtypes = [c_float, POINTER(c_float)]
modff.__doc__ = \
"""float modff(float p1, float * p2)
/usr/include/architecture/i386/math.h:326"""
# /usr/include/architecture/i386/math.h 328
ldexp = _libraries['/usr/local/cuda/lib/libcufft.dylib'].ldexp
ldexp.restype = c_double
# ldexp(p1, p2)
ldexp.argtypes = [c_double, c_int]
ldexp.__doc__ = \
"""double ldexp(double p1, int p2)
/usr/include/architecture/i386/math.h:328"""
# /usr/include/architecture/i386/math.h 329
ldexpf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].ldexpf
ldexpf.restype = c_float
# ldexpf(p1, p2)
ldexpf.argtypes = [c_float, c_int]
ldexpf.__doc__ = \
"""float ldexpf(float p1, int p2)
/usr/include/architecture/i386/math.h:329"""
# /usr/include/architecture/i386/math.h 331
frexp = _libraries['/usr/local/cuda/lib/libcufft.dylib'].frexp
frexp.restype = c_double
# frexp(p1, p2)
frexp.argtypes = [c_double, POINTER(c_int)]
frexp.__doc__ = \
"""double frexp(double p1, int * p2)
/usr/include/architecture/i386/math.h:331"""
# /usr/include/architecture/i386/math.h 332
frexpf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].frexpf
frexpf.restype = c_float
# frexpf(p1, p2)
frexpf.argtypes = [c_float, POINTER(c_int)]
frexpf.__doc__ = \
"""float frexpf(float p1, int * p2)
/usr/include/architecture/i386/math.h:332"""
# /usr/include/architecture/i386/math.h 334
ilogb = _libraries['/usr/local/cuda/lib/libcufft.dylib'].ilogb
ilogb.restype = c_int
# ilogb(p1)
ilogb.argtypes = [c_double]
ilogb.__doc__ = \
"""int ilogb(double p1)
/usr/include/architecture/i386/math.h:334"""
# /usr/include/architecture/i386/math.h 335
ilogbf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].ilogbf
ilogbf.restype = c_int
# ilogbf(p1)
ilogbf.argtypes = [c_float]
ilogbf.__doc__ = \
"""int ilogbf(float p1)
/usr/include/architecture/i386/math.h:335"""
# /usr/include/architecture/i386/math.h 337
scalbn = _libraries['/usr/local/cuda/lib/libcufft.dylib'].scalbn
scalbn.restype = c_double
# scalbn(p1, p2)
scalbn.argtypes = [c_double, c_int]
scalbn.__doc__ = \
"""double scalbn(double p1, int p2)
/usr/include/architecture/i386/math.h:337"""
# /usr/include/architecture/i386/math.h 338
scalbnf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].scalbnf
scalbnf.restype = c_float
# scalbnf(p1, p2)
scalbnf.argtypes = [c_float, c_int]
scalbnf.__doc__ = \
"""float scalbnf(float p1, int p2)
/usr/include/architecture/i386/math.h:338"""
# /usr/include/architecture/i386/math.h 340
scalbln = _libraries['/usr/local/cuda/lib/libcufft.dylib'].scalbln
scalbln.restype = c_double
# scalbln(p1, p2)
scalbln.argtypes = [c_double, c_long]
scalbln.__doc__ = \
"""double scalbln(double p1, long int p2)
/usr/include/architecture/i386/math.h:340"""
# /usr/include/architecture/i386/math.h 341
scalblnf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].scalblnf
scalblnf.restype = c_float
# scalblnf(p1, p2)
scalblnf.argtypes = [c_float, c_long]
scalblnf.__doc__ = \
"""float scalblnf(float p1, long int p2)
/usr/include/architecture/i386/math.h:341"""
# /usr/include/architecture/i386/math.h 343
fabs = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fabs
fabs.restype = c_double
# fabs(p1)
fabs.argtypes = [c_double]
fabs.__doc__ = \
"""double fabs(double p1)
/usr/include/architecture/i386/math.h:343"""
# /usr/include/architecture/i386/math.h 344
fabsf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fabsf
fabsf.restype = c_float
# fabsf(p1)
fabsf.argtypes = [c_float]
fabsf.__doc__ = \
"""float fabsf(float p1)
/usr/include/architecture/i386/math.h:344"""
# /usr/include/architecture/i386/math.h 346
cbrt = _libraries['/usr/local/cuda/lib/libcufft.dylib'].cbrt
cbrt.restype = c_double
# cbrt(p1)
cbrt.argtypes = [c_double]
cbrt.__doc__ = \
"""double cbrt(double p1)
/usr/include/architecture/i386/math.h:346"""
# /usr/include/architecture/i386/math.h 347
cbrtf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].cbrtf
cbrtf.restype = c_float
# cbrtf(p1)
cbrtf.argtypes = [c_float]
cbrtf.__doc__ = \
"""float cbrtf(float p1)
/usr/include/architecture/i386/math.h:347"""
# /usr/include/architecture/i386/math.h 349
hypot = _libraries['/usr/local/cuda/lib/libcufft.dylib'].hypot
hypot.restype = c_double
# hypot(p1, p2)
hypot.argtypes = [c_double, c_double]
hypot.__doc__ = \
"""double hypot(double p1, double p2)
/usr/include/architecture/i386/math.h:349"""
# /usr/include/architecture/i386/math.h 350
hypotf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].hypotf
hypotf.restype = c_float
# hypotf(p1, p2)
hypotf.argtypes = [c_float, c_float]
hypotf.__doc__ = \
"""float hypotf(float p1, float p2)
/usr/include/architecture/i386/math.h:350"""
# /usr/include/architecture/i386/math.h 352
pow = _libraries['/usr/local/cuda/lib/libcufft.dylib'].pow
pow.restype = c_double
# pow(p1, p2)
pow.argtypes = [c_double, c_double]
pow.__doc__ = \
"""double pow(double p1, double p2)
/usr/include/architecture/i386/math.h:352"""
# /usr/include/architecture/i386/math.h 353
powf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].powf
powf.restype = c_float
# powf(p1, p2)
powf.argtypes = [c_float, c_float]
powf.__doc__ = \
"""float powf(float p1, float p2)
/usr/include/architecture/i386/math.h:353"""
# /usr/include/architecture/i386/math.h 355
sqrt = _libraries['/usr/local/cuda/lib/libcufft.dylib'].sqrt
sqrt.restype = c_double
# sqrt(p1)
sqrt.argtypes = [c_double]
sqrt.__doc__ = \
"""double sqrt(double p1)
/usr/include/architecture/i386/math.h:355"""
# /usr/include/architecture/i386/math.h 356
sqrtf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].sqrtf
sqrtf.restype = c_float
# sqrtf(p1)
sqrtf.argtypes = [c_float]
sqrtf.__doc__ = \
"""float sqrtf(float p1)
/usr/include/architecture/i386/math.h:356"""
# /usr/include/architecture/i386/math.h 358
erf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].erf
erf.restype = c_double
# erf(p1)
erf.argtypes = [c_double]
erf.__doc__ = \
"""double erf(double p1)
/usr/include/architecture/i386/math.h:358"""
# /usr/include/architecture/i386/math.h 359
erff = _libraries['/usr/local/cuda/lib/libcufft.dylib'].erff
erff.restype = c_float
# erff(p1)
erff.argtypes = [c_float]
erff.__doc__ = \
"""float erff(float p1)
/usr/include/architecture/i386/math.h:359"""
# /usr/include/architecture/i386/math.h 361
erfc = _libraries['/usr/local/cuda/lib/libcufft.dylib'].erfc
erfc.restype = c_double
# erfc(p1)
erfc.argtypes = [c_double]
erfc.__doc__ = \
"""double erfc(double p1)
/usr/include/architecture/i386/math.h:361"""
# /usr/include/architecture/i386/math.h 362
erfcf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].erfcf
erfcf.restype = c_float
# erfcf(p1)
erfcf.argtypes = [c_float]
erfcf.__doc__ = \
"""float erfcf(float p1)
/usr/include/architecture/i386/math.h:362"""
# /usr/include/architecture/i386/math.h 364
lgamma = _libraries['/usr/local/cuda/lib/libcufft.dylib'].lgamma
lgamma.restype = c_double
# lgamma(p1)
lgamma.argtypes = [c_double]
lgamma.__doc__ = \
"""double lgamma(double p1)
/usr/include/architecture/i386/math.h:364"""
# /usr/include/architecture/i386/math.h 365
lgammaf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].lgammaf
lgammaf.restype = c_float
# lgammaf(p1)
lgammaf.argtypes = [c_float]
lgammaf.__doc__ = \
"""float lgammaf(float p1)
/usr/include/architecture/i386/math.h:365"""
# /usr/include/architecture/i386/math.h 367
tgamma = _libraries['/usr/local/cuda/lib/libcufft.dylib'].tgamma
tgamma.restype = c_double
# tgamma(p1)
tgamma.argtypes = [c_double]
tgamma.__doc__ = \
"""double tgamma(double p1)
/usr/include/architecture/i386/math.h:367"""
# /usr/include/architecture/i386/math.h 368
tgammaf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].tgammaf
tgammaf.restype = c_float
# tgammaf(p1)
tgammaf.argtypes = [c_float]
tgammaf.__doc__ = \
"""float tgammaf(float p1)
/usr/include/architecture/i386/math.h:368"""
# /usr/include/architecture/i386/math.h 370
ceil = _libraries['/usr/local/cuda/lib/libcufft.dylib'].ceil
ceil.restype = c_double
# ceil(p1)
ceil.argtypes = [c_double]
ceil.__doc__ = \
"""double ceil(double p1)
/usr/include/architecture/i386/math.h:370"""
# /usr/include/architecture/i386/math.h 371
ceilf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].ceilf
ceilf.restype = c_float
# ceilf(p1)
ceilf.argtypes = [c_float]
ceilf.__doc__ = \
"""float ceilf(float p1)
/usr/include/architecture/i386/math.h:371"""
# /usr/include/architecture/i386/math.h 373
floor = _libraries['/usr/local/cuda/lib/libcufft.dylib'].floor
floor.restype = c_double
# floor(p1)
floor.argtypes = [c_double]
floor.__doc__ = \
"""double floor(double p1)
/usr/include/architecture/i386/math.h:373"""
# /usr/include/architecture/i386/math.h 374
floorf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].floorf
floorf.restype = c_float
# floorf(p1)
floorf.argtypes = [c_float]
floorf.__doc__ = \
"""float floorf(float p1)
/usr/include/architecture/i386/math.h:374"""
# /usr/include/architecture/i386/math.h 376
nearbyint = _libraries['/usr/local/cuda/lib/libcufft.dylib'].nearbyint
nearbyint.restype = c_double
# nearbyint(p1)
nearbyint.argtypes = [c_double]
nearbyint.__doc__ = \
"""double nearbyint(double p1)
/usr/include/architecture/i386/math.h:376"""
# /usr/include/architecture/i386/math.h 377
nearbyintf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].nearbyintf
nearbyintf.restype = c_float
# nearbyintf(p1)
nearbyintf.argtypes = [c_float]
nearbyintf.__doc__ = \
"""float nearbyintf(float p1)
/usr/include/architecture/i386/math.h:377"""
# /usr/include/architecture/i386/math.h 379
rint = _libraries['/usr/local/cuda/lib/libcufft.dylib'].rint
rint.restype = c_double
# rint(p1)
rint.argtypes = [c_double]
rint.__doc__ = \
"""double rint(double p1)
/usr/include/architecture/i386/math.h:379"""
# /usr/include/architecture/i386/math.h 380
rintf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].rintf
rintf.restype = c_float
# rintf(p1)
rintf.argtypes = [c_float]
rintf.__doc__ = \
"""float rintf(float p1)
/usr/include/architecture/i386/math.h:380"""
# /usr/include/architecture/i386/math.h 382
lrint = _libraries['/usr/local/cuda/lib/libcufft.dylib'].lrint
lrint.restype = c_long
# lrint(p1)
lrint.argtypes = [c_double]
lrint.__doc__ = \
"""long int lrint(double p1)
/usr/include/architecture/i386/math.h:382"""
# /usr/include/architecture/i386/math.h 383
lrintf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].lrintf
lrintf.restype = c_long
# lrintf(p1)
lrintf.argtypes = [c_float]
lrintf.__doc__ = \
"""long int lrintf(float p1)
/usr/include/architecture/i386/math.h:383"""
# /usr/include/architecture/i386/math.h 385
round = _libraries['/usr/local/cuda/lib/libcufft.dylib'].round
round.restype = c_double
# round(p1)
round.argtypes = [c_double]
round.__doc__ = \
"""double round(double p1)
/usr/include/architecture/i386/math.h:385"""
# /usr/include/architecture/i386/math.h 386
roundf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].roundf
roundf.restype = c_float
# roundf(p1)
roundf.argtypes = [c_float]
roundf.__doc__ = \
"""float roundf(float p1)
/usr/include/architecture/i386/math.h:386"""
# /usr/include/architecture/i386/math.h 388
lround = _libraries['/usr/local/cuda/lib/libcufft.dylib'].lround
lround.restype = c_long
# lround(p1)
lround.argtypes = [c_double]
lround.__doc__ = \
"""long int lround(double p1)
/usr/include/architecture/i386/math.h:388"""
# /usr/include/architecture/i386/math.h 389
lroundf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].lroundf
lroundf.restype = c_long
# lroundf(p1)
lroundf.argtypes = [c_float]
lroundf.__doc__ = \
"""long int lroundf(float p1)
/usr/include/architecture/i386/math.h:389"""
# /usr/include/architecture/i386/math.h 394
llrint = _libraries['/usr/local/cuda/lib/libcufft.dylib'].llrint
llrint.restype = c_longlong
# llrint(p1)
llrint.argtypes = [c_double]
llrint.__doc__ = \
"""long long int llrint(double p1)
/usr/include/architecture/i386/math.h:394"""
# /usr/include/architecture/i386/math.h 395
llrintf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].llrintf
llrintf.restype = c_longlong
# llrintf(p1)
llrintf.argtypes = [c_float]
llrintf.__doc__ = \
"""long long int llrintf(float p1)
/usr/include/architecture/i386/math.h:395"""
# /usr/include/architecture/i386/math.h 397
llround = _libraries['/usr/local/cuda/lib/libcufft.dylib'].llround
llround.restype = c_longlong
# llround(p1)
llround.argtypes = [c_double]
llround.__doc__ = \
"""long long int llround(double p1)
/usr/include/architecture/i386/math.h:397"""
# /usr/include/architecture/i386/math.h 398
llroundf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].llroundf
llroundf.restype = c_longlong
# llroundf(p1)
llroundf.argtypes = [c_float]
llroundf.__doc__ = \
"""long long int llroundf(float p1)
/usr/include/architecture/i386/math.h:398"""
# /usr/include/architecture/i386/math.h 402
trunc = _libraries['/usr/local/cuda/lib/libcufft.dylib'].trunc
trunc.restype = c_double
# trunc(p1)
trunc.argtypes = [c_double]
trunc.__doc__ = \
"""double trunc(double p1)
/usr/include/architecture/i386/math.h:402"""
# /usr/include/architecture/i386/math.h 403
truncf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].truncf
truncf.restype = c_float
# truncf(p1)
truncf.argtypes = [c_float]
truncf.__doc__ = \
"""float truncf(float p1)
/usr/include/architecture/i386/math.h:403"""
# /usr/include/architecture/i386/math.h 405
fmod = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fmod
fmod.restype = c_double
# fmod(p1, p2)
fmod.argtypes = [c_double, c_double]
fmod.__doc__ = \
"""double fmod(double p1, double p2)
/usr/include/architecture/i386/math.h:405"""
# /usr/include/architecture/i386/math.h 406
fmodf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fmodf
fmodf.restype = c_float
# fmodf(p1, p2)
fmodf.argtypes = [c_float, c_float]
fmodf.__doc__ = \
"""float fmodf(float p1, float p2)
/usr/include/architecture/i386/math.h:406"""
# /usr/include/architecture/i386/math.h 408
remainder = _libraries['/usr/local/cuda/lib/libcufft.dylib'].remainder
remainder.restype = c_double
# remainder(p1, p2)
remainder.argtypes = [c_double, c_double]
remainder.__doc__ = \
"""double remainder(double p1, double p2)
/usr/include/architecture/i386/math.h:408"""
# /usr/include/architecture/i386/math.h 409
remainderf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].remainderf
remainderf.restype = c_float
# remainderf(p1, p2)
remainderf.argtypes = [c_float, c_float]
remainderf.__doc__ = \
"""float remainderf(float p1, float p2)
/usr/include/architecture/i386/math.h:409"""
# /usr/include/architecture/i386/math.h 411
remquo = _libraries['/usr/local/cuda/lib/libcufft.dylib'].remquo
remquo.restype = c_double
# remquo(p1, p2, p3)
remquo.argtypes = [c_double, c_double, POINTER(c_int)]
remquo.__doc__ = \
"""double remquo(double p1, double p2, int * p3)
/usr/include/architecture/i386/math.h:411"""
# /usr/include/architecture/i386/math.h 412
remquof = _libraries['/usr/local/cuda/lib/libcufft.dylib'].remquof
remquof.restype = c_float
# remquof(p1, p2, p3)
remquof.argtypes = [c_float, c_float, POINTER(c_int)]
remquof.__doc__ = \
"""float remquof(float p1, float p2, int * p3)
/usr/include/architecture/i386/math.h:412"""
# /usr/include/architecture/i386/math.h 414
copysign = _libraries['/usr/local/cuda/lib/libcufft.dylib'].copysign
copysign.restype = c_double
# copysign(p1, p2)
copysign.argtypes = [c_double, c_double]
copysign.__doc__ = \
"""double copysign(double p1, double p2)
/usr/include/architecture/i386/math.h:414"""
# /usr/include/architecture/i386/math.h 415
copysignf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].copysignf
copysignf.restype = c_float
# copysignf(p1, p2)
copysignf.argtypes = [c_float, c_float]
copysignf.__doc__ = \
"""float copysignf(float p1, float p2)
/usr/include/architecture/i386/math.h:415"""
# /usr/include/architecture/i386/math.h 417
nan = _libraries['/usr/local/cuda/lib/libcufft.dylib'].nan
nan.restype = c_double
# nan(p1)
nan.argtypes = [STRING]
nan.__doc__ = \
"""double nan(unknown * p1)
/usr/include/architecture/i386/math.h:417"""
# /usr/include/architecture/i386/math.h 418
nanf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].nanf
nanf.restype = c_float
# nanf(p1)
nanf.argtypes = [STRING]
nanf.__doc__ = \
"""float nanf(unknown * p1)
/usr/include/architecture/i386/math.h:418"""
# /usr/include/architecture/i386/math.h 420
nextafter = _libraries['/usr/local/cuda/lib/libcufft.dylib'].nextafter
nextafter.restype = c_double
# nextafter(p1, p2)
nextafter.argtypes = [c_double, c_double]
nextafter.__doc__ = \
"""double nextafter(double p1, double p2)
/usr/include/architecture/i386/math.h:420"""
# /usr/include/architecture/i386/math.h 421
nextafterf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].nextafterf
nextafterf.restype = c_float
# nextafterf(p1, p2)
nextafterf.argtypes = [c_float, c_float]
nextafterf.__doc__ = \
"""float nextafterf(float p1, float p2)
/usr/include/architecture/i386/math.h:421"""
# /usr/include/architecture/i386/math.h 423
fdim = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fdim
fdim.restype = c_double
# fdim(p1, p2)
fdim.argtypes = [c_double, c_double]
fdim.__doc__ = \
"""double fdim(double p1, double p2)
/usr/include/architecture/i386/math.h:423"""
# /usr/include/architecture/i386/math.h 424
fdimf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fdimf
fdimf.restype = c_float
# fdimf(p1, p2)
fdimf.argtypes = [c_float, c_float]
fdimf.__doc__ = \
"""float fdimf(float p1, float p2)
/usr/include/architecture/i386/math.h:424"""
# /usr/include/architecture/i386/math.h 426
fmax = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fmax
fmax.restype = c_double
# fmax(p1, p2)
fmax.argtypes = [c_double, c_double]
fmax.__doc__ = \
"""double fmax(double p1, double p2)
/usr/include/architecture/i386/math.h:426"""
# /usr/include/architecture/i386/math.h 427
fmaxf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fmaxf
fmaxf.restype = c_float
# fmaxf(p1, p2)
fmaxf.argtypes = [c_float, c_float]
fmaxf.__doc__ = \
"""float fmaxf(float p1, float p2)
/usr/include/architecture/i386/math.h:427"""
# /usr/include/architecture/i386/math.h 429
fmin = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fmin
fmin.restype = c_double
# fmin(p1, p2)
fmin.argtypes = [c_double, c_double]
fmin.__doc__ = \
"""double fmin(double p1, double p2)
/usr/include/architecture/i386/math.h:429"""
# /usr/include/architecture/i386/math.h 430
fminf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fminf
fminf.restype = c_float
# fminf(p1, p2)
fminf.argtypes = [c_float, c_float]
fminf.__doc__ = \
"""float fminf(float p1, float p2)
/usr/include/architecture/i386/math.h:430"""
# /usr/include/architecture/i386/math.h 432
fma = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fma
fma.restype = c_double
# fma(p1, p2, p3)
fma.argtypes = [c_double, c_double, c_double]
fma.__doc__ = \
"""double fma(double p1, double p2, double p3)
/usr/include/architecture/i386/math.h:432"""
# /usr/include/architecture/i386/math.h 433
fmaf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fmaf
fmaf.restype = c_float
# fmaf(p1, p2, p3)
fmaf.argtypes = [c_float, c_float, c_float]
fmaf.__doc__ = \
"""float fmaf(float p1, float p2, float p3)
/usr/include/architecture/i386/math.h:433"""
# /usr/include/architecture/i386/math.h 435
acosl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].acosl
acosl.restype = c_longdouble
# acosl(p1)
acosl.argtypes = [c_longdouble]
acosl.__doc__ = \
"""long double acosl(long double p1)
/usr/include/architecture/i386/math.h:435"""
# /usr/include/architecture/i386/math.h 436
asinl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].asinl
asinl.restype = c_longdouble
# asinl(p1)
asinl.argtypes = [c_longdouble]
asinl.__doc__ = \
"""long double asinl(long double p1)
/usr/include/architecture/i386/math.h:436"""
# /usr/include/architecture/i386/math.h 437
atanl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].atanl
atanl.restype = c_longdouble
# atanl(p1)
atanl.argtypes = [c_longdouble]
atanl.__doc__ = \
"""long double atanl(long double p1)
/usr/include/architecture/i386/math.h:437"""
# /usr/include/architecture/i386/math.h 438
atan2l = _libraries['/usr/local/cuda/lib/libcufft.dylib'].atan2l
atan2l.restype = c_longdouble
# atan2l(p1, p2)
atan2l.argtypes = [c_longdouble, c_longdouble]
atan2l.__doc__ = \
"""long double atan2l(long double p1, long double p2)
/usr/include/architecture/i386/math.h:438"""
# /usr/include/architecture/i386/math.h 439
cosl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].cosl
cosl.restype = c_longdouble
# cosl(p1)
cosl.argtypes = [c_longdouble]
cosl.__doc__ = \
"""long double cosl(long double p1)
/usr/include/architecture/i386/math.h:439"""
# /usr/include/architecture/i386/math.h 440
sinl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].sinl
sinl.restype = c_longdouble
# sinl(p1)
sinl.argtypes = [c_longdouble]
sinl.__doc__ = \
"""long double sinl(long double p1)
/usr/include/architecture/i386/math.h:440"""
# /usr/include/architecture/i386/math.h 441
tanl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].tanl
tanl.restype = c_longdouble
# tanl(p1)
tanl.argtypes = [c_longdouble]
tanl.__doc__ = \
"""long double tanl(long double p1)
/usr/include/architecture/i386/math.h:441"""
# /usr/include/architecture/i386/math.h 442
acoshl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].acoshl
acoshl.restype = c_longdouble
# acoshl(p1)
acoshl.argtypes = [c_longdouble]
acoshl.__doc__ = \
"""long double acoshl(long double p1)
/usr/include/architecture/i386/math.h:442"""
# /usr/include/architecture/i386/math.h 443
asinhl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].asinhl
asinhl.restype = c_longdouble
# asinhl(p1)
asinhl.argtypes = [c_longdouble]
asinhl.__doc__ = \
"""long double asinhl(long double p1)
/usr/include/architecture/i386/math.h:443"""
# /usr/include/architecture/i386/math.h 444
atanhl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].atanhl
atanhl.restype = c_longdouble
# atanhl(p1)
atanhl.argtypes = [c_longdouble]
atanhl.__doc__ = \
"""long double atanhl(long double p1)
/usr/include/architecture/i386/math.h:444"""
# /usr/include/architecture/i386/math.h 445
coshl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].coshl
coshl.restype = c_longdouble
# coshl(p1)
coshl.argtypes = [c_longdouble]
coshl.__doc__ = \
"""long double coshl(long double p1)
/usr/include/architecture/i386/math.h:445"""
# /usr/include/architecture/i386/math.h 446
sinhl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].sinhl
sinhl.restype = c_longdouble
# sinhl(p1)
sinhl.argtypes = [c_longdouble]
sinhl.__doc__ = \
"""long double sinhl(long double p1)
/usr/include/architecture/i386/math.h:446"""
# /usr/include/architecture/i386/math.h 447
tanhl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].tanhl
tanhl.restype = c_longdouble
# tanhl(p1)
tanhl.argtypes = [c_longdouble]
tanhl.__doc__ = \
"""long double tanhl(long double p1)
/usr/include/architecture/i386/math.h:447"""
# /usr/include/architecture/i386/math.h 448
expl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].expl
expl.restype = c_longdouble
# expl(p1)
expl.argtypes = [c_longdouble]
expl.__doc__ = \
"""long double expl(long double p1)
/usr/include/architecture/i386/math.h:448"""
# /usr/include/architecture/i386/math.h 449
exp2l = _libraries['/usr/local/cuda/lib/libcufft.dylib'].exp2l
exp2l.restype = c_longdouble
# exp2l(p1)
exp2l.argtypes = [c_longdouble]
exp2l.__doc__ = \
"""long double exp2l(long double p1)
/usr/include/architecture/i386/math.h:449"""
# /usr/include/architecture/i386/math.h 450
expm1l = _libraries['/usr/local/cuda/lib/libcufft.dylib'].expm1l
expm1l.restype = c_longdouble
# expm1l(p1)
expm1l.argtypes = [c_longdouble]
expm1l.__doc__ = \
"""long double expm1l(long double p1)
/usr/include/architecture/i386/math.h:450"""
# /usr/include/architecture/i386/math.h 451
logl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].logl
logl.restype = c_longdouble
# logl(p1)
logl.argtypes = [c_longdouble]
logl.__doc__ = \
"""long double logl(long double p1)
/usr/include/architecture/i386/math.h:451"""
# /usr/include/architecture/i386/math.h 452
log10l = _libraries['/usr/local/cuda/lib/libcufft.dylib'].log10l
log10l.restype = c_longdouble
# log10l(p1)
log10l.argtypes = [c_longdouble]
log10l.__doc__ = \
"""long double log10l(long double p1)
/usr/include/architecture/i386/math.h:452"""
# /usr/include/architecture/i386/math.h 453
log2l = _libraries['/usr/local/cuda/lib/libcufft.dylib'].log2l
log2l.restype = c_longdouble
# log2l(p1)
log2l.argtypes = [c_longdouble]
log2l.__doc__ = \
"""long double log2l(long double p1)
/usr/include/architecture/i386/math.h:453"""
# /usr/include/architecture/i386/math.h 454
log1pl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].log1pl
log1pl.restype = c_longdouble
# log1pl(p1)
log1pl.argtypes = [c_longdouble]
log1pl.__doc__ = \
"""long double log1pl(long double p1)
/usr/include/architecture/i386/math.h:454"""
# /usr/include/architecture/i386/math.h 455
logbl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].logbl
logbl.restype = c_longdouble
# logbl(p1)
logbl.argtypes = [c_longdouble]
logbl.__doc__ = \
"""long double logbl(long double p1)
/usr/include/architecture/i386/math.h:455"""
# /usr/include/architecture/i386/math.h 456
modfl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].modfl
modfl.restype = c_longdouble
# modfl(p1, p2)
modfl.argtypes = [c_longdouble, POINTER(c_longdouble)]
modfl.__doc__ = \
"""long double modfl(long double p1, long double * p2)
/usr/include/architecture/i386/math.h:456"""
# /usr/include/architecture/i386/math.h 457
ldexpl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].ldexpl
ldexpl.restype = c_longdouble
# ldexpl(p1, p2)
ldexpl.argtypes = [c_longdouble, c_int]
ldexpl.__doc__ = \
"""long double ldexpl(long double p1, int p2)
/usr/include/architecture/i386/math.h:457"""
# /usr/include/architecture/i386/math.h 458
frexpl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].frexpl
frexpl.restype = c_longdouble
# frexpl(p1, p2)
frexpl.argtypes = [c_longdouble, POINTER(c_int)]
frexpl.__doc__ = \
"""long double frexpl(long double p1, int * p2)
/usr/include/architecture/i386/math.h:458"""
# /usr/include/architecture/i386/math.h 459
ilogbl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].ilogbl
ilogbl.restype = c_int
# ilogbl(p1)
ilogbl.argtypes = [c_longdouble]
ilogbl.__doc__ = \
"""int ilogbl(long double p1)
/usr/include/architecture/i386/math.h:459"""
# /usr/include/architecture/i386/math.h 460
scalbnl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].scalbnl
scalbnl.restype = c_longdouble
# scalbnl(p1, p2)
scalbnl.argtypes = [c_longdouble, c_int]
scalbnl.__doc__ = \
"""long double scalbnl(long double p1, int p2)
/usr/include/architecture/i386/math.h:460"""
# /usr/include/architecture/i386/math.h 461
scalblnl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].scalblnl
scalblnl.restype = c_longdouble
# scalblnl(p1, p2)
scalblnl.argtypes = [c_longdouble, c_long]
scalblnl.__doc__ = \
"""long double scalblnl(long double p1, long int p2)
/usr/include/architecture/i386/math.h:461"""
# /usr/include/architecture/i386/math.h 462
fabsl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fabsl
fabsl.restype = c_longdouble
# fabsl(p1)
fabsl.argtypes = [c_longdouble]
fabsl.__doc__ = \
"""long double fabsl(long double p1)
/usr/include/architecture/i386/math.h:462"""
# /usr/include/architecture/i386/math.h 463
cbrtl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].cbrtl
cbrtl.restype = c_longdouble
# cbrtl(p1)
cbrtl.argtypes = [c_longdouble]
cbrtl.__doc__ = \
"""long double cbrtl(long double p1)
/usr/include/architecture/i386/math.h:463"""
# /usr/include/architecture/i386/math.h 464
hypotl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].hypotl
hypotl.restype = c_longdouble
# hypotl(p1, p2)
hypotl.argtypes = [c_longdouble, c_longdouble]
hypotl.__doc__ = \
"""long double hypotl(long double p1, long double p2)
/usr/include/architecture/i386/math.h:464"""
# /usr/include/architecture/i386/math.h 465
powl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].powl
powl.restype = c_longdouble
# powl(p1, p2)
powl.argtypes = [c_longdouble, c_longdouble]
powl.__doc__ = \
"""long double powl(long double p1, long double p2)
/usr/include/architecture/i386/math.h:465"""
# /usr/include/architecture/i386/math.h 466
sqrtl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].sqrtl
sqrtl.restype = c_longdouble
# sqrtl(p1)
sqrtl.argtypes = [c_longdouble]
sqrtl.__doc__ = \
"""long double sqrtl(long double p1)
/usr/include/architecture/i386/math.h:466"""
# /usr/include/architecture/i386/math.h 467
erfl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].erfl
erfl.restype = c_longdouble
# erfl(p1)
erfl.argtypes = [c_longdouble]
erfl.__doc__ = \
"""long double erfl(long double p1)
/usr/include/architecture/i386/math.h:467"""
# /usr/include/architecture/i386/math.h 468
erfcl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].erfcl
erfcl.restype = c_longdouble
# erfcl(p1)
erfcl.argtypes = [c_longdouble]
erfcl.__doc__ = \
"""long double erfcl(long double p1)
/usr/include/architecture/i386/math.h:468"""
# /usr/include/architecture/i386/math.h 469
lgammal = _libraries['/usr/local/cuda/lib/libcufft.dylib'].lgammal
lgammal.restype = c_longdouble
# lgammal(p1)
lgammal.argtypes = [c_longdouble]
lgammal.__doc__ = \
"""long double lgammal(long double p1)
/usr/include/architecture/i386/math.h:469"""
# /usr/include/architecture/i386/math.h 470
tgammal = _libraries['/usr/local/cuda/lib/libcufft.dylib'].tgammal
tgammal.restype = c_longdouble
# tgammal(p1)
tgammal.argtypes = [c_longdouble]
tgammal.__doc__ = \
"""long double tgammal(long double p1)
/usr/include/architecture/i386/math.h:470"""
# /usr/include/architecture/i386/math.h 471
ceill = _libraries['/usr/local/cuda/lib/libcufft.dylib'].ceill
ceill.restype = c_longdouble
# ceill(p1)
ceill.argtypes = [c_longdouble]
ceill.__doc__ = \
"""long double ceill(long double p1)
/usr/include/architecture/i386/math.h:471"""
# /usr/include/architecture/i386/math.h 472
floorl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].floorl
floorl.restype = c_longdouble
# floorl(p1)
floorl.argtypes = [c_longdouble]
floorl.__doc__ = \
"""long double floorl(long double p1)
/usr/include/architecture/i386/math.h:472"""
# /usr/include/architecture/i386/math.h 473
nearbyintl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].nearbyintl
nearbyintl.restype = c_longdouble
# nearbyintl(p1)
nearbyintl.argtypes = [c_longdouble]
nearbyintl.__doc__ = \
"""long double nearbyintl(long double p1)
/usr/include/architecture/i386/math.h:473"""
# /usr/include/architecture/i386/math.h 474
rintl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].rintl
rintl.restype = c_longdouble
# rintl(p1)
rintl.argtypes = [c_longdouble]
rintl.__doc__ = \
"""long double rintl(long double p1)
/usr/include/architecture/i386/math.h:474"""
# /usr/include/architecture/i386/math.h 475
lrintl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].lrintl
lrintl.restype = c_long
# lrintl(p1)
lrintl.argtypes = [c_longdouble]
lrintl.__doc__ = \
"""long int lrintl(long double p1)
/usr/include/architecture/i386/math.h:475"""
# /usr/include/architecture/i386/math.h 476
roundl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].roundl
roundl.restype = c_longdouble
# roundl(p1)
roundl.argtypes = [c_longdouble]
roundl.__doc__ = \
"""long double roundl(long double p1)
/usr/include/architecture/i386/math.h:476"""
# /usr/include/architecture/i386/math.h 477
lroundl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].lroundl
lroundl.restype = c_long
# lroundl(p1)
lroundl.argtypes = [c_longdouble]
lroundl.__doc__ = \
"""long int lroundl(long double p1)
/usr/include/architecture/i386/math.h:477"""
# /usr/include/architecture/i386/math.h 481
llrintl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].llrintl
llrintl.restype = c_longlong
# llrintl(p1)
llrintl.argtypes = [c_longdouble]
llrintl.__doc__ = \
"""long long int llrintl(long double p1)
/usr/include/architecture/i386/math.h:481"""
# /usr/include/architecture/i386/math.h 482
llroundl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].llroundl
llroundl.restype = c_longlong
# llroundl(p1)
llroundl.argtypes = [c_longdouble]
llroundl.__doc__ = \
"""long long int llroundl(long double p1)
/usr/include/architecture/i386/math.h:482"""
# /usr/include/architecture/i386/math.h 485
truncl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].truncl
truncl.restype = c_longdouble
# truncl(p1)
truncl.argtypes = [c_longdouble]
truncl.__doc__ = \
"""long double truncl(long double p1)
/usr/include/architecture/i386/math.h:485"""
# /usr/include/architecture/i386/math.h 486
fmodl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fmodl
fmodl.restype = c_longdouble
# fmodl(p1, p2)
fmodl.argtypes = [c_longdouble, c_longdouble]
fmodl.__doc__ = \
"""long double fmodl(long double p1, long double p2)
/usr/include/architecture/i386/math.h:486"""
# /usr/include/architecture/i386/math.h 487
remainderl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].remainderl
remainderl.restype = c_longdouble
# remainderl(p1, p2)
remainderl.argtypes = [c_longdouble, c_longdouble]
remainderl.__doc__ = \
"""long double remainderl(long double p1, long double p2)
/usr/include/architecture/i386/math.h:487"""
# /usr/include/architecture/i386/math.h 488
remquol = _libraries['/usr/local/cuda/lib/libcufft.dylib'].remquol
remquol.restype = c_longdouble
# remquol(p1, p2, p3)
remquol.argtypes = [c_longdouble, c_longdouble, POINTER(c_int)]
remquol.__doc__ = \
"""long double remquol(long double p1, long double p2, int * p3)
/usr/include/architecture/i386/math.h:488"""
# /usr/include/architecture/i386/math.h 489
copysignl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].copysignl
copysignl.restype = c_longdouble
# copysignl(p1, p2)
copysignl.argtypes = [c_longdouble, c_longdouble]
copysignl.__doc__ = \
"""long double copysignl(long double p1, long double p2)
/usr/include/architecture/i386/math.h:489"""
# /usr/include/architecture/i386/math.h 490
nanl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].nanl
nanl.restype = c_longdouble
# nanl(p1)
nanl.argtypes = [STRING]
nanl.__doc__ = \
"""long double nanl(unknown * p1)
/usr/include/architecture/i386/math.h:490"""
# /usr/include/architecture/i386/math.h 491
nextafterl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].nextafterl
nextafterl.restype = c_longdouble
# nextafterl(p1, p2)
nextafterl.argtypes = [c_longdouble, c_longdouble]
nextafterl.__doc__ = \
"""long double nextafterl(long double p1, long double p2)
/usr/include/architecture/i386/math.h:491"""
# /usr/include/architecture/i386/math.h 492
nexttoward = _libraries['/usr/local/cuda/lib/libcufft.dylib'].nexttoward
nexttoward.restype = c_double
# nexttoward(p1, p2)
nexttoward.argtypes = [c_double, c_longdouble]
nexttoward.__doc__ = \
"""double nexttoward(double p1, long double p2)
/usr/include/architecture/i386/math.h:492"""
# /usr/include/architecture/i386/math.h 493
nexttowardf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].nexttowardf
nexttowardf.restype = c_float
# nexttowardf(p1, p2)
nexttowardf.argtypes = [c_float, c_longdouble]
nexttowardf.__doc__ = \
"""float nexttowardf(float p1, long double p2)
/usr/include/architecture/i386/math.h:493"""
# /usr/include/architecture/i386/math.h 494
nexttowardl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].nexttowardl
nexttowardl.restype = c_longdouble
# nexttowardl(p1, p2)
nexttowardl.argtypes = [c_longdouble, c_longdouble]
nexttowardl.__doc__ = \
"""long double nexttowardl(long double p1, long double p2)
/usr/include/architecture/i386/math.h:494"""
# /usr/include/architecture/i386/math.h 495
fdiml = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fdiml
fdiml.restype = c_longdouble
# fdiml(p1, p2)
fdiml.argtypes = [c_longdouble, c_longdouble]
fdiml.__doc__ = \
"""long double fdiml(long double p1, long double p2)
/usr/include/architecture/i386/math.h:495"""
# /usr/include/architecture/i386/math.h 496
fmaxl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fmaxl
fmaxl.restype = c_longdouble
# fmaxl(p1, p2)
fmaxl.argtypes = [c_longdouble, c_longdouble]
fmaxl.__doc__ = \
"""long double fmaxl(long double p1, long double p2)
/usr/include/architecture/i386/math.h:496"""
# /usr/include/architecture/i386/math.h 497
fminl = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fminl
fminl.restype = c_longdouble
# fminl(p1, p2)
fminl.argtypes = [c_longdouble, c_longdouble]
fminl.__doc__ = \
"""long double fminl(long double p1, long double p2)
/usr/include/architecture/i386/math.h:497"""
# /usr/include/architecture/i386/math.h 498
fmal = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fmal
fmal.restype = c_longdouble
# fmal(p1, p2, p3)
fmal.argtypes = [c_longdouble, c_longdouble, c_longdouble]
fmal.__doc__ = \
"""long double fmal(long double p1, long double p2, long double p3)
/usr/include/architecture/i386/math.h:498"""
# /usr/include/architecture/i386/math.h 507
__inf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].__inf
__inf.restype = c_double
# __inf()
__inf.argtypes = []
__inf.__doc__ = \
"""double __inf()
/usr/include/architecture/i386/math.h:507"""
# /usr/include/architecture/i386/math.h 508
__inff = _libraries['/usr/local/cuda/lib/libcufft.dylib'].__inff
__inff.restype = c_float
# __inff()
__inff.argtypes = []
__inff.__doc__ = \
"""float __inff()
/usr/include/architecture/i386/math.h:508"""
# /usr/include/architecture/i386/math.h 510
__nan = _libraries['/usr/local/cuda/lib/libcufft.dylib'].__nan
__nan.restype = c_float
# __nan()
__nan.argtypes = []
__nan.__doc__ = \
"""float __nan()
/usr/include/architecture/i386/math.h:510"""
# /usr/include/architecture/i386/math.h 513
j0 = _libraries['/usr/local/cuda/lib/libcufft.dylib'].j0
j0.restype = c_double
# j0(p1)
j0.argtypes = [c_double]
j0.__doc__ = \
"""double j0(double p1)
/usr/include/architecture/i386/math.h:513"""
# /usr/include/architecture/i386/math.h 515
j1 = _libraries['/usr/local/cuda/lib/libcufft.dylib'].j1
j1.restype = c_double
# j1(p1)
j1.argtypes = [c_double]
j1.__doc__ = \
"""double j1(double p1)
/usr/include/architecture/i386/math.h:515"""
# /usr/include/architecture/i386/math.h 517
jn = _libraries['/usr/local/cuda/lib/libcufft.dylib'].jn
jn.restype = c_double
# jn(p1, p2)
jn.argtypes = [c_int, c_double]
jn.__doc__ = \
"""double jn(int p1, double p2)
/usr/include/architecture/i386/math.h:517"""
# /usr/include/architecture/i386/math.h 519
y0 = _libraries['/usr/local/cuda/lib/libcufft.dylib'].y0
y0.restype = c_double
# y0(p1)
y0.argtypes = [c_double]
y0.__doc__ = \
"""double y0(double p1)
/usr/include/architecture/i386/math.h:519"""
# /usr/include/architecture/i386/math.h 521
y1 = _libraries['/usr/local/cuda/lib/libcufft.dylib'].y1
y1.restype = c_double
# y1(p1)
y1.argtypes = [c_double]
y1.__doc__ = \
"""double y1(double p1)
/usr/include/architecture/i386/math.h:521"""
# /usr/include/architecture/i386/math.h 523
yn = _libraries['/usr/local/cuda/lib/libcufft.dylib'].yn
yn.restype = c_double
# yn(p1, p2)
yn.argtypes = [c_int, c_double]
yn.__doc__ = \
"""double yn(int p1, double p2)
/usr/include/architecture/i386/math.h:523"""
# /usr/include/architecture/i386/math.h 525
scalb = _libraries['/usr/local/cuda/lib/libcufft.dylib'].scalb
scalb.restype = c_double
# scalb(p1, p2)
scalb.argtypes = [c_double, c_double]
scalb.__doc__ = \
"""double scalb(double p1, double p2)
/usr/include/architecture/i386/math.h:525"""
signgam = (c_int).in_dll(_libraries['/usr/local/cuda/lib/libcufft.dylib'], 'signgam')
# /usr/include/architecture/i386/math.h 557
rinttol = _libraries['/usr/local/cuda/lib/libcufft.dylib'].rinttol
rinttol.restype = c_long
# rinttol(p1)
rinttol.argtypes = [c_double]
rinttol.__doc__ = \
"""long int rinttol(double p1)
/usr/include/architecture/i386/math.h:557"""
# /usr/include/architecture/i386/math.h 559
roundtol = _libraries['/usr/local/cuda/lib/libcufft.dylib'].roundtol
roundtol.restype = c_long
# roundtol(p1)
roundtol.argtypes = [c_double]
roundtol.__doc__ = \
"""long int roundtol(double p1)
/usr/include/architecture/i386/math.h:559"""
# /usr/include/architecture/i386/math.h 597
finite = _libraries['/usr/local/cuda/lib/libcufft.dylib'].finite
finite.restype = c_int
# finite(p1)
finite.argtypes = [c_double]
finite.__doc__ = \
"""int finite(double p1)
/usr/include/architecture/i386/math.h:597"""
# /usr/include/architecture/i386/math.h 599
gamma = _libraries['/usr/local/cuda/lib/libcufft.dylib'].gamma
gamma.restype = c_double
# gamma(p1)
gamma.argtypes = [c_double]
gamma.__doc__ = \
"""double gamma(double p1)
/usr/include/architecture/i386/math.h:599"""
# /usr/include/architecture/i386/math.h 610
significand = _libraries['/usr/local/cuda/lib/libcufft.dylib'].significand
significand.restype = c_double
# significand(p1)
significand.argtypes = [c_double]
significand.__doc__ = \
"""double significand(double p1)
/usr/include/architecture/i386/math.h:610"""
# /usr/include/architecture/i386/math.h 615
drem = _libraries['/usr/local/cuda/lib/libcufft.dylib'].drem
drem.restype = c_double
# drem(p1, p2)
drem.argtypes = [c_double, c_double]
drem.__doc__ = \
"""double drem(double p1, double p2)
/usr/include/architecture/i386/math.h:615"""
__int8_t = c_byte
__uint8_t = c_ubyte
__int16_t = c_short
__uint16_t = c_ushort
__int32_t = c_int
__uint32_t = c_uint
__int64_t = c_longlong
__uint64_t = c_ulonglong
__darwin_intptr_t = c_long
__darwin_natural_t = c_uint
__darwin_ct_rune_t = c_int
# /usr/include/i386/_types.h 79
class __mbstate_t(Union):
    pass
__mbstate_t._pack_ = 4
__mbstate_t._fields_ = [
    # /usr/include/i386/_types.h 79
    ('__mbstate8', c_char * 128),
    ('_mbstateL', c_longlong),
]
__darwin_mbstate_t = __mbstate_t
__darwin_ptrdiff_t = c_int
__darwin_size_t = c_ulong
__darwin_va_list = STRING
__darwin_wchar_t = c_int
__darwin_rune_t = __darwin_wchar_t
__darwin_wint_t = c_int
__darwin_clock_t = c_ulong
__darwin_socklen_t = __uint32_t
__darwin_ssize_t = c_long
__darwin_time_t = c_long
va_list = __darwin_va_list
__darwin_off_t = __int64_t
off_t = __darwin_off_t
size_t = __darwin_size_t
fpos_t = __darwin_off_t
# /usr/include/stdio.h 98
class __sbuf(Structure):
    pass
__sbuf._fields_ = [
    # /usr/include/stdio.h 98
    ('_base', POINTER(c_ubyte)),
    ('_size', c_int),
]
# /usr/include/stdio.h 104
class __sFILEX(Structure):
    pass
__sFILEX._fields_ = [
    # /usr/include/stdio.h 104
]
# /usr/include/stdio.h 132
class __sFILE(Structure):
    pass
__sFILE._pack_ = 4
__sFILE._fields_ = [
    # /usr/include/stdio.h 132
    ('_p', POINTER(c_ubyte)),
    ('_r', c_int),
    ('_w', c_int),
    ('_flags', c_short),
    ('_file', c_short),
    ('_bf', __sbuf),
    ('_lbfsize', c_int),
    ('_cookie', c_void_p),
    ('_close', CFUNCTYPE(c_int, c_void_p)),
    ('_read', CFUNCTYPE(c_int, c_void_p, STRING, c_int)),
    ('_seek', CFUNCTYPE(fpos_t, c_void_p, fpos_t, c_int)),
    ('_write', CFUNCTYPE(c_int, c_void_p, STRING, c_int)),
    ('_ub', __sbuf),
    ('_extra', POINTER(__sFILEX)),
    ('_ur', c_int),
    ('_ubuf', c_ubyte * 3),
    ('_nbuf', c_ubyte * 1),
    ('_lb', __sbuf),
    ('_blksize', c_int),
    ('_offset', fpos_t),
]
FILE = __sFILE
__stdinp = (POINTER(FILE)).in_dll(_libraries['/usr/local/cuda/lib/libcufft.dylib'], '__stdinp')
__stdoutp = (POINTER(FILE)).in_dll(_libraries['/usr/local/cuda/lib/libcufft.dylib'], '__stdoutp')
__stderrp = (POINTER(FILE)).in_dll(_libraries['/usr/local/cuda/lib/libcufft.dylib'], '__stderrp')
# /usr/include/stdio.h 249
clearerr = _libraries['/usr/local/cuda/lib/libcufft.dylib'].clearerr
clearerr.restype = None
# clearerr(p1)
clearerr.argtypes = [POINTER(FILE)]
clearerr.__doc__ = \
"""void clearerr(FILE * p1)
/usr/include/stdio.h:249"""
# /usr/include/stdio.h 250
fclose = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fclose
fclose.restype = c_int
# fclose(p1)
fclose.argtypes = [POINTER(FILE)]
fclose.__doc__ = \
"""int fclose(FILE * p1)
/usr/include/stdio.h:250"""
# /usr/include/stdio.h 251
feof = _libraries['/usr/local/cuda/lib/libcufft.dylib'].feof
feof.restype = c_int
# feof(p1)
feof.argtypes = [POINTER(FILE)]
feof.__doc__ = \
"""int feof(FILE * p1)
/usr/include/stdio.h:251"""
# /usr/include/stdio.h 252
ferror = _libraries['/usr/local/cuda/lib/libcufft.dylib'].ferror
ferror.restype = c_int
# ferror(p1)
ferror.argtypes = [POINTER(FILE)]
ferror.__doc__ = \
"""int ferror(FILE * p1)
/usr/include/stdio.h:252"""
# /usr/include/stdio.h 253
fflush = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fflush
fflush.restype = c_int
# fflush(p1)
fflush.argtypes = [POINTER(FILE)]
fflush.__doc__ = \
"""int fflush(FILE * p1)
/usr/include/stdio.h:253"""
# /usr/include/stdio.h 254
fgetc = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fgetc
fgetc.restype = c_int
# fgetc(p1)
fgetc.argtypes = [POINTER(FILE)]
fgetc.__doc__ = \
"""int fgetc(FILE * p1)
/usr/include/stdio.h:254"""
# /usr/include/stdio.h 255
fgetpos = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fgetpos
fgetpos.restype = c_int
# fgetpos(p1, p2)
fgetpos.argtypes = [POINTER(FILE), POINTER(fpos_t)]
fgetpos.__doc__ = \
"""int fgetpos(FILE * p1, fpos_t * p2)
/usr/include/stdio.h:255"""
# /usr/include/stdio.h 256
fgets = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fgets
fgets.restype = STRING
# fgets(p1, p2, p3)
fgets.argtypes = [STRING, c_int, POINTER(FILE)]
fgets.__doc__ = \
"""char * fgets(char * p1, int p2, FILE * p3)
/usr/include/stdio.h:256"""
# /usr/include/stdio.h 257
fopen = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fopen
fopen.restype = POINTER(FILE)
# fopen(p1, p2)
fopen.argtypes = [STRING, STRING]
fopen.__doc__ = \
"""FILE * fopen(unknown * p1, unknown * p2)
/usr/include/stdio.h:257"""
# /usr/include/stdio.h 258
fprintf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fprintf
fprintf.restype = c_int
# fprintf(p1, p2)
fprintf.argtypes = [POINTER(FILE), STRING]
fprintf.__doc__ = \
"""int fprintf(FILE * p1, unknown * p2)
/usr/include/stdio.h:258"""
# /usr/include/stdio.h 259
fputc = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fputc
fputc.restype = c_int
# fputc(p1, p2)
fputc.argtypes = [c_int, POINTER(FILE)]
fputc.__doc__ = \
"""int fputc(int p1, FILE * p2)
/usr/include/stdio.h:259"""
# /usr/include/stdio.h 260
fputs = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fputs
fputs.restype = c_int
# fputs(p1, p2)
fputs.argtypes = [STRING, POINTER(FILE)]
fputs.__doc__ = \
"""int fputs(unknown * p1, FILE * p2)
/usr/include/stdio.h:260"""
# /usr/include/stdio.h 261
fread = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fread
fread.restype = size_t
# fread(p1, p2, p3, p4)
fread.argtypes = [c_void_p, size_t, size_t, POINTER(FILE)]
fread.__doc__ = \
"""size_t fread(void * p1, size_t p2, size_t p3, FILE * p4)
/usr/include/stdio.h:261"""
# /usr/include/stdio.h 263
freopen = _libraries['/usr/local/cuda/lib/libcufft.dylib'].freopen
freopen.restype = POINTER(FILE)
# freopen(p1, p2, p3)
freopen.argtypes = [STRING, STRING, POINTER(FILE)]
freopen.__doc__ = \
"""FILE * freopen(unknown * p1, unknown * p2, FILE * p3)
/usr/include/stdio.h:263"""
# /usr/include/stdio.h 264
fscanf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fscanf
fscanf.restype = c_int
# fscanf(p1, p2)
fscanf.argtypes = [POINTER(FILE), STRING]
fscanf.__doc__ = \
"""int fscanf(FILE * p1, unknown * p2)
/usr/include/stdio.h:264"""
# /usr/include/stdio.h 265
fseek = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fseek
fseek.restype = c_int
# fseek(p1, p2, p3)
fseek.argtypes = [POINTER(FILE), c_long, c_int]
fseek.__doc__ = \
"""int fseek(FILE * p1, long int p2, int p3)
/usr/include/stdio.h:265"""
# /usr/include/stdio.h 266
fsetpos = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fsetpos
fsetpos.restype = c_int
# fsetpos(p1, p2)
fsetpos.argtypes = [POINTER(FILE), POINTER(fpos_t)]
fsetpos.__doc__ = \
"""int fsetpos(FILE * p1, unknown * p2)
/usr/include/stdio.h:266"""
# /usr/include/stdio.h 267
ftell = _libraries['/usr/local/cuda/lib/libcufft.dylib'].ftell
ftell.restype = c_long
# ftell(p1)
ftell.argtypes = [POINTER(FILE)]
ftell.__doc__ = \
"""long int ftell(FILE * p1)
/usr/include/stdio.h:267"""
# /usr/include/stdio.h 268
fwrite = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fwrite
fwrite.restype = size_t
# fwrite(p1, p2, p3, p4)
fwrite.argtypes = [c_void_p, size_t, size_t, POINTER(FILE)]
fwrite.__doc__ = \
"""size_t fwrite(unknown * p1, size_t p2, size_t p3, FILE * p4)
/usr/include/stdio.h:268"""
# /usr/include/stdio.h 269
getc = _libraries['/usr/local/cuda/lib/libcufft.dylib'].getc
getc.restype = c_int
# getc(p1)
getc.argtypes = [POINTER(FILE)]
getc.__doc__ = \
"""int getc(FILE * p1)
/usr/include/stdio.h:269"""
# /usr/include/stdio.h 270
getchar = _libraries['/usr/local/cuda/lib/libcufft.dylib'].getchar
getchar.restype = c_int
# getchar()
getchar.argtypes = []
getchar.__doc__ = \
"""int getchar()
/usr/include/stdio.h:270"""
# /usr/include/stdio.h 271
gets = _libraries['/usr/local/cuda/lib/libcufft.dylib'].gets
gets.restype = STRING
# gets(p1)
gets.argtypes = [STRING]
gets.__doc__ = \
"""char * gets(char * p1)
/usr/include/stdio.h:271"""
sys_nerr = (c_int).in_dll(_libraries['/usr/local/cuda/lib/libcufft.dylib'], 'sys_nerr')
sys_errlist = (STRING * 0).in_dll(_libraries['/usr/local/cuda/lib/libcufft.dylib'], 'sys_errlist')
# /usr/include/stdio.h 276
perror = _libraries['/usr/local/cuda/lib/libcufft.dylib'].perror
perror.restype = None
# perror(p1)
perror.argtypes = [STRING]
perror.__doc__ = \
"""void perror(unknown * p1)
/usr/include/stdio.h:276"""
# /usr/include/stdio.h 277
printf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].printf
printf.restype = c_int
# printf(p1)
printf.argtypes = [STRING]
printf.__doc__ = \
"""int printf(unknown * p1)
/usr/include/stdio.h:277"""
# /usr/include/stdio.h 278
putc = _libraries['/usr/local/cuda/lib/libcufft.dylib'].putc
putc.restype = c_int
# putc(p1, p2)
putc.argtypes = [c_int, POINTER(FILE)]
putc.__doc__ = \
"""int putc(int p1, FILE * p2)
/usr/include/stdio.h:278"""
# /usr/include/stdio.h 279
putchar = _libraries['/usr/local/cuda/lib/libcufft.dylib'].putchar
putchar.restype = c_int
# putchar(p1)
putchar.argtypes = [c_int]
putchar.__doc__ = \
"""int putchar(int p1)
/usr/include/stdio.h:279"""
# /usr/include/stdio.h 280
puts = _libraries['/usr/local/cuda/lib/libcufft.dylib'].puts
puts.restype = c_int
# puts(p1)
puts.argtypes = [STRING]
puts.__doc__ = \
"""int puts(unknown * p1)
/usr/include/stdio.h:280"""
# /usr/include/stdio.h 281
remove = _libraries['/usr/local/cuda/lib/libcufft.dylib'].remove
remove.restype = c_int
# remove(p1)
remove.argtypes = [STRING]
remove.__doc__ = \
"""int remove(unknown * p1)
/usr/include/stdio.h:281"""
# /usr/include/stdio.h 282
rename = _libraries['/usr/local/cuda/lib/libcufft.dylib'].rename
rename.restype = c_int
# rename(p1, p2)
rename.argtypes = [STRING, STRING]
rename.__doc__ = \
"""int rename(unknown * p1, unknown * p2)
/usr/include/stdio.h:282"""
# /usr/include/stdio.h 283
rewind = _libraries['/usr/local/cuda/lib/libcufft.dylib'].rewind
rewind.restype = None
# rewind(p1)
rewind.argtypes = [POINTER(FILE)]
rewind.__doc__ = \
"""void rewind(FILE * p1)
/usr/include/stdio.h:283"""
# /usr/include/stdio.h 284
scanf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].scanf
scanf.restype = c_int
# scanf(p1)
scanf.argtypes = [STRING]
scanf.__doc__ = \
"""int scanf(unknown * p1)
/usr/include/stdio.h:284"""
# /usr/include/stdio.h 285
setbuf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].setbuf
setbuf.restype = None
# setbuf(p1, p2)
setbuf.argtypes = [POINTER(FILE), STRING]
setbuf.__doc__ = \
"""void setbuf(FILE * p1, char * p2)
/usr/include/stdio.h:285"""
# /usr/include/stdio.h 286
setvbuf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].setvbuf
setvbuf.restype = c_int
# setvbuf(p1, p2, p3, p4)
setvbuf.argtypes = [POINTER(FILE), STRING, c_int, size_t]
setvbuf.__doc__ = \
"""int setvbuf(FILE * p1, char * p2, int p3, size_t p4)
/usr/include/stdio.h:286"""
# /usr/include/stdio.h 287
sprintf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].sprintf
sprintf.restype = c_int
# sprintf(p1, p2)
sprintf.argtypes = [STRING, STRING]
sprintf.__doc__ = \
"""int sprintf(char * p1, unknown * p2)
/usr/include/stdio.h:287"""
# /usr/include/stdio.h 288
sscanf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].sscanf
sscanf.restype = c_int
# sscanf(p1, p2)
sscanf.argtypes = [STRING, STRING]
sscanf.__doc__ = \
"""int sscanf(unknown * p1, unknown * p2)
/usr/include/stdio.h:288"""
# /usr/include/stdio.h 289
tmpfile = _libraries['/usr/local/cuda/lib/libcufft.dylib'].tmpfile
tmpfile.restype = POINTER(FILE)
# tmpfile()
tmpfile.argtypes = []
tmpfile.__doc__ = \
"""FILE * tmpfile()
/usr/include/stdio.h:289"""
# /usr/include/stdio.h 290
tmpnam = _libraries['/usr/local/cuda/lib/libcufft.dylib'].tmpnam
tmpnam.restype = STRING
# tmpnam(p1)
tmpnam.argtypes = [STRING]
tmpnam.__doc__ = \
"""char * tmpnam(char * p1)
/usr/include/stdio.h:290"""
# /usr/include/stdio.h 291
ungetc = _libraries['/usr/local/cuda/lib/libcufft.dylib'].ungetc
ungetc.restype = c_int
# ungetc(p1, p2)
ungetc.argtypes = [c_int, POINTER(FILE)]
ungetc.__doc__ = \
"""int ungetc(int p1, FILE * p2)
/usr/include/stdio.h:291"""
# /usr/include/stdio.h 292
vfprintf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].vfprintf
vfprintf.restype = c_int
# vfprintf(p1, p2, p3)
vfprintf.argtypes = [POINTER(FILE), STRING, va_list]
vfprintf.__doc__ = \
"""int vfprintf(FILE * p1, unknown * p2, va_list p3)
/usr/include/stdio.h:292"""
# /usr/include/stdio.h 293
vprintf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].vprintf
vprintf.restype = c_int
# vprintf(p1, p2)
vprintf.argtypes = [STRING, va_list]
vprintf.__doc__ = \
"""int vprintf(unknown * p1, va_list p2)
/usr/include/stdio.h:293"""
# /usr/include/stdio.h 294
vsprintf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].vsprintf
vsprintf.restype = c_int
# vsprintf(p1, p2, p3)
vsprintf.argtypes = [STRING, STRING, va_list]
vsprintf.__doc__ = \
"""int vsprintf(char * p1, unknown * p2, va_list p3)
/usr/include/stdio.h:294"""
# /usr/include/stdio.h 296
asprintf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].asprintf
asprintf.restype = c_int
# asprintf(p1, p2)
asprintf.argtypes = [POINTER(STRING), STRING]
asprintf.__doc__ = \
"""int asprintf(char * * p1, unknown * p2)
/usr/include/stdio.h:296"""
# /usr/include/stdio.h 297
vasprintf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].vasprintf
vasprintf.restype = c_int
# vasprintf(p1, p2, p3)
vasprintf.argtypes = [POINTER(STRING), STRING, va_list]
vasprintf.__doc__ = \
"""int vasprintf(char * * p1, unknown * p2, va_list p3)
/usr/include/stdio.h:297"""
# /usr/include/stdio.h 308
ctermid = _libraries['/usr/local/cuda/lib/libcufft.dylib'].ctermid
ctermid.restype = STRING
# ctermid(p1)
ctermid.argtypes = [STRING]
ctermid.__doc__ = \
"""char * ctermid(char * p1)
/usr/include/stdio.h:308"""
# /usr/include/stdio.h 310
ctermid_r = _libraries['/usr/local/cuda/lib/libcufft.dylib'].ctermid_r
ctermid_r.restype = STRING
# ctermid_r(p1)
ctermid_r.argtypes = [STRING]
ctermid_r.__doc__ = \
"""char * ctermid_r(char * p1)
/usr/include/stdio.h:310"""
# /usr/include/stdio.h 312
fdopen = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fdopen
fdopen.restype = POINTER(FILE)
# fdopen(p1, p2)
fdopen.argtypes = [c_int, STRING]
fdopen.__doc__ = \
"""FILE * fdopen(int p1, unknown * p2)
/usr/include/stdio.h:312"""
# /usr/include/stdio.h 314
fgetln = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fgetln
fgetln.restype = STRING
# fgetln(p1, p2)
fgetln.argtypes = [POINTER(FILE), POINTER(size_t)]
fgetln.__doc__ = \
"""char * fgetln(FILE * p1, size_t * p2)
/usr/include/stdio.h:314"""
# /usr/include/stdio.h 316
fileno = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fileno
fileno.restype = c_int
# fileno(p1)
fileno.argtypes = [POINTER(FILE)]
fileno.__doc__ = \
"""int fileno(FILE * p1)
/usr/include/stdio.h:316"""
# /usr/include/stdio.h 317
flockfile = _libraries['/usr/local/cuda/lib/libcufft.dylib'].flockfile
flockfile.restype = None
# flockfile(p1)
flockfile.argtypes = [POINTER(FILE)]
flockfile.__doc__ = \
"""void flockfile(FILE * p1)
/usr/include/stdio.h:317"""
# /usr/include/stdio.h 320
fmtcheck = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fmtcheck
fmtcheck.restype = STRING
# fmtcheck(p1, p2)
fmtcheck.argtypes = [STRING, STRING]
fmtcheck.__doc__ = \
"""unknown * fmtcheck(unknown * p1, unknown * p2)
/usr/include/stdio.h:320"""
# /usr/include/stdio.h 321
fpurge = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fpurge
fpurge.restype = c_int
# fpurge(p1)
fpurge.argtypes = [POINTER(FILE)]
fpurge.__doc__ = \
"""int fpurge(FILE * p1)
/usr/include/stdio.h:321"""
# /usr/include/stdio.h 323
fseeko = _libraries['/usr/local/cuda/lib/libcufft.dylib'].fseeko
fseeko.restype = c_int
# fseeko(p1, p2, p3)
fseeko.argtypes = [POINTER(FILE), off_t, c_int]
fseeko.__doc__ = \
"""int fseeko(FILE * p1, off_t p2, int p3)
/usr/include/stdio.h:323"""
# /usr/include/stdio.h 324
ftello = _libraries['/usr/local/cuda/lib/libcufft.dylib'].ftello
ftello.restype = off_t
# ftello(p1)
ftello.argtypes = [POINTER(FILE)]
ftello.__doc__ = \
"""off_t ftello(FILE * p1)
/usr/include/stdio.h:324"""
# /usr/include/stdio.h 325
ftrylockfile = _libraries['/usr/local/cuda/lib/libcufft.dylib'].ftrylockfile
ftrylockfile.restype = c_int
# ftrylockfile(p1)
ftrylockfile.argtypes = [POINTER(FILE)]
ftrylockfile.__doc__ = \
"""int ftrylockfile(FILE * p1)
/usr/include/stdio.h:325"""
# /usr/include/stdio.h 326
funlockfile = _libraries['/usr/local/cuda/lib/libcufft.dylib'].funlockfile
funlockfile.restype = None
# funlockfile(p1)
funlockfile.argtypes = [POINTER(FILE)]
funlockfile.__doc__ = \
"""void funlockfile(FILE * p1)
/usr/include/stdio.h:326"""
# /usr/include/stdio.h 327
getc_unlocked = _libraries['/usr/local/cuda/lib/libcufft.dylib'].getc_unlocked
getc_unlocked.restype = c_int
# getc_unlocked(p1)
getc_unlocked.argtypes = [POINTER(FILE)]
getc_unlocked.__doc__ = \
"""int getc_unlocked(FILE * p1)
/usr/include/stdio.h:327"""
# /usr/include/stdio.h 328
getchar_unlocked = _libraries['/usr/local/cuda/lib/libcufft.dylib'].getchar_unlocked
getchar_unlocked.restype = c_int
# getchar_unlocked()
getchar_unlocked.argtypes = []
getchar_unlocked.__doc__ = \
"""int getchar_unlocked()
/usr/include/stdio.h:328"""
# /usr/include/stdio.h 330
getw = _libraries['/usr/local/cuda/lib/libcufft.dylib'].getw
getw.restype = c_int
# getw(p1)
getw.argtypes = [POINTER(FILE)]
getw.__doc__ = \
"""int getw(FILE * p1)
/usr/include/stdio.h:330"""
# /usr/include/stdio.h 332
pclose = _libraries['/usr/local/cuda/lib/libcufft.dylib'].pclose
pclose.restype = c_int
# pclose(p1)
pclose.argtypes = [POINTER(FILE)]
pclose.__doc__ = \
"""int pclose(FILE * p1)
/usr/include/stdio.h:332"""
# /usr/include/stdio.h 333
popen = _libraries['/usr/local/cuda/lib/libcufft.dylib'].popen
popen.restype = POINTER(FILE)
# popen(p1, p2)
popen.argtypes = [STRING, STRING]
popen.__doc__ = \
"""FILE * popen(unknown * p1, unknown * p2)
/usr/include/stdio.h:333"""
# /usr/include/stdio.h 334
putc_unlocked = _libraries['/usr/local/cuda/lib/libcufft.dylib'].putc_unlocked
putc_unlocked.restype = c_int
# putc_unlocked(p1, p2)
putc_unlocked.argtypes = [c_int, POINTER(FILE)]
putc_unlocked.__doc__ = \
"""int putc_unlocked(int p1, FILE * p2)
/usr/include/stdio.h:334"""
# /usr/include/stdio.h 335
putchar_unlocked = _libraries['/usr/local/cuda/lib/libcufft.dylib'].putchar_unlocked
putchar_unlocked.restype = c_int
# putchar_unlocked(p1)
putchar_unlocked.argtypes = [c_int]
putchar_unlocked.__doc__ = \
"""int putchar_unlocked(int p1)
/usr/include/stdio.h:335"""
# /usr/include/stdio.h 337
putw = _libraries['/usr/local/cuda/lib/libcufft.dylib'].putw
putw.restype = c_int
# putw(p1, p2)
putw.argtypes = [c_int, POINTER(FILE)]
putw.__doc__ = \
"""int putw(int p1, FILE * p2)
/usr/include/stdio.h:337"""
# /usr/include/stdio.h 338
setbuffer = _libraries['/usr/local/cuda/lib/libcufft.dylib'].setbuffer
setbuffer.restype = None
# setbuffer(p1, p2, p3)
setbuffer.argtypes = [POINTER(FILE), STRING, c_int]
setbuffer.__doc__ = \
"""void setbuffer(FILE * p1, char * p2, int p3)
/usr/include/stdio.h:338"""
# /usr/include/stdio.h 339
setlinebuf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].setlinebuf
setlinebuf.restype = c_int
# setlinebuf(p1)
setlinebuf.argtypes = [POINTER(FILE)]
setlinebuf.__doc__ = \
"""int setlinebuf(FILE * p1)
/usr/include/stdio.h:339"""
# /usr/include/stdio.h 341
snprintf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].snprintf
snprintf.restype = c_int
# snprintf(p1, p2, p3)
snprintf.argtypes = [STRING, size_t, STRING]
snprintf.__doc__ = \
"""int snprintf(char * p1, size_t p2, unknown * p3)
/usr/include/stdio.h:341"""
# /usr/include/stdio.h 342
tempnam = _libraries['/usr/local/cuda/lib/libcufft.dylib'].tempnam
tempnam.restype = STRING
# tempnam(p1, p2)
tempnam.argtypes = [STRING, STRING]
tempnam.__doc__ = \
"""char * tempnam(unknown * p1, unknown * p2)
/usr/include/stdio.h:342"""
# /usr/include/stdio.h 343
vfscanf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].vfscanf
vfscanf.restype = c_int
# vfscanf(p1, p2, p3)
vfscanf.argtypes = [POINTER(FILE), STRING, va_list]
vfscanf.__doc__ = \
"""int vfscanf(FILE * p1, unknown * p2, va_list p3)
/usr/include/stdio.h:343"""
# /usr/include/stdio.h 344
vscanf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].vscanf
vscanf.restype = c_int
# vscanf(p1, p2)
vscanf.argtypes = [STRING, va_list]
vscanf.__doc__ = \
"""int vscanf(unknown * p1, va_list p2)
/usr/include/stdio.h:344"""
# /usr/include/stdio.h 345
vsnprintf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].vsnprintf
vsnprintf.restype = c_int
# vsnprintf(p1, p2, p3, p4)
vsnprintf.argtypes = [STRING, size_t, STRING, va_list]
vsnprintf.__doc__ = \
"""int vsnprintf(char * p1, size_t p2, unknown * p3, va_list p4)
/usr/include/stdio.h:345"""
# /usr/include/stdio.h 346
vsscanf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].vsscanf
vsscanf.restype = c_int
# vsscanf(p1, p2, p3)
vsscanf.argtypes = [STRING, STRING, va_list]
vsscanf.__doc__ = \
"""int vsscanf(unknown * p1, unknown * p2, va_list p3)
/usr/include/stdio.h:346"""
# /usr/include/stdio.h 361
funopen = _libraries['/usr/local/cuda/lib/libcufft.dylib'].funopen
funopen.restype = POINTER(FILE)
# funopen(p1, p2, p3, p4, p5)
funopen.argtypes = [c_void_p, CFUNCTYPE(c_int, c_void_p, STRING, c_int), CFUNCTYPE(c_int, c_void_p, STRING, c_int), CFUNCTYPE(fpos_t, c_void_p, fpos_t, c_int), CFUNCTYPE(c_int, c_void_p)]
funopen.__doc__ = \
"""FILE * funopen(unknown * p1, unknown * p2, unknown * p3, unknown * p4, unknown * p5)
/usr/include/stdio.h:361"""
# /usr/include/stdio.h 372
__srget = _libraries['/usr/local/cuda/lib/libcufft.dylib'].__srget
__srget.restype = c_int
# __srget(p1)
__srget.argtypes = [POINTER(FILE)]
__srget.__doc__ = \
"""int __srget(FILE * p1)
/usr/include/stdio.h:372"""
# /usr/include/stdio.h 373
__svfscanf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].__svfscanf
__svfscanf.restype = c_int
# __svfscanf(p1, p2, p3)
__svfscanf.argtypes = [POINTER(FILE), STRING, va_list]
__svfscanf.__doc__ = \
"""int __svfscanf(FILE * p1, unknown * p2, va_list p3)
/usr/include/stdio.h:373"""
# /usr/include/stdio.h 374
__swbuf = _libraries['/usr/local/cuda/lib/libcufft.dylib'].__swbuf
__swbuf.restype = c_int
# __swbuf(p1, p2)
__swbuf.argtypes = [c_int, POINTER(FILE)]
__swbuf.__doc__ = \
"""int __swbuf(int p1, FILE * p2)
/usr/include/stdio.h:374"""
# /usr/include/sys/_types.h 59
class __darwin_pthread_handler_rec(Structure):
    pass
__darwin_pthread_handler_rec._fields_ = [
    # /usr/include/sys/_types.h 59
    ('__routine', CFUNCTYPE(None, c_void_p)),
    ('__arg', c_void_p),
    ('__next', POINTER(__darwin_pthread_handler_rec)),
]
# /usr/include/sys/_types.h 64
class _opaque_pthread_attr_t(Structure):
    pass
_opaque_pthread_attr_t._fields_ = [
    # /usr/include/sys/_types.h 64
    ('__sig', c_long),
    ('__opaque', c_char * 36),
]
# /usr/include/sys/_types.h 65
class _opaque_pthread_cond_t(Structure):
    pass
_opaque_pthread_cond_t._fields_ = [
    # /usr/include/sys/_types.h 65
    ('__sig', c_long),
    ('__opaque', c_char * 24),
]
# /usr/include/sys/_types.h 66
class _opaque_pthread_condattr_t(Structure):
    pass
_opaque_pthread_condattr_t._fields_ = [
    # /usr/include/sys/_types.h 66
    ('__sig', c_long),
    ('__opaque', c_char * 4),
]
# /usr/include/sys/_types.h 67
class _opaque_pthread_mutex_t(Structure):
    pass
_opaque_pthread_mutex_t._fields_ = [
    # /usr/include/sys/_types.h 67
    ('__sig', c_long),
    ('__opaque', c_char * 40),
]
# /usr/include/sys/_types.h 68
class _opaque_pthread_mutexattr_t(Structure):
    pass
_opaque_pthread_mutexattr_t._fields_ = [
    # /usr/include/sys/_types.h 68
    ('__sig', c_long),
    ('__opaque', c_char * 8),
]
# /usr/include/sys/_types.h 69
class _opaque_pthread_once_t(Structure):
    pass
_opaque_pthread_once_t._fields_ = [
    # /usr/include/sys/_types.h 69
    ('__sig', c_long),
    ('__opaque', c_char * 4),
]
# /usr/include/sys/_types.h 70
class _opaque_pthread_rwlock_t(Structure):
    pass
_opaque_pthread_rwlock_t._fields_ = [
    # /usr/include/sys/_types.h 70
    ('__sig', c_long),
    ('__opaque', c_char * 124),
]
# /usr/include/sys/_types.h 71
class _opaque_pthread_rwlockattr_t(Structure):
    pass
_opaque_pthread_rwlockattr_t._fields_ = [
    # /usr/include/sys/_types.h 71
    ('__sig', c_long),
    ('__opaque', c_char * 12),
]
# /usr/include/sys/_types.h 72
class _opaque_pthread_t(Structure):
    pass
_opaque_pthread_t._fields_ = [
    # /usr/include/sys/_types.h 72
    ('__sig', c_long),
    ('__cleanup_stack', POINTER(__darwin_pthread_handler_rec)),
    ('__opaque', c_char * 596),
]
__darwin_blkcnt_t = __int64_t
__darwin_blksize_t = __int32_t
__darwin_dev_t = __int32_t
__darwin_fsblkcnt_t = c_uint
__darwin_fsfilcnt_t = c_uint
__darwin_gid_t = __uint32_t
__darwin_id_t = __uint32_t
__darwin_ino64_t = __uint64_t
__darwin_ino_t = __uint32_t
__darwin_mach_port_name_t = __darwin_natural_t
__darwin_mach_port_t = __darwin_mach_port_name_t
__darwin_mode_t = __uint16_t
__darwin_pid_t = __int32_t
__darwin_pthread_attr_t = _opaque_pthread_attr_t
__darwin_pthread_cond_t = _opaque_pthread_cond_t
__darwin_pthread_condattr_t = _opaque_pthread_condattr_t
__darwin_pthread_key_t = c_ulong
__darwin_pthread_mutex_t = _opaque_pthread_mutex_t
__darwin_pthread_mutexattr_t = _opaque_pthread_mutexattr_t
__darwin_pthread_once_t = _opaque_pthread_once_t
__darwin_pthread_rwlock_t = _opaque_pthread_rwlock_t
__darwin_pthread_rwlockattr_t = _opaque_pthread_rwlockattr_t
__darwin_pthread_t = POINTER(_opaque_pthread_t)
__darwin_sigset_t = __uint32_t
__darwin_suseconds_t = __int32_t
__darwin_uid_t = __uint32_t
__darwin_useconds_t = __uint32_t
__darwin_uuid_t = c_ubyte * 16
# /usr/local/cuda/include/vector_types.h 269
class float2(Structure):
    pass
cuFloatComplex = float2
# /usr/local/cuda/include/vector_types.h 293
class double2(Structure):
    pass
cuDoubleComplex = double2
cuComplex = cuFloatComplex

# values for enumeration 'cufftResult_t'
cufftResult_t = c_int # enum
cufftResult = cufftResult_t
cufftHandle = c_uint
cufftReal = c_float
cufftComplex = cuComplex

# values for enumeration 'cufftType_t'
cufftType_t = c_int # enum
cufftType = cufftType_t
# /usr/local/cuda/include/cufft.h 99
cufftPlan1d = _libraries['/usr/local/cuda/lib/libcufft.dylib'].cufftPlan1d
cufftPlan1d.restype = cufftResult
# cufftPlan1d(plan, nx, type, batch)
cufftPlan1d.argtypes = [POINTER(cufftHandle), c_int, cufftType, c_int]
cufftPlan1d.__doc__ = \
"""cufftResult cufftPlan1d(cufftHandle * plan, int nx, cufftType type, int batch)
/usr/local/cuda/include/cufft.h:99"""
# /usr/local/cuda/include/cufft.h 103
cufftPlan2d = _libraries['/usr/local/cuda/lib/libcufft.dylib'].cufftPlan2d
cufftPlan2d.restype = cufftResult
# cufftPlan2d(plan, nx, ny, type)
cufftPlan2d.argtypes = [POINTER(cufftHandle), c_int, c_int, cufftType]
cufftPlan2d.__doc__ = \
"""cufftResult cufftPlan2d(cufftHandle * plan, int nx, int ny, cufftType type)
/usr/local/cuda/include/cufft.h:103"""
# /usr/local/cuda/include/cufft.h 107
cufftPlan3d = _libraries['/usr/local/cuda/lib/libcufft.dylib'].cufftPlan3d
cufftPlan3d.restype = cufftResult
# cufftPlan3d(plan, nx, ny, nz, type)
cufftPlan3d.argtypes = [POINTER(cufftHandle), c_int, c_int, c_int, cufftType]
cufftPlan3d.__doc__ = \
"""cufftResult cufftPlan3d(cufftHandle * plan, int nx, int ny, int nz, cufftType type)
/usr/local/cuda/include/cufft.h:107"""
# /usr/local/cuda/include/cufft.h 109
cufftDestroy = _libraries['/usr/local/cuda/lib/libcufft.dylib'].cufftDestroy
cufftDestroy.restype = cufftResult
# cufftDestroy(plan)
cufftDestroy.argtypes = [cufftHandle]
cufftDestroy.__doc__ = \
"""cufftResult cufftDestroy(cufftHandle plan)
/usr/local/cuda/include/cufft.h:109"""
# /usr/local/cuda/include/cufft.h 114
cufftExecC2C = _libraries['/usr/local/cuda/lib/libcufft.dylib'].cufftExecC2C
cufftExecC2C.restype = cufftResult
# cufftExecC2C(plan, idata, odata, direction)
cufftExecC2C.argtypes = [cufftHandle, POINTER(cufftComplex), POINTER(cufftComplex), c_int]
cufftExecC2C.__doc__ = \
"""cufftResult cufftExecC2C(cufftHandle plan, cufftComplex * idata, cufftComplex * odata, int direction)
/usr/local/cuda/include/cufft.h:114"""
# /usr/local/cuda/include/cufft.h 118
cufftExecR2C = _libraries['/usr/local/cuda/lib/libcufft.dylib'].cufftExecR2C
cufftExecR2C.restype = cufftResult
# cufftExecR2C(plan, idata, odata)
cufftExecR2C.argtypes = [cufftHandle, POINTER(cufftReal), POINTER(cufftComplex)]
cufftExecR2C.__doc__ = \
"""cufftResult cufftExecR2C(cufftHandle plan, cufftReal * idata, cufftComplex * odata)
/usr/local/cuda/include/cufft.h:118"""
# /usr/local/cuda/include/cufft.h 122
cufftExecC2R = _libraries['/usr/local/cuda/lib/libcufft.dylib'].cufftExecC2R
cufftExecC2R.restype = cufftResult
# cufftExecC2R(plan, idata, odata)
cufftExecC2R.argtypes = [cufftHandle, POINTER(cufftComplex), POINTER(cufftReal)]
cufftExecC2R.__doc__ = \
"""cufftResult cufftExecC2R(cufftHandle plan, cufftComplex * idata, cufftReal * odata)
/usr/local/cuda/include/cufft.h:122"""
# /usr/local/cuda/include/vector_types.h 55
class char1(Structure):
    pass
char1._fields_ = [
    # /usr/local/cuda/include/vector_types.h 55
    ('x', c_byte),
]
# /usr/local/cuda/include/vector_types.h 61
class uchar1(Structure):
    pass
uchar1._fields_ = [
    # /usr/local/cuda/include/vector_types.h 61
    ('x', c_ubyte),
]
# /usr/local/cuda/include/vector_types.h 67
class char2(Structure):
    pass
char2._fields_ = [
    # /usr/local/cuda/include/vector_types.h 67
    ('x', c_byte),
    ('y', c_byte),
]
# /usr/local/cuda/include/vector_types.h 73
class uchar2(Structure):
    pass
uchar2._fields_ = [
    # /usr/local/cuda/include/vector_types.h 73
    ('x', c_ubyte),
    ('y', c_ubyte),
]
# /usr/local/cuda/include/vector_types.h 79
class char3(Structure):
    pass
char3._fields_ = [
    # /usr/local/cuda/include/vector_types.h 79
    ('x', c_byte),
    ('y', c_byte),
    ('z', c_byte),
]
# /usr/local/cuda/include/vector_types.h 85
class uchar3(Structure):
    pass
uchar3._fields_ = [
    # /usr/local/cuda/include/vector_types.h 85
    ('x', c_ubyte),
    ('y', c_ubyte),
    ('z', c_ubyte),
]
# /usr/local/cuda/include/vector_types.h 91
class char4(Structure):
    pass
char4._fields_ = [
    # /usr/local/cuda/include/vector_types.h 91
    ('x', c_byte),
    ('y', c_byte),
    ('z', c_byte),
    ('w', c_byte),
]
# /usr/local/cuda/include/vector_types.h 97
class uchar4(Structure):
    pass
uchar4._fields_ = [
    # /usr/local/cuda/include/vector_types.h 97
    ('x', c_ubyte),
    ('y', c_ubyte),
    ('z', c_ubyte),
    ('w', c_ubyte),
]
# /usr/local/cuda/include/vector_types.h 103
class short1(Structure):
    pass
short1._fields_ = [
    # /usr/local/cuda/include/vector_types.h 103
    ('x', c_short),
]
# /usr/local/cuda/include/vector_types.h 109
class ushort1(Structure):
    pass
ushort1._fields_ = [
    # /usr/local/cuda/include/vector_types.h 109
    ('x', c_ushort),
]
# /usr/local/cuda/include/vector_types.h 115
class short2(Structure):
    pass
short2._fields_ = [
    # /usr/local/cuda/include/vector_types.h 115
    ('x', c_short),
    ('y', c_short),
]
# /usr/local/cuda/include/vector_types.h 121
class ushort2(Structure):
    pass
ushort2._fields_ = [
    # /usr/local/cuda/include/vector_types.h 121
    ('x', c_ushort),
    ('y', c_ushort),
]
# /usr/local/cuda/include/vector_types.h 127
class short3(Structure):
    pass
short3._fields_ = [
    # /usr/local/cuda/include/vector_types.h 127
    ('x', c_short),
    ('y', c_short),
    ('z', c_short),
]
# /usr/local/cuda/include/vector_types.h 133
class ushort3(Structure):
    pass
ushort3._fields_ = [
    # /usr/local/cuda/include/vector_types.h 133
    ('x', c_ushort),
    ('y', c_ushort),
    ('z', c_ushort),
]
# /usr/local/cuda/include/vector_types.h 139
class short4(Structure):
    pass
short4._fields_ = [
    # /usr/local/cuda/include/vector_types.h 139
    ('x', c_short),
    ('y', c_short),
    ('z', c_short),
    ('w', c_short),
]
# /usr/local/cuda/include/vector_types.h 145
class ushort4(Structure):
    pass
ushort4._fields_ = [
    # /usr/local/cuda/include/vector_types.h 145
    ('x', c_ushort),
    ('y', c_ushort),
    ('z', c_ushort),
    ('w', c_ushort),
]
# /usr/local/cuda/include/vector_types.h 151
class int1(Structure):
    pass
int1._fields_ = [
    # /usr/local/cuda/include/vector_types.h 151
    ('x', c_int),
]
# /usr/local/cuda/include/vector_types.h 157
class uint1(Structure):
    pass
uint1._fields_ = [
    # /usr/local/cuda/include/vector_types.h 157
    ('x', c_uint),
]
# /usr/local/cuda/include/vector_types.h 163
class int2(Structure):
    pass
int2._fields_ = [
    # /usr/local/cuda/include/vector_types.h 163
    ('x', c_int),
    ('y', c_int),
]
# /usr/local/cuda/include/vector_types.h 169
class uint2(Structure):
    pass
uint2._fields_ = [
    # /usr/local/cuda/include/vector_types.h 169
    ('x', c_uint),
    ('y', c_uint),
]
# /usr/local/cuda/include/vector_types.h 175
class int3(Structure):
    pass
int3._fields_ = [
    # /usr/local/cuda/include/vector_types.h 175
    ('x', c_int),
    ('y', c_int),
    ('z', c_int),
]
# /usr/local/cuda/include/vector_types.h 181
class uint3(Structure):
    pass
uint3._fields_ = [
    # /usr/local/cuda/include/vector_types.h 181
    ('x', c_uint),
    ('y', c_uint),
    ('z', c_uint),
]
# /usr/local/cuda/include/vector_types.h 187
class int4(Structure):
    pass
int4._fields_ = [
    # /usr/local/cuda/include/vector_types.h 187
    ('x', c_int),
    ('y', c_int),
    ('z', c_int),
    ('w', c_int),
]
# /usr/local/cuda/include/vector_types.h 193
class uint4(Structure):
    pass
uint4._fields_ = [
    # /usr/local/cuda/include/vector_types.h 193
    ('x', c_uint),
    ('y', c_uint),
    ('z', c_uint),
    ('w', c_uint),
]
# /usr/local/cuda/include/vector_types.h 199
class long1(Structure):
    pass
long1._fields_ = [
    # /usr/local/cuda/include/vector_types.h 199
    ('x', c_long),
]
# /usr/local/cuda/include/vector_types.h 205
class ulong1(Structure):
    pass
ulong1._fields_ = [
    # /usr/local/cuda/include/vector_types.h 205
    ('x', c_ulong),
]
# /usr/local/cuda/include/vector_types.h 217
class long2(Structure):
    pass
long2._fields_ = [
    # /usr/local/cuda/include/vector_types.h 217
    ('x', c_long),
    ('y', c_long),
]
# /usr/local/cuda/include/vector_types.h 229
class ulong2(Structure):
    pass
ulong2._fields_ = [
    # /usr/local/cuda/include/vector_types.h 229
    ('x', c_ulong),
    ('y', c_ulong),
]
# /usr/local/cuda/include/vector_types.h 237
class long3(Structure):
    pass
long3._fields_ = [
    # /usr/local/cuda/include/vector_types.h 237
    ('x', c_long),
    ('y', c_long),
    ('z', c_long),
]
# /usr/local/cuda/include/vector_types.h 243
class ulong3(Structure):
    pass
ulong3._fields_ = [
    # /usr/local/cuda/include/vector_types.h 243
    ('x', c_ulong),
    ('y', c_ulong),
    ('z', c_ulong),
]
# /usr/local/cuda/include/vector_types.h 249
class long4(Structure):
    pass
long4._fields_ = [
    # /usr/local/cuda/include/vector_types.h 249
    ('x', c_long),
    ('y', c_long),
    ('z', c_long),
    ('w', c_long),
]
# /usr/local/cuda/include/vector_types.h 255
class ulong4(Structure):
    pass
ulong4._fields_ = [
    # /usr/local/cuda/include/vector_types.h 255
    ('x', c_ulong),
    ('y', c_ulong),
    ('z', c_ulong),
    ('w', c_ulong),
]
# /usr/local/cuda/include/vector_types.h 263
class float1(Structure):
    pass
float1._fields_ = [
    # /usr/local/cuda/include/vector_types.h 263
    ('x', c_float),
]
float2._fields_ = [
    # /usr/local/cuda/include/vector_types.h 269
    ('x', c_float),
    ('y', c_float),
]
# /usr/local/cuda/include/vector_types.h 275
class float3(Structure):
    pass
float3._fields_ = [
    # /usr/local/cuda/include/vector_types.h 275
    ('x', c_float),
    ('y', c_float),
    ('z', c_float),
]
# /usr/local/cuda/include/vector_types.h 281
class float4(Structure):
    pass
float4._fields_ = [
    # /usr/local/cuda/include/vector_types.h 281
    ('x', c_float),
    ('y', c_float),
    ('z', c_float),
    ('w', c_float),
]
# /usr/local/cuda/include/vector_types.h 287
class double1(Structure):
    pass
double1._pack_ = 4
double1._fields_ = [
    # /usr/local/cuda/include/vector_types.h 287
    ('x', c_double),
]
double2._pack_ = 4
double2._fields_ = [
    # /usr/local/cuda/include/vector_types.h 293
    ('x', c_double),
    ('y', c_double),
]
# /usr/local/cuda/include/vector_types.h 391
class dim3(Structure):
    pass
dim3._fields_ = [
    # /usr/local/cuda/include/vector_types.h 391
]
__all__ = ['cbrtf', 'nearbyint', 'ctermid_r', 'fclose', 'cbrtl',
           '__darwin_time_t', 'acosl', 'expm1f', 'acosh', 'acosf',
           '_FP_SUPERNORMAL', 'log2f', 'fpos_t', 'log2l', 'ilogb',
           'cufftExecC2R', 'cufftExecC2C', 'scalbnf', 'getc_unlocked',
           'scalbnl', '__darwin_pthread_t', '_FP_ZERO',
           '__darwin_ssize_t', 'cufftType', '__darwin_sigset_t',
           'tanh', 'fgetln', 'round', 'ldexpl', 'cosf', '__uint64_t',
           'nexttoward', 'snprintf', 'cosl', 'cosh', '__nan', 'asin',
           'getchar_unlocked', 'nanl', '__darwin_uuid_t', 'nanf',
           'llroundl', 'modff', 'ldexpf', 'va_list', 'llroundf',
           'fmax', 'CUFFT_ALLOC_FAILED', 'copysign', 'sinl', 'drem',
           'fmaf', 'sinf', 'fmal', 'trunc', 'lroundf',
           'cuFloatComplex', 'popen', 'lroundl',
           '__darwin_useconds_t', 'cbrt', 'roundtol', 'printf',
           'getchar', '_opaque_pthread_rwlockattr_t', 'fdimf',
           'fdiml', 'uint4', 'uint1', 'uint3', 'nexttowardf',
           '__int8_t', 'nexttowardl', 'llrintl', 'llrintf', '_FP_NAN',
           'ftrylockfile', 'cufftType_t', 'erf', '__darwin_ino64_t',
           'CUFFT_EXEC_FAILED', '_FP_SUBNORMAL', 'off_t', 'fprintf',
           '__fpclassifyf', 'tan', '__fpclassifyd', 'feof',
           'clearerr', 'atanf', '__darwin_ino_t',
           '__darwin_pthread_rwlockattr_t', 'atanh', 'atanl',
           'rewind', 'CUFFT_SUCCESS', 'putc_unlocked', 'sin',
           'flockfile', 'vasprintf', 'funlockfile', 'cufftReal',
           '__darwin_off_t', '_opaque_pthread_t', 'atan2',
           '__stdoutp', '__srget', 'coshf',
           '__darwin_pthread_condattr_t', 'coshl', '__darwin_id_t',
           '__darwin_nl_item', 'FILE', 'y1', 'y0', 'cufftComplex',
           'short2', 'fwrite', '__darwin_dev_t', '_FP_NORMAL',
           'ulong4', 'ulong3', 'ulong2', 'ulong1', 'remquo', 'yn',
           'gets', '__darwin_ptrdiff_t', 'uchar1', '__int32_t',
           'uchar2', 'uchar4', 'modf', 'vsscanf',
           '__math_errhandling', '__stdinp', 'logf', 'logb', 'sinhf',
           'logl', '__darwin_socklen_t', '__darwin_intptr_t', 'sinhl',
           'atan', 'cufftPlan2d', 'sprintf', 'atan2l', 'vscanf',
           'atan2f', 'log2', 'asprintf', 'ferror', 'remainder',
           '__darwin_blkcnt_t', 'expm1', 'fseeko', 'putchar', 'erff',
           'erfc', 'copysignl', 'erfl', '__darwin_clock_t', 'short4',
           'short1', 'floorf', 'short3', 'rint', 'cufftPlan3d',
           'floorl', 'ldexp', 'copysignf', 'ushort1', 'pclose',
           'exp2', 'scanf', '__darwin_pthread_mutexattr_t',
           '__darwin_mode_t', 'fma', '__mbstate_t', 'nearbyintl',
           '__uint8_t', 'setbuffer', 'nearbyintf', 'llrint', 'fscanf',
           '__darwin_mbstate_t', 'expl', 'expf', 'vsnprintf', 'char1',
           'char3', 'char2', '__darwin_wctype_t', 'char4', 'fmtcheck',
           'CUFFT_INTERNAL_ERROR', 'frexpl', 'funopen', 'frexpf',
           '__darwin_va_list', 'significand', 'long3', 'long2',
           'long1', '__darwin_pthread_attr_t', 'long4', '__swbuf',
           'logbf', '__darwin_wint_t', 'logbl',
           '_opaque_pthread_rwlock_t', 'expm1l', 'scalb', 'exp',
           'setlinebuf', 'setvbuf', '__uint16_t', 'fpurge',
           '_opaque_pthread_condattr_t', 'putchar_unlocked',
           'CUFFT_SETUP_FAILED', 'fputc', '__fpclassify',
           '__darwin_gid_t', 'frexp', 'fputs', 'ushort2', 'ushort3',
           'ushort4', 'cufftDestroy', 'double2', 'double1', 'lgammaf',
           'tgamma', 'CUFFT_INVALID_SIZE', 'lgammal', 'ceil',
           'fileno', 'perror', 'remove', '__int16_t', 'nextafterl',
           'nextafterf', 'j0', 'j1', 'size_t', 'float4', 'float1',
           'float2', 'float3', '__sbuf', 'fgetpos', 'cuComplex',
           'erfcf', '__darwin_blksize_t', 'erfcl', 'scalbln',
           '__darwin_wchar_t', 'ilogbl', 'jn', 'CUFFT_R2C', 'ilogbf',
           'atanhl', 'cos', '_opaque_pthread_cond_t', 'atanhf',
           '__darwin_ct_rune_t', '__darwin_pthread_key_t', 'acoshf',
           'fmaxf', '__darwin_pthread_handler_rec', 'pow', 'double_t',
           'fmaxl', 'fabsl', 'sys_nerr', '__darwin_fsblkcnt_t',
           'cufftHandle', 'putw', 'puts', 'cufftResult_t', 'hypotl',
           'acoshl', 'fminf', 'putc', 'fminl', 'asinh',
           '__darwin_mach_port_t', 'asinl', 'asinf',
           '_opaque_pthread_mutex_t', 'tanl', 'truncl', 'scalblnf',
           'tanf', 'scalblnl', 'truncf', 'lgamma', 'vsprintf',
           'rename', 'log10l', 'log10f', 'CUFFT_C2R', 'dim3',
           '_FP_INFINITE', '__sFILE', 'CUFFT_C2C', 'fabs', 'getc',
           'sqrt', 'finite', 'nextafter', 'getw', '__sFILEX', 'ceilf',
           'ceill', '__darwin_pthread_cond_t', 'setbuf', '__int64_t',
           'powl', 'powf', 'fseek', 'rintf', 'rintl', 'fflush',
           'fabsf', 'lrintl', '__uint32_t', 'lrintf', 'tmpnam',
           '__darwin_fsfilcnt_t', 'scalbn', 'cufftExecR2C', 'float_t',
           '__svfscanf', 'cufftResult', 'freopen', 'modfl', 'tanhl',
           'tempnam', 'tmpfile', 'fgetc', 'tanhf', '__inff', 'hypot',
           'fgets', 'ctermid', 'exp2f', 'uchar3', 'exp2l', 'fsetpos',
           'CUFFT_INVALID_VALUE', 'ftell', '__darwin_wctrans_t',
           'log1pl', 'fmod', 'tgammal', 'log1pf', 'tgammaf', 'hypotf',
           '__stderrp', '__darwin_natural_t', '__darwin_size_t',
           'CUFFT_INVALID_TYPE', 'sys_errlist',
           '_opaque_pthread_mutexattr_t', 'signgam', 'fmin',
           'llround', 'acos', 'gamma', 'remquol', 'roundl', 'roundf',
           '__inf', '__darwin_pthread_mutex_t',
           '__darwin_pthread_rwlock_t', 'sqrtl', 'fopen',
           '__darwin_rune_t', 'sqrtf', 'log', 'fdopen', 'rinttol',
           'lround', '__darwin_suseconds_t',
           '__darwin_pthread_once_t', 'log10', 'remquof', 'vprintf',
           '__darwin_uid_t', 'int4', 'int1', 'vfprintf', 'int3',
           'int2', 'lrint', 'fdim', 'ungetc', 'log1p', 'sscanf',
           'cufftPlan1d', 'fread', 'ftello', '_opaque_pthread_once_t',
           'CUFFT_INVALID_PLAN', '__darwin_pid_t', 'floor', 'uint2',
           'nan', 'cuDoubleComplex', 'fmodf', 'vfscanf', 'fmodl',
           '__darwin_mach_port_name_t', 'remainderf', 'remainderl',
           'sinh', 'asinhf', '_opaque_pthread_attr_t', 'asinhl']
