test.o : test.cu \
    /usr/include/bits/wordsize.h \
    /usr/include/bits/types.h \
    /usr/include/sys/cdefs.h \
    /usr/lib/gcc/i486-linux-gnu/4.1.2/include/stdarg.h \
    ../../common/inc/cutil.h \
    /usr/include/gconv.h \
    /usr/include/_G_config.h \
    /usr/include/bits/typesizes.h \
    /usr/lib/gcc/i486-linux-gnu/4.1.2/include/stddef.h \
    /usr/include/stdio.h \
    /usr/include/bits/wchar.h \
    /usr/include/libio.h \
    /usr/include/gnu/stubs-32.h \
    /usr/include/gnu/stubs.h \
    /usr/include/bits/stdio_lim.h \
    /usr/include/wchar.h \
    /usr/include/bits/sys_errlist.h \
    /usr/include/bits/stdio.h \
    /usr/include/features.h
