#!/bin/tcsh -f

# Link all needed Intel routines into _vector.so
# thus avoiding later problems with dynamic loading

set src="vector"
set mkl="/opt/intel/mkl/10.0.1.014/lib/32"
set lib="$mkl/libmkl_intel.a $mkl/libmkl_intel_thread.a $mkl/libmkl_core.a $mkl/libguide.a -lpthread"
set flags="-static -fPIC -O2 -msse2 -malign-double"
gcc -c $flags $src.c
gcc -shared -o _$src.so $src.o $lib
strip -x _$src.so
rm *.o
