# generated by 'xml2py'
# flags 'cudart.xml -c -d -v -l cudart'
from ctypes import *
from cuda.utils import get_lib
c_longdouble = c_double

_libraries = {}
_libraries['cudart'] = get_lib('cudart')
STRING = c_char_p


cudaErrorInvalidTexture = 18
cudaErrorMixedDeviceExecution = 28
cudaErrorMemoryAllocation = 2
cudaAddressModeWrap = 0
cudaErrorInvalidTextureBinding = 19
cudaErrorInitializationError = 3
cudaErrorSynchronizationError = 25
cudaAddressModeClamp = 1
cudaMemcpyDeviceToHost = 2
cudaErrorInvalidChannelDescriptor = 20
cudaErrorLaunchFailure = 4
cudaFilterModePoint = 0
cudaErrorInvalidNormSetting = 27
cudaErrorInvalidSymbol = 13
cudaErrorInvalidMemcpyDirection = 21
cudaErrorMemoryValueTooLarge = 32
cudaErrorAddressOfConstant = 22
cudaErrorLaunchTimeout = 6
cudaErrorCudartUnloading = 29
cudaErrorTextureFetchFailed = 23
cudaErrorLaunchOutOfResources = 7
cudaErrorUnknown = 30
cudaErrorTextureNotBound = 24
cudaRoundNearest = 0
cudaErrorInvalidDeviceFunction = 8
cudaErrorInvalidFilterSetting = 26
cudaMemcpyDeviceToDevice = 3
cudaErrorNotYetImplemented = 31
cudaRoundZero = 1
cudaErrorInvalidConfiguration = 9
cudaRoundPosInf = 2
cudaErrorInvalidDevice = 10
cudaErrorInvalidResourceHandle = 33
cudaRoundMinInf = 3
cudaErrorInvalidValue = 11
cudaErrorPriorLaunchFailure = 5
cudaErrorNotReady = 34
cudaReadModeElementType = 0
cudaErrorInvalidPitchValue = 12
cudaReadModeNormalizedFloat = 1
cudaErrorSetOnActiveProcess = 36
cudaErrorMapBufferObjectFailed = 14
cudaChannelFormatKindSigned = 0
cudaErrorStartupFailure = 127
cudaMemcpyHostToDevice = 1
cudaErrorUnmapBufferObjectFailed = 15
cudaChannelFormatKindUnsigned = 1
cudaErrorApiFailureBase = 10000
cudaErrorInsufficientDriver = 35
cudaErrorInvalidHostPointer = 16
cudaChannelFormatKindFloat = 2
cudaSuccess = 0
cudaFilterModeLinear = 1
cudaMemcpyHostToHost = 0
cudaErrorInvalidDevicePointer = 17
cudaChannelFormatKindNone = 3
cudaErrorMissingConfiguration = 1
# ./my_CUDA2100_vector_types.h 55
class char1(Structure):
    pass
char1._fields_ = [
    # ./my_CUDA2100_vector_types.h 55
    ('x', c_byte),
]
# ./my_CUDA2100_vector_types.h 61
class uchar1(Structure):
    pass
uchar1._fields_ = [
    # ./my_CUDA2100_vector_types.h 61
    ('x', c_ubyte),
]
# ./my_CUDA2100_vector_types.h 67
class char2(Structure):
    pass
char2._fields_ = [
    # ./my_CUDA2100_vector_types.h 67
    ('x', c_byte),
    ('y', c_byte),
]
# ./my_CUDA2100_vector_types.h 73
class uchar2(Structure):
    pass
uchar2._fields_ = [
    # ./my_CUDA2100_vector_types.h 73
    ('x', c_ubyte),
    ('y', c_ubyte),
]
# ./my_CUDA2100_vector_types.h 79
class char3(Structure):
    pass
char3._fields_ = [
    # ./my_CUDA2100_vector_types.h 79
    ('x', c_byte),
    ('y', c_byte),
    ('z', c_byte),
]
# ./my_CUDA2100_vector_types.h 85
class uchar3(Structure):
    pass
uchar3._fields_ = [
    # ./my_CUDA2100_vector_types.h 85
    ('x', c_ubyte),
    ('y', c_ubyte),
    ('z', c_ubyte),
]
# ./my_CUDA2100_vector_types.h 91
class char4(Structure):
    pass
char4._fields_ = [
    # ./my_CUDA2100_vector_types.h 91
    ('x', c_byte),
    ('y', c_byte),
    ('z', c_byte),
    ('w', c_byte),
]
# ./my_CUDA2100_vector_types.h 97
class uchar4(Structure):
    pass
uchar4._fields_ = [
    # ./my_CUDA2100_vector_types.h 97
    ('x', c_ubyte),
    ('y', c_ubyte),
    ('z', c_ubyte),
    ('w', c_ubyte),
]
# ./my_CUDA2100_vector_types.h 103
class short1(Structure):
    pass
short1._fields_ = [
    # ./my_CUDA2100_vector_types.h 103
    ('x', c_short),
]
# ./my_CUDA2100_vector_types.h 109
class ushort1(Structure):
    pass
ushort1._fields_ = [
    # ./my_CUDA2100_vector_types.h 109
    ('x', c_ushort),
]
# ./my_CUDA2100_vector_types.h 115
class short2(Structure):
    pass
short2._fields_ = [
    # ./my_CUDA2100_vector_types.h 115
    ('x', c_short),
    ('y', c_short),
]
# ./my_CUDA2100_vector_types.h 121
class ushort2(Structure):
    pass
ushort2._fields_ = [
    # ./my_CUDA2100_vector_types.h 121
    ('x', c_ushort),
    ('y', c_ushort),
]
# ./my_CUDA2100_vector_types.h 127
class short3(Structure):
    pass
short3._fields_ = [
    # ./my_CUDA2100_vector_types.h 127
    ('x', c_short),
    ('y', c_short),
    ('z', c_short),
]
# ./my_CUDA2100_vector_types.h 133
class ushort3(Structure):
    pass
ushort3._fields_ = [
    # ./my_CUDA2100_vector_types.h 133
    ('x', c_ushort),
    ('y', c_ushort),
    ('z', c_ushort),
]
# ./my_CUDA2100_vector_types.h 139
class short4(Structure):
    pass
short4._fields_ = [
    # ./my_CUDA2100_vector_types.h 139
    ('x', c_short),
    ('y', c_short),
    ('z', c_short),
    ('w', c_short),
]
# ./my_CUDA2100_vector_types.h 145
class ushort4(Structure):
    pass
ushort4._fields_ = [
    # ./my_CUDA2100_vector_types.h 145
    ('x', c_ushort),
    ('y', c_ushort),
    ('z', c_ushort),
    ('w', c_ushort),
]
# ./my_CUDA2100_vector_types.h 151
class int1(Structure):
    pass
int1._fields_ = [
    # ./my_CUDA2100_vector_types.h 151
    ('x', c_int),
]
# ./my_CUDA2100_vector_types.h 157
class uint1(Structure):
    pass
uint1._fields_ = [
    # ./my_CUDA2100_vector_types.h 157
    ('x', c_uint),
]
# ./my_CUDA2100_vector_types.h 163
class int2(Structure):
    pass
int2._fields_ = [
    # ./my_CUDA2100_vector_types.h 163
    ('x', c_int),
    ('y', c_int),
]
# ./my_CUDA2100_vector_types.h 169
class uint2(Structure):
    pass
uint2._fields_ = [
    # ./my_CUDA2100_vector_types.h 169
    ('x', c_uint),
    ('y', c_uint),
]
# ./my_CUDA2100_vector_types.h 175
class int3(Structure):
    pass
int3._fields_ = [
    # ./my_CUDA2100_vector_types.h 175
    ('x', c_int),
    ('y', c_int),
    ('z', c_int),
]
# ./my_CUDA2100_vector_types.h 181
class uint3(Structure):
    pass
uint3._fields_ = [
    # ./my_CUDA2100_vector_types.h 181
    ('x', c_uint),
    ('y', c_uint),
    ('z', c_uint),
]
# ./my_CUDA2100_vector_types.h 187
class int4(Structure):
    pass
int4._fields_ = [
    # ./my_CUDA2100_vector_types.h 187
    ('x', c_int),
    ('y', c_int),
    ('z', c_int),
    ('w', c_int),
]
# ./my_CUDA2100_vector_types.h 193
class uint4(Structure):
    pass
uint4._fields_ = [
    # ./my_CUDA2100_vector_types.h 193
    ('x', c_uint),
    ('y', c_uint),
    ('z', c_uint),
    ('w', c_uint),
]
# ./my_CUDA2100_vector_types.h 199
class long1(Structure):
    pass
long1._fields_ = [
    # ./my_CUDA2100_vector_types.h 199
    ('x', c_long),
]
# ./my_CUDA2100_vector_types.h 205
class ulong1(Structure):
    pass
ulong1._fields_ = [
    # ./my_CUDA2100_vector_types.h 205
    ('x', c_ulong),
]
# ./my_CUDA2100_vector_types.h 217
class long2(Structure):
    pass
long2._fields_ = [
    # ./my_CUDA2100_vector_types.h 217
    ('x', c_long),
    ('y', c_long),
]
# ./my_CUDA2100_vector_types.h 229
class ulong2(Structure):
    pass
ulong2._fields_ = [
    # ./my_CUDA2100_vector_types.h 229
    ('x', c_ulong),
    ('y', c_ulong),
]
# ./my_CUDA2100_vector_types.h 263
class float1(Structure):
    pass
float1._fields_ = [
    # ./my_CUDA2100_vector_types.h 263
    ('x', c_float),
]
# ./my_CUDA2100_vector_types.h 269
class float2(Structure):
    pass
float2._fields_ = [
    # ./my_CUDA2100_vector_types.h 269
    ('x', c_float),
    ('y', c_float),
]
# ./my_CUDA2100_vector_types.h 275
class float3(Structure):
    pass
float3._fields_ = [
    # ./my_CUDA2100_vector_types.h 275
    ('x', c_float),
    ('y', c_float),
    ('z', c_float),
]
# ./my_CUDA2100_vector_types.h 281
class float4(Structure):
    pass
float4._fields_ = [
    # ./my_CUDA2100_vector_types.h 281
    ('x', c_float),
    ('y', c_float),
    ('z', c_float),
    ('w', c_float),
]
# ./my_CUDA2100_vector_types.h 287
class longlong1(Structure):
    pass
longlong1._fields_ = [
    # ./my_CUDA2100_vector_types.h 287
    ('x', c_longlong),
]
# ./my_CUDA2100_vector_types.h 293
class ulonglong1(Structure):
    pass
ulonglong1._fields_ = [
    # ./my_CUDA2100_vector_types.h 293
    ('x', c_ulonglong),
]
# ./my_CUDA2100_vector_types.h 299
class longlong2(Structure):
    pass
longlong2._fields_ = [
    # ./my_CUDA2100_vector_types.h 299
    ('x', c_longlong),
    ('y', c_longlong),
]
# ./my_CUDA2100_vector_types.h 305
class ulonglong2(Structure):
    pass
ulonglong2._fields_ = [
    # ./my_CUDA2100_vector_types.h 305
    ('x', c_ulonglong),
    ('y', c_ulonglong),
]
# ./my_CUDA2100_vector_types.h 311
class double1(Structure):
    pass
double1._fields_ = [
    # ./my_CUDA2100_vector_types.h 311
    ('x', c_double),
]
# ./my_CUDA2100_vector_types.h 317
class double2(Structure):
    pass
double2._fields_ = [
    # ./my_CUDA2100_vector_types.h 317
    ('x', c_double),
    ('y', c_double),
]
# ./my_CUDA2100_vector_types.h 384
class long3(Structure):
    pass
long3._fields_ = [
    # ./my_CUDA2100_vector_types.h 384
]
# ./my_CUDA2100_vector_types.h 386
class ulong3(Structure):
    pass
ulong3._fields_ = [
    # ./my_CUDA2100_vector_types.h 386
]
# ./my_CUDA2100_vector_types.h 388
class long4(Structure):
    pass
long4._fields_ = [
    # ./my_CUDA2100_vector_types.h 388
]
# ./my_CUDA2100_vector_types.h 390
class ulong4(Structure):
    pass
ulong4._fields_ = [
    # ./my_CUDA2100_vector_types.h 390
]
# ./my_CUDA2100_vector_types.h 423
class dim3(Structure):
    pass
dim3._fields_ = [
    # ./my_CUDA2100_vector_types.h 423
    ('x', c_uint),
    ('y', c_uint),
    ('z', c_uint),
]
ptrdiff_t = c_long
size_t = c_ulong
# /usr/local/cuda/include/driver_types.h 113
class cudaChannelFormatDesc(Structure):
    pass

# values for enumeration 'cudaChannelFormatKind'
cudaChannelFormatKind = c_int # enum
cudaChannelFormatDesc._fields_ = [
    # /usr/local/cuda/include/driver_types.h 113
    ('x', c_int),
    ('y', c_int),
    ('z', c_int),
    ('w', c_int),
    ('f', cudaChannelFormatKind),
]
# /usr/local/cuda/include/channel_descriptor.h 63
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:63"""
# /usr/local/cuda/include/channel_descriptor.h 74
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:74"""
# /usr/local/cuda/include/channel_descriptor.h 81
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:81"""
# /usr/local/cuda/include/channel_descriptor.h 88
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:88"""
# /usr/local/cuda/include/channel_descriptor.h 95
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:95"""
# /usr/local/cuda/include/channel_descriptor.h 102
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:102"""
# /usr/local/cuda/include/channel_descriptor.h 109
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:109"""
# /usr/local/cuda/include/channel_descriptor.h 116
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:116"""
# /usr/local/cuda/include/channel_descriptor.h 123
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:123"""
# /usr/local/cuda/include/channel_descriptor.h 130
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:130"""
# /usr/local/cuda/include/channel_descriptor.h 137
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:137"""
# /usr/local/cuda/include/channel_descriptor.h 144
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:144"""
# /usr/local/cuda/include/channel_descriptor.h 151
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:151"""
# /usr/local/cuda/include/channel_descriptor.h 158
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:158"""
# /usr/local/cuda/include/channel_descriptor.h 165
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:165"""
# /usr/local/cuda/include/channel_descriptor.h 172
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:172"""
# /usr/local/cuda/include/channel_descriptor.h 179
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:179"""
# /usr/local/cuda/include/channel_descriptor.h 186
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:186"""
# /usr/local/cuda/include/channel_descriptor.h 193
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:193"""
# /usr/local/cuda/include/channel_descriptor.h 200
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:200"""
# /usr/local/cuda/include/channel_descriptor.h 207
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:207"""
# /usr/local/cuda/include/channel_descriptor.h 214
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:214"""
# /usr/local/cuda/include/channel_descriptor.h 221
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:221"""
# /usr/local/cuda/include/channel_descriptor.h 228
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:228"""
# /usr/local/cuda/include/channel_descriptor.h 235
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:235"""
# /usr/local/cuda/include/channel_descriptor.h 302
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:302"""
# /usr/local/cuda/include/channel_descriptor.h 309
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:309"""
# /usr/local/cuda/include/channel_descriptor.h 316
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:316"""
# /usr/local/cuda/include/channel_descriptor.h 323
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc()
cudaCreateChannelDesc.argtypes = []
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc()
/usr/local/cuda/include/channel_descriptor.h:323"""

# values for enumeration 'cudaError'
cudaError = c_int # enum
cudaError_t = cudaError
# /usr/local/cuda/include/driver_types.h 135
class cudaPitchedPtr(Structure):
    pass
# /usr/local/cuda/include/driver_types.h 144
class cudaExtent(Structure):
    pass
cudaExtent._fields_ = [
    # /usr/local/cuda/include/driver_types.h 144
    ('width', size_t),
    ('height', size_t),
    ('depth', size_t),
]
# /usr/local/cuda/include/cuda_runtime_api.h 88
cudaMalloc3D = _libraries['cudart'].cudaMalloc3D
cudaMalloc3D.restype = cudaError_t
# cudaMalloc3D(pitchDevPtr, extent)
cudaMalloc3D.argtypes = [POINTER(cudaPitchedPtr), cudaExtent]
cudaMalloc3D.__doc__ = \
"""cudaError_t cudaMalloc3D(cudaPitchedPtr * pitchDevPtr, cudaExtent extent)
/usr/local/cuda/include/cuda_runtime_api.h:88"""
# /usr/local/cuda/include/driver_types.h 122
class cudaArray(Structure):
    pass
# /usr/local/cuda/include/cuda_runtime_api.h 89
cudaMalloc3DArray = _libraries['cudart'].cudaMalloc3DArray
cudaMalloc3DArray.restype = cudaError_t
# cudaMalloc3DArray(arrayPtr, desc, extent)
cudaMalloc3DArray.argtypes = [POINTER(POINTER(cudaArray)), POINTER(cudaChannelFormatDesc), cudaExtent]
cudaMalloc3DArray.__doc__ = \
"""cudaError_t cudaMalloc3DArray(cudaArray * * arrayPtr, unknown * desc, cudaExtent extent)
/usr/local/cuda/include/cuda_runtime_api.h:89"""
cudaPitchedPtr._fields_ = [
    # /usr/local/cuda/include/driver_types.h 135
    ('ptr', c_void_p),
    ('pitch', size_t),
    ('xsize', size_t),
    ('ysize', size_t),
]
# /usr/local/cuda/include/cuda_runtime_api.h 90
cudaMemset3D = _libraries['cudart'].cudaMemset3D
cudaMemset3D.restype = cudaError_t
# cudaMemset3D(pitchDevPtr, value, extent)
cudaMemset3D.argtypes = [cudaPitchedPtr, c_int, cudaExtent]
cudaMemset3D.__doc__ = \
"""cudaError_t cudaMemset3D(cudaPitchedPtr pitchDevPtr, int value, cudaExtent extent)
/usr/local/cuda/include/cuda_runtime_api.h:90"""
# /usr/local/cuda/include/driver_types.h 160
class cudaMemcpy3DParms(Structure):
    pass
# /usr/local/cuda/include/driver_types.h 152
class cudaPos(Structure):
    pass
cudaPos._fields_ = [
    # /usr/local/cuda/include/driver_types.h 152
    ('x', size_t),
    ('y', size_t),
    ('z', size_t),
]

# values for enumeration 'cudaMemcpyKind'
cudaMemcpyKind = c_int # enum
cudaMemcpy3DParms._fields_ = [
    # /usr/local/cuda/include/driver_types.h 160
    ('srcArray', POINTER(cudaArray)),
    ('srcPos', cudaPos),
    ('srcPtr', cudaPitchedPtr),
    ('dstArray', POINTER(cudaArray)),
    ('dstPos', cudaPos),
    ('dstPtr', cudaPitchedPtr),
    ('extent', cudaExtent),
    ('kind', cudaMemcpyKind),
]
# /usr/local/cuda/include/cuda_runtime_api.h 91
cudaMemcpy3D = _libraries['cudart'].cudaMemcpy3D
cudaMemcpy3D.restype = cudaError_t
# cudaMemcpy3D(p)
cudaMemcpy3D.argtypes = [POINTER(cudaMemcpy3DParms)]
cudaMemcpy3D.__doc__ = \
"""cudaError_t cudaMemcpy3D(unknown * p)
/usr/local/cuda/include/cuda_runtime_api.h:91"""
cudaStream_t = c_int
# /usr/local/cuda/include/cuda_runtime_api.h 92
cudaMemcpy3DAsync = _libraries['cudart'].cudaMemcpy3DAsync
cudaMemcpy3DAsync.restype = cudaError_t
# cudaMemcpy3DAsync(p, stream)
cudaMemcpy3DAsync.argtypes = [POINTER(cudaMemcpy3DParms), cudaStream_t]
cudaMemcpy3DAsync.__doc__ = \
"""cudaError_t cudaMemcpy3DAsync(unknown * p, cudaStream_t stream)
/usr/local/cuda/include/cuda_runtime_api.h:92"""
# /usr/local/cuda/include/cuda_runtime_api.h 101
cudaMalloc = _libraries['cudart'].cudaMalloc
cudaMalloc.restype = cudaError_t
# cudaMalloc(devPtr, size)
cudaMalloc.argtypes = [POINTER(c_void_p), size_t]
cudaMalloc.__doc__ = \
"""cudaError_t cudaMalloc(void * * devPtr, size_t size)
/usr/local/cuda/include/cuda_runtime_api.h:101"""
# /usr/local/cuda/include/cuda_runtime_api.h 102
cudaMallocHost = _libraries['cudart'].cudaMallocHost
cudaMallocHost.restype = cudaError_t
# cudaMallocHost(ptr, size)
cudaMallocHost.argtypes = [POINTER(c_void_p), size_t]
cudaMallocHost.__doc__ = \
"""cudaError_t cudaMallocHost(void * * ptr, size_t size)
/usr/local/cuda/include/cuda_runtime_api.h:102"""
# /usr/local/cuda/include/cuda_runtime_api.h 103
cudaMallocPitch = _libraries['cudart'].cudaMallocPitch
cudaMallocPitch.restype = cudaError_t
# cudaMallocPitch(devPtr, pitch, width, height)
cudaMallocPitch.argtypes = [POINTER(c_void_p), POINTER(size_t), size_t, size_t]
cudaMallocPitch.__doc__ = \
"""cudaError_t cudaMallocPitch(void * * devPtr, size_t * pitch, size_t width, size_t height)
/usr/local/cuda/include/cuda_runtime_api.h:103"""
# /usr/local/cuda/include/cuda_runtime_api.h 104
cudaMallocArray = _libraries['cudart'].cudaMallocArray
cudaMallocArray.restype = cudaError_t
# cudaMallocArray(array, desc, width, height)
cudaMallocArray.argtypes = [POINTER(POINTER(cudaArray)), POINTER(cudaChannelFormatDesc), size_t, size_t]
cudaMallocArray.__doc__ = \
"""cudaError_t cudaMallocArray(cudaArray * * array, unknown * desc, size_t width, size_t height)
/usr/local/cuda/include/cuda_runtime_api.h:104"""
# /usr/local/cuda/include/cuda_runtime_api.h 105
cudaFree = _libraries['cudart'].cudaFree
cudaFree.restype = cudaError_t
# cudaFree(devPtr)
cudaFree.argtypes = [c_void_p]
cudaFree.__doc__ = \
"""cudaError_t cudaFree(void * devPtr)
/usr/local/cuda/include/cuda_runtime_api.h:105"""
# /usr/local/cuda/include/cuda_runtime_api.h 106
cudaFreeHost = _libraries['cudart'].cudaFreeHost
cudaFreeHost.restype = cudaError_t
# cudaFreeHost(ptr)
cudaFreeHost.argtypes = [c_void_p]
cudaFreeHost.__doc__ = \
"""cudaError_t cudaFreeHost(void * ptr)
/usr/local/cuda/include/cuda_runtime_api.h:106"""
# /usr/local/cuda/include/cuda_runtime_api.h 107
cudaFreeArray = _libraries['cudart'].cudaFreeArray
cudaFreeArray.restype = cudaError_t
# cudaFreeArray(array)
cudaFreeArray.argtypes = [POINTER(cudaArray)]
cudaFreeArray.__doc__ = \
"""cudaError_t cudaFreeArray(cudaArray * array)
/usr/local/cuda/include/cuda_runtime_api.h:107"""
# /usr/local/cuda/include/cuda_runtime_api.h 116
cudaMemcpy = _libraries['cudart'].cudaMemcpy
cudaMemcpy.restype = cudaError_t
# cudaMemcpy(dst, src, count, kind)
cudaMemcpy.argtypes = [c_void_p, c_void_p, size_t, cudaMemcpyKind]
cudaMemcpy.__doc__ = \
"""cudaError_t cudaMemcpy(void * dst, unknown * src, size_t count, cudaMemcpyKind kind)
/usr/local/cuda/include/cuda_runtime_api.h:116"""
# /usr/local/cuda/include/cuda_runtime_api.h 117
cudaMemcpyToArray = _libraries['cudart'].cudaMemcpyToArray
cudaMemcpyToArray.restype = cudaError_t
# cudaMemcpyToArray(dst, wOffset, hOffset, src, count, kind)
cudaMemcpyToArray.argtypes = [POINTER(cudaArray), size_t, size_t, c_void_p, size_t, cudaMemcpyKind]
cudaMemcpyToArray.__doc__ = \
"""cudaError_t cudaMemcpyToArray(cudaArray * dst, size_t wOffset, size_t hOffset, unknown * src, size_t count, cudaMemcpyKind kind)
/usr/local/cuda/include/cuda_runtime_api.h:117"""
cudaArray._fields_ = [
    # /usr/local/cuda/include/driver_types.h 122
]
# /usr/local/cuda/include/cuda_runtime_api.h 118
cudaMemcpyFromArray = _libraries['cudart'].cudaMemcpyFromArray
cudaMemcpyFromArray.restype = cudaError_t
# cudaMemcpyFromArray(dst, src, wOffset, hOffset, count, kind)
cudaMemcpyFromArray.argtypes = [c_void_p, POINTER(cudaArray), size_t, size_t, size_t, cudaMemcpyKind]
cudaMemcpyFromArray.__doc__ = \
"""cudaError_t cudaMemcpyFromArray(void * dst, unknown * src, size_t wOffset, size_t hOffset, size_t count, cudaMemcpyKind kind)
/usr/local/cuda/include/cuda_runtime_api.h:118"""
# /usr/local/cuda/include/cuda_runtime_api.h 119
cudaMemcpyArrayToArray = _libraries['cudart'].cudaMemcpyArrayToArray
cudaMemcpyArrayToArray.restype = cudaError_t
# cudaMemcpyArrayToArray(dst, wOffsetDst, hOffsetDst, src, wOffsetSrc, hOffsetSrc, count, kind)
cudaMemcpyArrayToArray.argtypes = [POINTER(cudaArray), size_t, size_t, POINTER(cudaArray), size_t, size_t, size_t, cudaMemcpyKind]
cudaMemcpyArrayToArray.__doc__ = \
"""cudaError_t cudaMemcpyArrayToArray(cudaArray * dst, size_t wOffsetDst, size_t hOffsetDst, unknown * src, size_t wOffsetSrc, size_t hOffsetSrc, size_t count, cudaMemcpyKind kind)
/usr/local/cuda/include/cuda_runtime_api.h:119"""
# /usr/local/cuda/include/cuda_runtime_api.h 120
cudaMemcpy2D = _libraries['cudart'].cudaMemcpy2D
cudaMemcpy2D.restype = cudaError_t
# cudaMemcpy2D(dst, dpitch, src, spitch, width, height, kind)
cudaMemcpy2D.argtypes = [c_void_p, size_t, c_void_p, size_t, size_t, size_t, cudaMemcpyKind]
cudaMemcpy2D.__doc__ = \
"""cudaError_t cudaMemcpy2D(void * dst, size_t dpitch, unknown * src, size_t spitch, size_t width, size_t height, cudaMemcpyKind kind)
/usr/local/cuda/include/cuda_runtime_api.h:120"""
# /usr/local/cuda/include/cuda_runtime_api.h 121
cudaMemcpy2DToArray = _libraries['cudart'].cudaMemcpy2DToArray
cudaMemcpy2DToArray.restype = cudaError_t
# cudaMemcpy2DToArray(dst, wOffset, hOffset, src, spitch, width, height, kind)
cudaMemcpy2DToArray.argtypes = [POINTER(cudaArray), size_t, size_t, c_void_p, size_t, size_t, size_t, cudaMemcpyKind]
cudaMemcpy2DToArray.__doc__ = \
"""cudaError_t cudaMemcpy2DToArray(cudaArray * dst, size_t wOffset, size_t hOffset, unknown * src, size_t spitch, size_t width, size_t height, cudaMemcpyKind kind)
/usr/local/cuda/include/cuda_runtime_api.h:121"""
# /usr/local/cuda/include/cuda_runtime_api.h 122
cudaMemcpy2DFromArray = _libraries['cudart'].cudaMemcpy2DFromArray
cudaMemcpy2DFromArray.restype = cudaError_t
# cudaMemcpy2DFromArray(dst, dpitch, src, wOffset, hOffset, width, height, kind)
cudaMemcpy2DFromArray.argtypes = [c_void_p, size_t, POINTER(cudaArray), size_t, size_t, size_t, size_t, cudaMemcpyKind]
cudaMemcpy2DFromArray.__doc__ = \
"""cudaError_t cudaMemcpy2DFromArray(void * dst, size_t dpitch, unknown * src, size_t wOffset, size_t hOffset, size_t width, size_t height, cudaMemcpyKind kind)
/usr/local/cuda/include/cuda_runtime_api.h:122"""
# /usr/local/cuda/include/cuda_runtime_api.h 123
cudaMemcpy2DArrayToArray = _libraries['cudart'].cudaMemcpy2DArrayToArray
cudaMemcpy2DArrayToArray.restype = cudaError_t
# cudaMemcpy2DArrayToArray(dst, wOffsetDst, hOffsetDst, src, wOffsetSrc, hOffsetSrc, width, height, kind)
cudaMemcpy2DArrayToArray.argtypes = [POINTER(cudaArray), size_t, size_t, POINTER(cudaArray), size_t, size_t, size_t, size_t, cudaMemcpyKind]
cudaMemcpy2DArrayToArray.__doc__ = \
"""cudaError_t cudaMemcpy2DArrayToArray(cudaArray * dst, size_t wOffsetDst, size_t hOffsetDst, unknown * src, size_t wOffsetSrc, size_t hOffsetSrc, size_t width, size_t height, cudaMemcpyKind kind)
/usr/local/cuda/include/cuda_runtime_api.h:123"""
# /usr/local/cuda/include/cuda_runtime_api.h 124
cudaMemcpyToSymbol = _libraries['cudart'].cudaMemcpyToSymbol
cudaMemcpyToSymbol.restype = cudaError_t
# cudaMemcpyToSymbol(symbol, src, count, offset, kind)
cudaMemcpyToSymbol.argtypes = [STRING, c_void_p, size_t, size_t, cudaMemcpyKind]
cudaMemcpyToSymbol.__doc__ = \
"""cudaError_t cudaMemcpyToSymbol(unknown * symbol, unknown * src, size_t count, size_t offset, cudaMemcpyKind kind)
/usr/local/cuda/include/cuda_runtime_api.h:124"""
# /usr/local/cuda/include/cuda_runtime_api.h 125
cudaMemcpyFromSymbol = _libraries['cudart'].cudaMemcpyFromSymbol
cudaMemcpyFromSymbol.restype = cudaError_t
# cudaMemcpyFromSymbol(dst, symbol, count, offset, kind)
cudaMemcpyFromSymbol.argtypes = [c_void_p, STRING, size_t, size_t, cudaMemcpyKind]
cudaMemcpyFromSymbol.__doc__ = \
"""cudaError_t cudaMemcpyFromSymbol(void * dst, unknown * symbol, size_t count, size_t offset, cudaMemcpyKind kind)
/usr/local/cuda/include/cuda_runtime_api.h:125"""
# /usr/local/cuda/include/cuda_runtime_api.h 133
cudaMemcpyAsync = _libraries['cudart'].cudaMemcpyAsync
cudaMemcpyAsync.restype = cudaError_t
# cudaMemcpyAsync(dst, src, count, kind, stream)
cudaMemcpyAsync.argtypes = [c_void_p, c_void_p, size_t, cudaMemcpyKind, cudaStream_t]
cudaMemcpyAsync.__doc__ = \
"""cudaError_t cudaMemcpyAsync(void * dst, unknown * src, size_t count, cudaMemcpyKind kind, cudaStream_t stream)
/usr/local/cuda/include/cuda_runtime_api.h:133"""
# /usr/local/cuda/include/cuda_runtime_api.h 134
cudaMemcpyToArrayAsync = _libraries['cudart'].cudaMemcpyToArrayAsync
cudaMemcpyToArrayAsync.restype = cudaError_t
# cudaMemcpyToArrayAsync(dst, wOffset, hOffset, src, count, kind, stream)
cudaMemcpyToArrayAsync.argtypes = [POINTER(cudaArray), size_t, size_t, c_void_p, size_t, cudaMemcpyKind, cudaStream_t]
cudaMemcpyToArrayAsync.__doc__ = \
"""cudaError_t cudaMemcpyToArrayAsync(cudaArray * dst, size_t wOffset, size_t hOffset, unknown * src, size_t count, cudaMemcpyKind kind, cudaStream_t stream)
/usr/local/cuda/include/cuda_runtime_api.h:134"""
# /usr/local/cuda/include/cuda_runtime_api.h 135
cudaMemcpyFromArrayAsync = _libraries['cudart'].cudaMemcpyFromArrayAsync
cudaMemcpyFromArrayAsync.restype = cudaError_t
# cudaMemcpyFromArrayAsync(dst, src, wOffset, hOffset, count, kind, stream)
cudaMemcpyFromArrayAsync.argtypes = [c_void_p, POINTER(cudaArray), size_t, size_t, size_t, cudaMemcpyKind, cudaStream_t]
cudaMemcpyFromArrayAsync.__doc__ = \
"""cudaError_t cudaMemcpyFromArrayAsync(void * dst, unknown * src, size_t wOffset, size_t hOffset, size_t count, cudaMemcpyKind kind, cudaStream_t stream)
/usr/local/cuda/include/cuda_runtime_api.h:135"""
# /usr/local/cuda/include/cuda_runtime_api.h 136
cudaMemcpy2DAsync = _libraries['cudart'].cudaMemcpy2DAsync
cudaMemcpy2DAsync.restype = cudaError_t
# cudaMemcpy2DAsync(dst, dpitch, src, spitch, width, height, kind, stream)
cudaMemcpy2DAsync.argtypes = [c_void_p, size_t, c_void_p, size_t, size_t, size_t, cudaMemcpyKind, cudaStream_t]
cudaMemcpy2DAsync.__doc__ = \
"""cudaError_t cudaMemcpy2DAsync(void * dst, size_t dpitch, unknown * src, size_t spitch, size_t width, size_t height, cudaMemcpyKind kind, cudaStream_t stream)
/usr/local/cuda/include/cuda_runtime_api.h:136"""
# /usr/local/cuda/include/cuda_runtime_api.h 137
cudaMemcpy2DToArrayAsync = _libraries['cudart'].cudaMemcpy2DToArrayAsync
cudaMemcpy2DToArrayAsync.restype = cudaError_t
# cudaMemcpy2DToArrayAsync(dst, wOffset, hOffset, src, spitch, width, height, kind, stream)
cudaMemcpy2DToArrayAsync.argtypes = [POINTER(cudaArray), size_t, size_t, c_void_p, size_t, size_t, size_t, cudaMemcpyKind, cudaStream_t]
cudaMemcpy2DToArrayAsync.__doc__ = \
"""cudaError_t cudaMemcpy2DToArrayAsync(cudaArray * dst, size_t wOffset, size_t hOffset, unknown * src, size_t spitch, size_t width, size_t height, cudaMemcpyKind kind, cudaStream_t stream)
/usr/local/cuda/include/cuda_runtime_api.h:137"""
# /usr/local/cuda/include/cuda_runtime_api.h 138
cudaMemcpy2DFromArrayAsync = _libraries['cudart'].cudaMemcpy2DFromArrayAsync
cudaMemcpy2DFromArrayAsync.restype = cudaError_t
# cudaMemcpy2DFromArrayAsync(dst, dpitch, src, wOffset, hOffset, width, height, kind, stream)
cudaMemcpy2DFromArrayAsync.argtypes = [c_void_p, size_t, POINTER(cudaArray), size_t, size_t, size_t, size_t, cudaMemcpyKind, cudaStream_t]
cudaMemcpy2DFromArrayAsync.__doc__ = \
"""cudaError_t cudaMemcpy2DFromArrayAsync(void * dst, size_t dpitch, unknown * src, size_t wOffset, size_t hOffset, size_t width, size_t height, cudaMemcpyKind kind, cudaStream_t stream)
/usr/local/cuda/include/cuda_runtime_api.h:138"""
# /usr/local/cuda/include/cuda_runtime_api.h 139
cudaMemcpyToSymbolAsync = _libraries['cudart'].cudaMemcpyToSymbolAsync
cudaMemcpyToSymbolAsync.restype = cudaError_t
# cudaMemcpyToSymbolAsync(symbol, src, count, offset, kind, stream)
cudaMemcpyToSymbolAsync.argtypes = [STRING, c_void_p, size_t, size_t, cudaMemcpyKind, cudaStream_t]
cudaMemcpyToSymbolAsync.__doc__ = \
"""cudaError_t cudaMemcpyToSymbolAsync(unknown * symbol, unknown * src, size_t count, size_t offset, cudaMemcpyKind kind, cudaStream_t stream)
/usr/local/cuda/include/cuda_runtime_api.h:139"""
# /usr/local/cuda/include/cuda_runtime_api.h 140
cudaMemcpyFromSymbolAsync = _libraries['cudart'].cudaMemcpyFromSymbolAsync
cudaMemcpyFromSymbolAsync.restype = cudaError_t
# cudaMemcpyFromSymbolAsync(dst, symbol, count, offset, kind, stream)
cudaMemcpyFromSymbolAsync.argtypes = [c_void_p, STRING, size_t, size_t, cudaMemcpyKind, cudaStream_t]
cudaMemcpyFromSymbolAsync.__doc__ = \
"""cudaError_t cudaMemcpyFromSymbolAsync(void * dst, unknown * symbol, size_t count, size_t offset, cudaMemcpyKind kind, cudaStream_t stream)
/usr/local/cuda/include/cuda_runtime_api.h:140"""
# /usr/local/cuda/include/cuda_runtime_api.h 148
cudaMemset = _libraries['cudart'].cudaMemset
cudaMemset.restype = cudaError_t
# cudaMemset(mem, c, count)
cudaMemset.argtypes = [c_void_p, c_int, size_t]
cudaMemset.__doc__ = \
"""cudaError_t cudaMemset(void * mem, int c, size_t count)
/usr/local/cuda/include/cuda_runtime_api.h:148"""
# /usr/local/cuda/include/cuda_runtime_api.h 149
cudaMemset2D = _libraries['cudart'].cudaMemset2D
cudaMemset2D.restype = cudaError_t
# cudaMemset2D(mem, pitch, c, width, height)
cudaMemset2D.argtypes = [c_void_p, size_t, c_int, size_t, size_t]
cudaMemset2D.__doc__ = \
"""cudaError_t cudaMemset2D(void * mem, size_t pitch, int c, size_t width, size_t height)
/usr/local/cuda/include/cuda_runtime_api.h:149"""
# /usr/local/cuda/include/cuda_runtime_api.h 157
cudaGetSymbolAddress = _libraries['cudart'].cudaGetSymbolAddress
cudaGetSymbolAddress.restype = cudaError_t
# cudaGetSymbolAddress(devPtr, symbol)
cudaGetSymbolAddress.argtypes = [POINTER(c_void_p), STRING]
cudaGetSymbolAddress.__doc__ = \
"""cudaError_t cudaGetSymbolAddress(void * * devPtr, unknown * symbol)
/usr/local/cuda/include/cuda_runtime_api.h:157"""
# /usr/local/cuda/include/cuda_runtime_api.h 158
cudaGetSymbolSize = _libraries['cudart'].cudaGetSymbolSize
cudaGetSymbolSize.restype = cudaError_t
# cudaGetSymbolSize(size, symbol)
cudaGetSymbolSize.argtypes = [POINTER(size_t), STRING]
cudaGetSymbolSize.__doc__ = \
"""cudaError_t cudaGetSymbolSize(size_t * size, unknown * symbol)
/usr/local/cuda/include/cuda_runtime_api.h:158"""
# /usr/local/cuda/include/cuda_runtime_api.h 166
cudaGetDeviceCount = _libraries['cudart'].cudaGetDeviceCount
cudaGetDeviceCount.restype = cudaError_t
# cudaGetDeviceCount(count)
cudaGetDeviceCount.argtypes = [POINTER(c_int)]
cudaGetDeviceCount.__doc__ = \
"""cudaError_t cudaGetDeviceCount(int * count)
/usr/local/cuda/include/cuda_runtime_api.h:166"""
# /usr/local/cuda/include/driver_types.h 175
class cudaDeviceProp(Structure):
    pass
# /usr/local/cuda/include/cuda_runtime_api.h 167
cudaGetDeviceProperties = _libraries['cudart'].cudaGetDeviceProperties
cudaGetDeviceProperties.restype = cudaError_t
# cudaGetDeviceProperties(prop, device)
cudaGetDeviceProperties.argtypes = [POINTER(cudaDeviceProp), c_int]
cudaGetDeviceProperties.__doc__ = \
"""cudaError_t cudaGetDeviceProperties(cudaDeviceProp * prop, int device)
/usr/local/cuda/include/cuda_runtime_api.h:167"""
cudaDeviceProp._fields_ = [
    # /usr/local/cuda/include/driver_types.h 175
    ('name', c_char * 256),
    ('totalGlobalMem', size_t),
    ('sharedMemPerBlock', size_t),
    ('regsPerBlock', c_int),
    ('warpSize', c_int),
    ('memPitch', size_t),
    ('maxThreadsPerBlock', c_int),
    ('maxThreadsDim', c_int * 3),
    ('maxGridSize', c_int * 3),
    ('clockRate', c_int),
    ('totalConstMem', size_t),
    ('major', c_int),
    ('minor', c_int),
    ('textureAlignment', size_t),
    ('deviceOverlap', c_int),
    ('multiProcessorCount', c_int),
    ('kernelExecTimeoutEnabled', c_int),
    ('__cudaReserved', c_int * 39),
]
# /usr/local/cuda/include/cuda_runtime_api.h 168
cudaChooseDevice = _libraries['cudart'].cudaChooseDevice
cudaChooseDevice.restype = cudaError_t
# cudaChooseDevice(device, prop)
cudaChooseDevice.argtypes = [POINTER(c_int), POINTER(cudaDeviceProp)]
cudaChooseDevice.__doc__ = \
"""cudaError_t cudaChooseDevice(int * device, unknown * prop)
/usr/local/cuda/include/cuda_runtime_api.h:168"""
# /usr/local/cuda/include/cuda_runtime_api.h 169
cudaSetDevice = _libraries['cudart'].cudaSetDevice
cudaSetDevice.restype = cudaError_t
# cudaSetDevice(device)
cudaSetDevice.argtypes = [c_int]
cudaSetDevice.__doc__ = \
"""cudaError_t cudaSetDevice(int device)
/usr/local/cuda/include/cuda_runtime_api.h:169"""
# /usr/local/cuda/include/cuda_runtime_api.h 170
cudaGetDevice = _libraries['cudart'].cudaGetDevice
cudaGetDevice.restype = cudaError_t
# cudaGetDevice(device)
cudaGetDevice.argtypes = [POINTER(c_int)]
cudaGetDevice.__doc__ = \
"""cudaError_t cudaGetDevice(int * device)
/usr/local/cuda/include/cuda_runtime_api.h:170"""
# /usr/local/cuda/include/texture_types.h 76
class textureReference(Structure):
    pass

# values for enumeration 'cudaTextureFilterMode'
cudaTextureFilterMode = c_int # enum

# values for enumeration 'cudaTextureAddressMode'
cudaTextureAddressMode = c_int # enum
textureReference._fields_ = [
    # /usr/local/cuda/include/texture_types.h 76
    ('normalized', c_int),
    ('filterMode', cudaTextureFilterMode),
    ('addressMode', cudaTextureAddressMode * 3),
    ('channelDesc', cudaChannelFormatDesc),
    ('__cudaReserved', c_int * 16),
]
# /usr/local/cuda/include/cuda_runtime_api.h 178
cudaBindTexture = _libraries['cudart'].cudaBindTexture
cudaBindTexture.restype = cudaError_t
# cudaBindTexture(offset, texref, devPtr, desc, size)
cudaBindTexture.argtypes = [POINTER(size_t), POINTER(textureReference), c_void_p, POINTER(cudaChannelFormatDesc), size_t]
cudaBindTexture.__doc__ = \
"""cudaError_t cudaBindTexture(size_t * offset, unknown * texref, unknown * devPtr, unknown * desc, size_t size)
/usr/local/cuda/include/cuda_runtime_api.h:178"""
# /usr/local/cuda/include/cuda_runtime_api.h 179
cudaBindTextureToArray = _libraries['cudart'].cudaBindTextureToArray
cudaBindTextureToArray.restype = cudaError_t
# cudaBindTextureToArray(texref, array, desc)
cudaBindTextureToArray.argtypes = [POINTER(textureReference), POINTER(cudaArray), POINTER(cudaChannelFormatDesc)]
cudaBindTextureToArray.__doc__ = \
"""cudaError_t cudaBindTextureToArray(unknown * texref, unknown * array, unknown * desc)
/usr/local/cuda/include/cuda_runtime_api.h:179"""
# /usr/local/cuda/include/cuda_runtime_api.h 180
cudaUnbindTexture = _libraries['cudart'].cudaUnbindTexture
cudaUnbindTexture.restype = cudaError_t
# cudaUnbindTexture(texref)
cudaUnbindTexture.argtypes = [POINTER(textureReference)]
cudaUnbindTexture.__doc__ = \
"""cudaError_t cudaUnbindTexture(unknown * texref)
/usr/local/cuda/include/cuda_runtime_api.h:180"""
# /usr/local/cuda/include/cuda_runtime_api.h 181
cudaGetTextureAlignmentOffset = _libraries['cudart'].cudaGetTextureAlignmentOffset
cudaGetTextureAlignmentOffset.restype = cudaError_t
# cudaGetTextureAlignmentOffset(offset, texref)
cudaGetTextureAlignmentOffset.argtypes = [POINTER(size_t), POINTER(textureReference)]
cudaGetTextureAlignmentOffset.__doc__ = \
"""cudaError_t cudaGetTextureAlignmentOffset(size_t * offset, unknown * texref)
/usr/local/cuda/include/cuda_runtime_api.h:181"""
# /usr/local/cuda/include/cuda_runtime_api.h 182
cudaGetTextureReference = _libraries['cudart'].cudaGetTextureReference
cudaGetTextureReference.restype = cudaError_t
# cudaGetTextureReference(texref, symbol)
cudaGetTextureReference.argtypes = [POINTER(POINTER(textureReference)), STRING]
cudaGetTextureReference.__doc__ = \
"""cudaError_t cudaGetTextureReference(unknown * * texref, unknown * symbol)
/usr/local/cuda/include/cuda_runtime_api.h:182"""
# /usr/local/cuda/include/cuda_runtime_api.h 190
cudaGetChannelDesc = _libraries['cudart'].cudaGetChannelDesc
cudaGetChannelDesc.restype = cudaError_t
# cudaGetChannelDesc(desc, array)
cudaGetChannelDesc.argtypes = [POINTER(cudaChannelFormatDesc), POINTER(cudaArray)]
cudaGetChannelDesc.__doc__ = \
"""cudaError_t cudaGetChannelDesc(cudaChannelFormatDesc * desc, unknown * array)
/usr/local/cuda/include/cuda_runtime_api.h:190"""
# /usr/local/cuda/include/cuda_runtime_api.h 191
cudaCreateChannelDesc = _libraries['cudart'].cudaCreateChannelDesc
cudaCreateChannelDesc.restype = cudaChannelFormatDesc
# cudaCreateChannelDesc(x, y, z, w, f)
cudaCreateChannelDesc.argtypes = [c_int, c_int, c_int, c_int, cudaChannelFormatKind]
cudaCreateChannelDesc.__doc__ = \
"""cudaChannelFormatDesc cudaCreateChannelDesc(int x, int y, int z, int w, cudaChannelFormatKind f)
/usr/local/cuda/include/cuda_runtime_api.h:191"""
# /usr/local/cuda/include/cuda_runtime_api.h 199
cudaGetLastError = _libraries['cudart'].cudaGetLastError
cudaGetLastError.restype = cudaError_t
# cudaGetLastError()
cudaGetLastError.argtypes = []
cudaGetLastError.__doc__ = \
"""cudaError_t cudaGetLastError()
/usr/local/cuda/include/cuda_runtime_api.h:199"""
# /usr/local/cuda/include/cuda_runtime_api.h 200
cudaGetErrorString = _libraries['cudart'].cudaGetErrorString
cudaGetErrorString.restype = STRING
# cudaGetErrorString(error)
cudaGetErrorString.argtypes = [cudaError_t]
cudaGetErrorString.__doc__ = \
"""unknown * cudaGetErrorString(cudaError_t error)
/usr/local/cuda/include/cuda_runtime_api.h:200"""
# /usr/local/cuda/include/cuda_runtime_api.h 208
cudaConfigureCall = _libraries['cudart'].cudaConfigureCall
cudaConfigureCall.restype = cudaError_t
# cudaConfigureCall(gridDim, blockDim, sharedMem, stream)
cudaConfigureCall.argtypes = [dim3, dim3, size_t, cudaStream_t]
cudaConfigureCall.__doc__ = \
"""cudaError_t cudaConfigureCall(dim3 gridDim, dim3 blockDim, size_t sharedMem, cudaStream_t stream)
/usr/local/cuda/include/cuda_runtime_api.h:208"""
# /usr/local/cuda/include/cuda_runtime_api.h 209
cudaSetupArgument = _libraries['cudart'].cudaSetupArgument
cudaSetupArgument.restype = cudaError_t
# cudaSetupArgument(arg, size, offset)
cudaSetupArgument.argtypes = [c_void_p, size_t, size_t]
cudaSetupArgument.__doc__ = \
"""cudaError_t cudaSetupArgument(unknown * arg, size_t size, size_t offset)
/usr/local/cuda/include/cuda_runtime_api.h:209"""
# /usr/local/cuda/include/cuda_runtime_api.h 210
cudaLaunch = _libraries['cudart'].cudaLaunch
cudaLaunch.restype = cudaError_t
# cudaLaunch(symbol)
cudaLaunch.argtypes = [STRING]
cudaLaunch.__doc__ = \
"""cudaError_t cudaLaunch(unknown * symbol)
/usr/local/cuda/include/cuda_runtime_api.h:210"""
# /usr/local/cuda/include/cuda_runtime_api.h 218
cudaStreamCreate = _libraries['cudart'].cudaStreamCreate
cudaStreamCreate.restype = cudaError_t
# cudaStreamCreate(stream)
cudaStreamCreate.argtypes = [POINTER(cudaStream_t)]
cudaStreamCreate.__doc__ = \
"""cudaError_t cudaStreamCreate(cudaStream_t * stream)
/usr/local/cuda/include/cuda_runtime_api.h:218"""
# /usr/local/cuda/include/cuda_runtime_api.h 219
cudaStreamDestroy = _libraries['cudart'].cudaStreamDestroy
cudaStreamDestroy.restype = cudaError_t
# cudaStreamDestroy(stream)
cudaStreamDestroy.argtypes = [cudaStream_t]
cudaStreamDestroy.__doc__ = \
"""cudaError_t cudaStreamDestroy(cudaStream_t stream)
/usr/local/cuda/include/cuda_runtime_api.h:219"""
# /usr/local/cuda/include/cuda_runtime_api.h 220
cudaStreamSynchronize = _libraries['cudart'].cudaStreamSynchronize
cudaStreamSynchronize.restype = cudaError_t
# cudaStreamSynchronize(stream)
cudaStreamSynchronize.argtypes = [cudaStream_t]
cudaStreamSynchronize.__doc__ = \
"""cudaError_t cudaStreamSynchronize(cudaStream_t stream)
/usr/local/cuda/include/cuda_runtime_api.h:220"""
# /usr/local/cuda/include/cuda_runtime_api.h 221
cudaStreamQuery = _libraries['cudart'].cudaStreamQuery
cudaStreamQuery.restype = cudaError_t
# cudaStreamQuery(stream)
cudaStreamQuery.argtypes = [cudaStream_t]
cudaStreamQuery.__doc__ = \
"""cudaError_t cudaStreamQuery(cudaStream_t stream)
/usr/local/cuda/include/cuda_runtime_api.h:221"""
cudaEvent_t = c_int
# /usr/local/cuda/include/cuda_runtime_api.h 229
cudaEventCreate = _libraries['cudart'].cudaEventCreate
cudaEventCreate.restype = cudaError_t
# cudaEventCreate(event)
cudaEventCreate.argtypes = [POINTER(cudaEvent_t)]
cudaEventCreate.__doc__ = \
"""cudaError_t cudaEventCreate(cudaEvent_t * event)
/usr/local/cuda/include/cuda_runtime_api.h:229"""
# /usr/local/cuda/include/cuda_runtime_api.h 230
cudaEventRecord = _libraries['cudart'].cudaEventRecord
cudaEventRecord.restype = cudaError_t
# cudaEventRecord(event, stream)
cudaEventRecord.argtypes = [cudaEvent_t, cudaStream_t]
cudaEventRecord.__doc__ = \
"""cudaError_t cudaEventRecord(cudaEvent_t event, cudaStream_t stream)
/usr/local/cuda/include/cuda_runtime_api.h:230"""
# /usr/local/cuda/include/cuda_runtime_api.h 231
cudaEventQuery = _libraries['cudart'].cudaEventQuery
cudaEventQuery.restype = cudaError_t
# cudaEventQuery(event)
cudaEventQuery.argtypes = [cudaEvent_t]
cudaEventQuery.__doc__ = \
"""cudaError_t cudaEventQuery(cudaEvent_t event)
/usr/local/cuda/include/cuda_runtime_api.h:231"""
# /usr/local/cuda/include/cuda_runtime_api.h 232
cudaEventSynchronize = _libraries['cudart'].cudaEventSynchronize
cudaEventSynchronize.restype = cudaError_t
# cudaEventSynchronize(event)
cudaEventSynchronize.argtypes = [cudaEvent_t]
cudaEventSynchronize.__doc__ = \
"""cudaError_t cudaEventSynchronize(cudaEvent_t event)
/usr/local/cuda/include/cuda_runtime_api.h:232"""
# /usr/local/cuda/include/cuda_runtime_api.h 233
cudaEventDestroy = _libraries['cudart'].cudaEventDestroy
cudaEventDestroy.restype = cudaError_t
# cudaEventDestroy(event)
cudaEventDestroy.argtypes = [cudaEvent_t]
cudaEventDestroy.__doc__ = \
"""cudaError_t cudaEventDestroy(cudaEvent_t event)
/usr/local/cuda/include/cuda_runtime_api.h:233"""
# /usr/local/cuda/include/cuda_runtime_api.h 234
cudaEventElapsedTime = _libraries['cudart'].cudaEventElapsedTime
cudaEventElapsedTime.restype = cudaError_t
# cudaEventElapsedTime(ms, start, end)
cudaEventElapsedTime.argtypes = [POINTER(c_float), cudaEvent_t, cudaEvent_t]
cudaEventElapsedTime.__doc__ = \
"""cudaError_t cudaEventElapsedTime(float * ms, cudaEvent_t start, cudaEvent_t end)
/usr/local/cuda/include/cuda_runtime_api.h:234"""
# /usr/local/cuda/include/cuda_runtime_api.h 242
cudaSetDoubleForDevice = _libraries['cudart'].cudaSetDoubleForDevice
cudaSetDoubleForDevice.restype = cudaError_t
# cudaSetDoubleForDevice(d)
cudaSetDoubleForDevice.argtypes = [POINTER(c_double)]
cudaSetDoubleForDevice.__doc__ = \
"""cudaError_t cudaSetDoubleForDevice(double * d)
/usr/local/cuda/include/cuda_runtime_api.h:242"""
# /usr/local/cuda/include/cuda_runtime_api.h 243
cudaSetDoubleForHost = _libraries['cudart'].cudaSetDoubleForHost
cudaSetDoubleForHost.restype = cudaError_t
# cudaSetDoubleForHost(d)
cudaSetDoubleForHost.argtypes = [POINTER(c_double)]
cudaSetDoubleForHost.__doc__ = \
"""cudaError_t cudaSetDoubleForHost(double * d)
/usr/local/cuda/include/cuda_runtime_api.h:243"""
# /usr/local/cuda/include/cuda_runtime_api.h 251
cudaThreadExit = _libraries['cudart'].cudaThreadExit
cudaThreadExit.restype = cudaError_t
# cudaThreadExit()
cudaThreadExit.argtypes = []
cudaThreadExit.__doc__ = \
"""cudaError_t cudaThreadExit()
/usr/local/cuda/include/cuda_runtime_api.h:251"""
# /usr/local/cuda/include/cuda_runtime_api.h 252
cudaThreadSynchronize = _libraries['cudart'].cudaThreadSynchronize
cudaThreadSynchronize.restype = cudaError_t
# cudaThreadSynchronize()
cudaThreadSynchronize.argtypes = []
cudaThreadSynchronize.__doc__ = \
"""cudaError_t cudaThreadSynchronize()
/usr/local/cuda/include/cuda_runtime_api.h:252"""

# values for enumeration 'cudaRoundMode'
cudaRoundMode = c_int # enum

# values for enumeration 'cudaTextureReadMode'
cudaTextureReadMode = c_int # enum
__all__ = ['cudaMalloc3DArray', 'cudaGetTextureAlignmentOffset',
           'cudaErrorInvalidResourceHandle', 'cudaAddressModeWrap',
           'cudaErrorTextureNotBound', 'cudaStream_t',
           'cudaMemcpyHostToHost', 'size_t', 'cudaGetSymbolAddress',
           'cudaMallocArray', 'cudaPitchedPtr',
           'cudaErrorInvalidNormSetting', 'cudaErrorCudartUnloading',
           'ushort1', 'ushort2', 'ushort3', 'ushort4', 'double2',
           'cudaMemcpy2D', 'cudaThreadSynchronize', 'double1',
           'ulong3', 'ulong2', 'ulong1', 'cudaMemcpyFromArrayAsync',
           'cudaMemcpyToArray', 'cudaErrorMixedDeviceExecution',
           'cudaPos', 'cudaThreadExit', 'cudaErrorMemoryAllocation',
           'cudaGetLastError', 'cudaChooseDevice',
           'cudaErrorMapBufferObjectFailed', 'cudaErrorLaunchFailure',
           'cudaMemcpyToSymbol', 'cudaStreamSynchronize',
           'cudaGetErrorString', 'uchar1', 'uchar3', 'uchar2',
           'uchar4', 'cudaMemcpy3D', 'float4',
           'cudaMemcpyDeviceToHost', 'cudaSetupArgument',
           'cudaBindTexture', 'cudaMemcpyFromSymbolAsync',
           'cudaChannelFormatDesc', 'cudaEventSynchronize',
           'cudaStreamQuery', 'cudaErrorMemoryValueTooLarge',
           'cudaErrorNotReady', 'cudaErrorInsufficientDriver',
           'cudaMemcpyHostToDevice', 'float1', 'float2', 'float3',
           'cudaErrorInvalidTextureBinding',
           'cudaErrorInvalidDeviceFunction',
           'cudaErrorPriorLaunchFailure', 'cudaMemcpy',
           'cudaChannelFormatKindNone', 'long3', 'cudaDeviceProp',
           'long2', 'cudaChannelFormatKindSigned',
           'cudaChannelFormatKindFloat', 'cudaCreateChannelDesc',
           'cudaMemcpy2DFromArrayAsync', 'cudaMalloc3D', 'ulong4',
           'cudaMemcpyFromArray', 'cudaErrorLaunchTimeout',
           'cudaReadModeNormalizedFloat', 'cudaUnbindTexture',
           'cudaGetDeviceProperties', 'cudaRoundMinInf',
           'cudaConfigureCall', 'cudaLaunch', 'cudaGetChannelDesc',
           'cudaMemcpyFromSymbol', 'cudaError_t', 'cudaMemset',
           'cudaRoundMode', 'cudaErrorUnmapBufferObjectFailed',
           'cudaGetTextureReference', 'cudaMemcpy2DToArrayAsync',
           'cudaMemset2D', 'cudaRoundPosInf', 'ptrdiff_t',
           'cudaErrorInvalidMemcpyDirection', 'short4',
           'cudaErrorInvalidDevice', 'cudaFree', 'short1', 'short2',
           'short3', 'cudaAddressModeClamp', 'cudaEvent_t',
           'cudaError', 'cudaMemcpyAsync', 'cudaEventCreate',
           'cudaSetDoubleForDevice', 'cudaErrorLaunchOutOfResources',
           'cudaMemcpy3DAsync', 'cudaMalloc', 'cudaStreamCreate',
           'cudaErrorTextureFetchFailed', 'cudaTextureFilterMode',
           'uint4', 'uint1', 'uint3', 'uint2',
           'cudaErrorInvalidFilterSetting', 'textureReference',
           'int4', 'cudaEventDestroy', 'int1', 'int3', 'int2',
           'cudaMallocHost', 'cudaMemcpy2DArrayToArray',
           'cudaEventElapsedTime', 'longlong1', 'cudaGetSymbolSize',
           'longlong2', 'cudaErrorInvalidValue', 'dim3',
           'cudaTextureReadMode', 'cudaGetDeviceCount',
           'cudaErrorMissingConfiguration', 'cudaMemcpy2DAsync',
           'cudaFilterModeLinear', 'cudaSetDevice',
           'cudaReadModeElementType', 'cudaErrorInvalidDevicePointer',
           'cudaEventRecord', 'ulonglong1', 'ulonglong2',
           'cudaSuccess', 'char1', 'char3', 'char2',
           'cudaTextureAddressMode', 'char4',
           'cudaErrorInvalidTexture', 'cudaErrorSynchronizationError',
           'cudaEventQuery', 'cudaErrorInitializationError',
           'cudaErrorInvalidPitchValue', 'cudaMemcpyToArrayAsync',
           'cudaFreeArray', 'cudaMemcpyDeviceToDevice',
           'cudaMemcpyArrayToArray', 'cudaRoundZero',
           'cudaMemcpy2DFromArray', 'cudaErrorApiFailureBase',
           'cudaMemcpyToSymbolAsync', 'cudaMemcpy2DToArray',
           'cudaErrorAddressOfConstant', 'cudaExtent',
           'cudaErrorInvalidHostPointer',
           'cudaErrorInvalidConfiguration', 'cudaRoundNearest',
           'cudaErrorUnknown', 'cudaFreeHost',
           'cudaErrorNotYetImplemented', 'cudaStreamDestroy',
           'cudaErrorStartupFailure', 'cudaMemcpyKind',
           'cudaMemset3D', 'cudaErrorInvalidSymbol',
           'cudaErrorInvalidChannelDescriptor', 'long1',
           'cudaMallocPitch', 'long4', 'cudaChannelFormatKind',
           'cudaChannelFormatKindUnsigned', 'cudaMemcpy3DParms',
           'cudaArray', 'cudaErrorSetOnActiveProcess',
           'cudaFilterModePoint', 'cudaSetDoubleForHost',
           'cudaBindTextureToArray', 'cudaGetDevice']
